### ISSUE TITLE
Switch 数据绑定问题

### ISSUE THREAD

**Issue by hdwong** [didi/cube-ui#103]
### Version
1.4.3

### Reproduction link
[https://codesandbox.io/s/jn3o1q27ww](https://codesandbox.io/s/jn3o1q27ww)

### Steps to reproduce
1. 点击 Switch 组件，观察 Value 变化
2. 确认 Switch 与 Value 绑定正常
3. 点击 ［Toggle value］ 按键
4. 确认按键能修改 Value 值

### What is expected?
通过按键可以修改 Value 同时正确改变 Switch 状态

### What is actually happening?
Switch 状态不能被 Value 修改

现在好像只能通过组件的 checkboxValue 属性值直接修改

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.0

**Comment by dolymood** [comment]
see https://github.com/didi/cube-ui/issues/102
