### ISSUE TITLE
cubi-view通过滑动的方式后退时，会发生闪动的现象

### ISSUE THREAD

**Issue by lyh2668** [didi/cube-ui#106]
### Version
1.5.0

### Reproduction link
[https://didi.github.io/cube-ui/example/#/](https://didi.github.io/cube-ui/example/#/)

### Steps to reproduce
1. 组件demo首页点击进入任意组件页面
2. IOS手机从屏幕左侧滑动后退
3. 后退执行并会重新执行一次后退动画，会有明显的闪烁

### What is expected?
希望动画跳转的时候不会出现该闪烁现象

### What is actually happening?
会闪烁

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.1

**Comment by ustbhuangyi** [comment]
这并不是源码的 bug，只是这种侧滑路由动画实现方式通用的问题，我觉得可以接受

**Comment by lyh2668** [comment]
是的大佬，但是我觉得这个问题很普遍，是否能有什么折中的策略能解决这个问题呢，感觉解决了这个问题能够使hybrid app有更接近原生的体验。

**Comment by OmegaTed** [comment]
vux中似乎没出现这个问题.不知大佬是否能去借鉴解决下
