### ISSUE TITLE
input type="Number" 时 maxlength 不起作用

### ISSUE THREAD

**Issue by szhbkw** [didi/cube-ui#108]
### Version
1.5.0

### Reproduction link
[https://github.com/didi/cube-ui/blob/dev/src/components/input/input.vue](https://github.com/didi/cube-ui/blob/dev/src/components/input/input.vue)

### Steps to reproduce
input type="Number" 时 maxlength 不起作用

### What is expected?
input type="Number" 时 maxlength 可以有效

### What is actually happening?
有需求

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.1

**Comment by szhbkw** [comment]
虽然原生就存在， 可以再组件内 解决吗

**Comment by dolymood** [comment]
这个是默认行为，我们推荐和原生保持一致。目前如果说你想要maxlength的效果的话，可以自己修改值也行。

很快未来我们会加入表单部分，类似的问题的话，可以通过表单校验达到目的
