### ISSUE TITLE
[New Feature] 如果做到类似IOS滴滴打车的push和pop效果？

### ISSUE THREAD

**Issue by alicksnake22** [didi/cube-ui#109]
### What problem does this feature solve?
ios里面切换页面应该是有vue路由切换和原生navigationcontroller切换混合。
vue路由切换方面，侧滑返回原理是怎样做的？不知道cube里面是否有提供？

### What does the proposed API look like?
cube是否有侧滑返回的功能？

**Comment by ustbhuangyi** [comment]
这个问题和 cube-ui 无关，可以去群里交流
