### ISSUE TITLE
picker兼容性问题

### ISSUE THREAD

**Issue by szhbkw** [didi/cube-ui#115]
### Version
1.5.0

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/picker](https://didi.github.io/cube-ui/#/zh-CN/docs/picker)

### Steps to reproduce
在火狐游览器打开 发现picker组件有个border 不显示

### What is expected?
让border 显示

### What is actually happening?
兼容性

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.4

**Comment by szhbkw** [comment]
补充下： 要切换到手机模式

**Comment by dolymood** [comment]
刚实验了下，是可以显示的，不知是不是版本问题或者缩放问题。

PS：我们是面向移动端的，兼容性问题理论上只考虑手机真机上
