### ISSUE TITLE
scorll  direction:"horizontal" is not take effect

### ISSUE THREAD

**Issue by hkchenyuan** [didi/cube-ui#117]
scorll  direction:"horizontal" is not take effect

**Comment by AmyFoxFN** [comment]
direction:"horizontal" 应该是正常。要能横向滚动，最主要得让cube-scroll-content元素的宽度大于cube-scroll-wrapper元素的宽度，这也是better-scroll的原理，只有内容区长度大于容器长度才能在那个方向上滚动。你可以确定一下，你的cube-scroll-content是不是比cube-scroll-wrapper宽
