### ISSUE TITLE
switch组件

### ISSUE THREAD

**Issue by szhbkw** [didi/cube-ui#118]
### Version
1.6.0

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/switch](https://didi.github.io/cube-ui/#/zh-CN/docs/switch)

### Steps to reproduce
关于switch组件 返回数据 只有 true，还是false 不够。 有时候有一组列表 还要返回其他信息 比如说该 item的id 等。

### What is expected?
可以返回 该item 的id 

### What is actually happening?
有需求

### Dependencies Version
vue: 2.5.15
better-scroll: 1.8.4

**Comment by dolymood** [comment]
一组的场景，直接过滤下就可以了吧 用computed或者直接在需要的地方过滤 都可以
