### ISSUE TITLE
华为P9 兼容性问题

### ISSUE THREAD

**Issue by HUANGYAQI** [didi/cube-ui#119]
在使用中发现了华为P9手机的兼容性问题，在手机原生浏览器中会出现样式的bug，在UC，微信等浏览器中不存在。
![image](https://user-images.githubusercontent.com/11711798/37321136-f85a807e-26b1-11e8-95ee-46fe3f906222.png)

**Comment by HUANGYAQI** [comment]
![image](https://user-images.githubusercontent.com/11711798/37321272-9dda8332-26b2-11e8-9fbc-413dc5ca6569.png)
以及华为荣耀

**Comment by ustbhuangyi** [comment]
请按 issue 规范提
