### ISSUE TITLE
关于布局

### ISSUE THREAD

**Issue by xiangsongtao** [didi/cube-ui#12]
这个不是issue, 我想问下cube-content不使用流式布局是因为什么, 目前使用的是固定宽高通过```overflow: scroll;```让内部滚动. 业务使用会不会有局限性啊?

**Comment by dolymood** [comment]
布局肯定是和需求相关的，而这里比较特殊，在PC上我们希望可以直接滚动查看效果，为了文档中演示。
而其实在移动端的话，如果在小屏手机上我们是做了 better-scroll 平滑滚动处理的，所以是有 top bottom 来撑高，这个是 better-scroll 依赖。

所以最终的话就是两个都有，这个在实际业务中并不会存在这种情况的。
