### ISSUE TITLE
安卓原生浏览器兼容性问题

### ISSUE THREAD

**Issue by HUANGYAQI** [didi/cube-ui#120]
Version
1.6.0

Reproduction link
http://goic.sf-express.com/user/riderregister/riderregisterh5

Steps to reproduce
使用华为P9，荣耀等机型，使用原生浏览器打开会出现样式问题甚至影响操作

What is expected?
正常显示，并能操作

What is actually happening?
由于input样式问题甚至遮挡按钮导致无法操作

Dependencies Version
vue: 2.5.15 better-scroll: 1.8.4

短信链接H5，点击以后会使用浏览器打开

**Comment by dolymood** [comment]
能提供下系统版本吗 ，华为 Mate9 EMUI 5.0.1 android7.0 原生浏览器没问题

**Comment by HUANGYAQI** [comment]
华为P9手机，型号EVA-AL00，系统版本EMUI系统4.1，安卓6.0  
出现以下问题
![image](https://user-images.githubusercontent.com/11711798/37340574-8cff93c6-26f9-11e8-9f29-3ba3bfdaeb65.png)

**Comment by dolymood** [comment]
你是用的后编译吧，我看了下你的线上代码，应该是因为 你的生成的 css transform 没有 -webkit- 前缀，所以你需要改下你项目 package.json 的 browserslist

```json
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8",
    "Android >= 4.0"
  ]
``` 

就是增加了 "Android >= 4.0" ，不过这也是问题，最新的 cube-template 也加入了这个

**Comment by HUANGYAQI** [comment]
![image](https://user-images.githubusercontent.com/11711798/37389875-eed9e626-27a0-11e8-9297-ed2aee3111b4.png)
我的package.json里面应该是有自动加前缀的。
![image](https://user-images.githubusercontent.com/11711798/37389904-071801be-27a1-11e8-9428-fa0703c962a2.png)
编译出来的CSS文件里也是可以看到-webkit-。
唯独browserslist少"Android >= 4.0"，待会我加了再试试
![image](https://user-images.githubusercontent.com/11711798/37389942-24e947de-27a1-11e8-9586-7b37e3fff052.png)

**Comment by HUANGYAQI** [comment]
问题解决啦~ 加了 "Android >= 4.0" 有更多属性会被加上-webkit-
