### ISSUE TITLE
[New Feature] 组件太少了

### ISSUE THREAD

**Issue by lizhuangs** [didi/cube-ui#122]
### What problem does this feature solve?
比如常见的tab选项卡，省市级联等。请问这个有road map？

### What does the proposed API look like?
更丰富，可以有类似ANT DESIGN PRO的脚手架演示～

**Comment by dolymood** [comment]
tab 选项卡没计划做的，省市级联的话我们有示例的，使用 https://didi.github.io/cube-ui/#/zh-CN/docs/cascade-picker 很容易实现各种级联的组件

演示（实战）项目演示的话，我们正在弄，目前基本完成了，https://github.com/cube-ui/cube-application-guide

像 PRO 式的更详细的演示的话 目前还没有，后续可以考虑

**Comment by ustbhuangyi** [comment]
关联这个 issue #11
