### ISSUE TITLE
调用弹框

### ISSUE THREAD

**Issue by qixiaomeng** [didi/cube-ui#123]
### Version
1.6.0

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/toast](https://didi.github.io/cube-ui/#/zh-CN/docs/toast)

### Steps to reproduce
在main,js里面无法调用弹出框等, Vue.$createToast   还是this.$createToast都不行

### What is expected?
可以在main.js里面使用弹出框

### What is actually happening?
不知道

### Dependencies Version
vue: 2.5.16
better-scroll: 1.8.4

**Comment by AmyFoxFN** [comment]
在普通 JS 文件中 API 调用，this不是vue实例，不能用this调用，请参考文档 https://didi.github.io/cube-ui/#/zh-CN/docs/create-api 里的说明

**Comment by dolymood** [comment]
目前的话 你可以使用 Vue.prototype.$createToast 来做

下个版本我们会给 Toast 本身增加一个 API $create 可以直接创建

**Comment by alicksnake22** [comment]
Vue.prototype.$createToast创建也失败

**Comment by dolymood** [comment]
你 use 了吗 需要use 才能使用的

**Comment by alextzh** [comment]
const vm = new Vue()
vm.$createToast这样子可以

**Comment by qixiaomeng** [comment]
谢谢解答
