### ISSUE TITLE
[New Feature] 是否可以结合mpvue，开发微信小程序

### ISSUE THREAD

**Issue by tuhe32** [didi/cube-ui#126]
### What problem does this feature solve?
您好，cube-ui是否可以结合mpvue开发微信小程序，或者需要如何二次开发来通过mpvue开发微信小程序

### What does the proposed API look like?
结合mpvue，开发微信小程序

**Comment by AmyFoxFN** [comment]
不好意思，小程序我们暂时还不会考虑
