### ISSUE TITLE
scroll嵌套，click事件触有bug

### ISSUE THREAD

**Issue by php4world** [didi/cube-ui#127]
### Version
1.6.0

### Steps to reproduce
外层scroll作为页面滚动，内层多个scroll横排滚动，内层scroll内有click事件。使用@click.stop.prevent后，触发两次，外层的@click.capture.stop.prevent则正常，触发一次。

### What is expected?
正常触发一次

### What is actually happening?
内层会触发两次

### Dependencies Version
vue: 2.5.16
better-scroll: 1.8.4

**Comment by dolymood** [comment]
如果是双层 scroll 嵌套的话，里层的scroll的 click要配置为 false
