### ISSUE TITLE
苹果手机使用safari浏览器访问浏览自带底部导航永远显示在底部

### ISSUE THREAD

**Issue by ChasonHong** [didi/cube-ui#134]
### Version
1.6.1

### Reproduction link
[https://didi.github.io/cube-ui/example/#/](https://didi.github.io/cube-ui/example/#/)

### Steps to reproduce
苹果手机使用safari浏览器访问浏览自带底部导航永远显示在底部

### What is expected?
无

### What is actually happening?
无

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

**Comment by SHERlocked93** [comment]
这个问题后来怎么解决了，底部一直有toolbar，遮挡了网页内容，meta标签 `<meta name="apple-touch-fullscreen" content="yes">` 与 `<meta name="apple-mobile-web-app-capable" content="yes">` 也不管用
