### ISSUE TITLE
[New Feature] 建议开发tab组件

### ISSUE THREAD

**Issue by php4world** [didi/cube-ui#137]
### What problem does this feature solve?
更好的用户体验
![图片](https://s1.ax1x.com/2018/03/27/9OU3Eq.jpg)

### What does the proposed API look like?
无

**Comment by dolymood** [comment]
所有的需求都提在这个 issue 下 https://github.com/didi/cube-ui/issues/11

**Comment by psychokiller666** [comment]
希望添加tab组件
