### ISSUE TITLE
scroll组件添加下拉属性时使用在服务端渲染报错：window is not define

### ISSUE THREAD

**Issue by winsan-zhang** [didi/cube-ui#141]
### Version
1.6.1

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/scroll](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll)

### Steps to reproduce
正常使用如果不添加scroll的options下拉属性无问题，如果添加该属性则报错：windown is not define，服务端渲染时应该是没有window对象的，是否该组件不能够使用在服务端渲染呢？

### What is expected?
无

### What is actually happening?
无

### Dependencies Version
vue: 2.5.16
better-scroll: 1.8.4

**Comment by dolymood** [comment]
需要更具体的一些报错信息
