### ISSUE TITLE
datepicker 数据格式返回改进

### ISSUE THREAD

**Issue by qinzitong** [didi/cube-ui#144]
### Version
1.6.1

### Reproduction link
[]()

### Steps to reproduce
date-picker 在返回的数据希望能够format 一下，比如[2017-8-8]这样的格式希望返回[2017-08-08]的形式，因为类似于[2017-8-8]这样格式的数据在new date的时候 Safari 以及ios下的设备 都会是invalid date的返回

### What is expected?
 select(selectedVal, selectedIndex, selectedText) {
        var formatDate = selectedVal[0]   '-'  
          (selectedVal[1] < 10 ? '0'   selectedVal[1] : selectedVal[1])   '-'  
          (selectedVal[2] < 10 ? '0'   selectedVal[2] : selectedVal[2])
        this.$emit(EVENT_SELECT, formatDate, selectedIndex, selectedText)
      },

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

---
希望返回的代码是这样的 
select(selectedVal, selectedIndex, selectedText) {
        var formatDate = selectedVal[0]   '-'  
          (selectedVal[1] < 10 ? '0'   selectedVal[1] : selectedVal[1])   '-'  
          (selectedVal[2] < 10 ? '0'   selectedVal[2] : selectedVal[2])
        this.$emit(EVENT_SELECT, formatDate, selectedIndex, selectedText)
      },

**Comment by AmyFoxFN** [comment]
之前的 date-picker 只是示例，不是官方组件，1.7.0版本会发官方DatePicker，将会返回 Date数据类型，你可以在 #145 提前看下效果
