### ISSUE TITLE
Radio组件不能传name属性，导致不能通过表单提交。也没有方法获取被选中radio的值

### ISSUE THREAD

**Issue by blogwy** [didi/cube-ui#147]
### Version
1.6.1

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/radio](https://didi.github.io/cube-ui/#/zh-CN/docs/radio)

### Steps to reproduce
Radio组件不能传name属性，导致不能通过表单提交。也没有方法获取被选中radio的值

### What is expected?
Radio组件不能传name属性，导致不能通过表单提交。也没有方法获取被选中radio的值

### What is actually happening?
Radio组件不能传name属性，导致不能通过表单提交。也没有方法获取被选中radio的值

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

---
Radio组件不能传name属性，导致不能通过表单提交。也没有方法获取被选中radio的值

**Comment by dolymood** [comment]
v-model 不是可以获取到值吗？你是原生 form 直接提交的方式？
