### ISSUE TITLE
Toast mask animation is not smooth

### ISSUE THREAD

**Issue by xinkule** [didi/cube-ui#15]
### A feature or reporting a bug?
feature

### What is the current behavior?
The mask animation in the Toast component is not smooth, feeling an apparently lag when changing opacity.

### What is the expected behavior?
The fade in animation will be smoother.

- vue version: 2.5.3
- cube-ui version: 1.0.0

**Comment by dolymood** [comment]
Nice! Thanks. The animation should be more smoother. It will be released in the next version.
