### ISSUE TITLE
ios下 datetimepicker 确定取消按钮点击无效

### ISSUE THREAD

**Issue by artiely** [didi/cube-ui#152]
### Version
1.7.2

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker](https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker)

### Steps to reproduce
系统  ios11.03 11.2 升级为11.3后依然无法点击 ，其他版本是否存在类似问题未知，安卓机正常

### What is expected?
确认和取消按钮可点击

### What is actually happening?
确认和取消按钮不能点击

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

---
系统  ios11.03 11.2 升级为11.3后依然无法点击 ，其他版本是否存在类似问题未知，安卓机正常

**Comment by dolymood** [comment]
11.3 验证有效啊，能给出复现步骤吗
