### ISSUE TITLE
input组件eye位置怎么控制

### ISSUE THREAD

**Issue by binperson** [didi/cube-ui#153]
### Version
1.7.2

### Reproduction link
[https://codesandbox.io/s/5z3ojy5wlp?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue](https://codesandbox.io/s/5z3ojy5wlp?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
如此demo是看不见的，在本地工程中，eye图标太偏右了

### What is expected?
可以控制eye图标的位置

### What is actually happening?
eye图标位置可控

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

**Comment by dolymood** [comment]
eye是紧靠右边的，如果你想有一定间距，可以css调整 margi-right 就可以了吧

**Comment by binperson** [comment]
这个需要改源代码吧？在组件外层是改不了，覆盖不了

**Comment by binperson** [comment]
在main.js引用的styl可以覆盖～～
