### ISSUE TITLE
[New Feature] vue-scroll 下拉到最后时当数据发生变化 加载更多的no more data 不消失

### ISSUE THREAD

**Issue by artiely** [didi/cube-ui#159]
### What problem does this feature solve?
上拉加载到最后 时出现no more data 然后下拉刷新后 上拉时还是no more data 而不是load more 或者切换和其他方式改变了数据 no more data 提示文字一直存在

### What does the proposed API look like?
当数据请求到最后出现no more data 然后数据改变 不足一屏时 不用显示no more data 提示 ；够一屏时应该显示加载更多而不是 no more data

**Comment by AmyFoxFN** [comment]
感谢反馈，这样确实有一些问题，我们下个版本会加一个方法来重置上拉加载的状态，这样可以根据具体的情况自己选择什么时候重置成“加载更多”

**Comment by 136985627** [comment]
这个问题还没有解决吗？

**Comment by AmyFoxFN** [comment]
已添加 resetPullUpTxt 方法，下个版本发布 #162
