### ISSUE TITLE
styl是什么类型的文件，需要什么样的loader？

### ISSUE THREAD

**Issue by laurensmartz** [didi/cube-ui#16]
<img width="639" alt="wechat image_20171112225445" src="https://user-images.githubusercontent.com/19658995/32700181-85f2adf4-c7fc-11e7-86ac-c10f3ce69b64.png">

**Comment by dolymood** [comment]
styl 是 Stylus 的文件，需要依赖 stylus & stylus-loader

**Comment by dolymood** [comment]
这个可以参考 https://didi.github.io/cube-ui/#/zh-CN/docs/quick-start 最后边关于 “使用后编译” 部分

**Comment by laurensmartz** [comment]
谢谢
