### ISSUE TITLE
common/helpers/util 的 deepAssign 是浅拷贝

### ISSUE THREAD

**Issue by hooraygith** [didi/cube-ui#160]
### Version
1.7.3

### Reproduction link
[https://jsfiddle.net/xqw28nav/2/](https://jsfiddle.net/xqw28nav/2/)

### Steps to reproduce
看源码就知道

### What is expected?
名字叫 deepAssign 的话，应该是深拷贝

### What is actually happening?
deepAssign 为浅拷贝

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

**Comment by AmyFoxFN** [comment]
这是一个尾递归的深度assign。assign跟拷贝是不一样的，而且你的测试用例并没有测到深度assign
