### ISSUE TITLE
DatePicker 组件 在支付宝浏览器中 uc 浏览器无法使用

### ISSUE THREAD

**Issue by windsBro** [didi/cube-ui#163]
### Version
1.7.3

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker](https://didi.github.io/cube-ui/#/zh-CN/docs/date-picker)

### Steps to reproduce
* 安卓手机 支付宝扫描官网demo 进入网址 选择datepicker 组件，不显示

### What is expected?
正常显示组件

### What is actually happening?
不显示，反应慢

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.9.0

**Comment by dolymood** [comment]
多谢反馈
