### ISSUE TITLE
[New Feature] 请给有遮罩的组件的body添加overflow:hidden

### ISSUE THREAD

**Issue by qinzitong** [didi/cube-ui#164]
### What problem does this feature solve?
popup、picker等组件在弹出以后，遮罩层底下的内容区域依然可以滚动。建议在组件弹出时，给body 添加overflow:hidden 的属性，关闭时移除。

**Comment by dolymood** [comment]
这个其实在移动端并不是总有效的吧

**Comment by xinkule** [comment]
移动端要阻止touchmove事件了

**Comment by fengjunoo** [comment]
目前来看iOS设备下是有效的

**Comment by dolymood** [comment]
下个版本我们给 popup 增加 touchmove 阻止来解决这个问题

**Comment by dolymood** [comment]
1.10.11 解决了

**Comment by dolymood** [comment]
如果有此需求 给里层元素 加上 toucmove stop 阻止冒泡就可以了
