### ISSUE TITLE
[New Feature] 如何使用不同大小的图标适应不同的分辨率？

### ISSUE THREAD

**Issue by snowdream** [didi/cube-ui#166]
### What problem does this feature solve?
如何使用不同大小的图标适应不同的分辨率？

### What does the proposed API look like?
如何使用不同大小的图标适应不同的分辨率？

**Comment by dolymood** [comment]
iconfont 的大小问题吗

**Comment by snowdream** [comment]
以android为例，图标怎么对应hdpi，xhdpi，xxhdpi。。

**Comment by ustbhuangyi** [comment]
可以去群里讨论问题
