### ISSUE TITLE
用createAPI调用的自定义组件，在组件里面，使用vuex的mapState、mapActions报错

### ISSUE THREAD

**Issue by xhtea** [didi/cube-ui#167]
### Version
1.8.0

### Reproduction link
[https://codesandbox.io/s/nrp113w200](https://codesandbox.io/s/nrp113w200)

### Steps to reproduce
在页面上的uid是从vuex里面读取出来的。
点击示例中的展示hello按钮，就报错，不能展开自定义组件（自定义组件里也有读取vuex的内容就报错，去掉就正常）；请问有什么解决办法

### What is expected?
期望结果是展开createAPI创建的组件，且组件能读取到vuex的state值，并操作改变vuex的值 

### What is actually happening?
引入vuex的state值就报错 

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.10.0

**Comment by dolymood** [comment]
1.8.1 可用
