### ISSUE TITLE
Scroll组件下拉在快要刷新完成时，迅速上滑，整个组件会滑出屏幕导致空白

### ISSUE THREAD

**Issue by iceuncle** [didi/cube-ui#176]
### Version
1.8.1

### Reproduction link
[https://github.com/iceuncle/scroll-test](https://github.com/iceuncle/scroll-test)

### Steps to reproduce
1. 下拉刷新
2. 在快要刷新完成时迅速上滑

### What is expected?
上滑能滑到列表底部并正常回弹

### What is actually happening?
上滑后，整个列表从顶部滑出了屏幕

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.10.0

**Comment by AmyFoxFN** [comment]
谢谢反馈，这个问题 better-scroll 正在修复，等那边发版，我们也会升级修复

**Comment by AmyFoxFN** [comment]
1.9.0+版本依赖的BScroll@1.11.1里已经基本修复这个问题，可能仅剩极小概率出现的浏览器渲染bug，这部分暂时是很难从前端代码处理的，后续可以关注一下

**Comment by iceuncle** [comment]
刚刚测试了一下，还是有这个问题。只要在刷新完成 进行向上回弹的动画时，迅速上滑就会出现这个现象。

**Comment by ceeyang** [comment]
同样遇到该问题

**Comment by ceeyang** [comment]
I had run 'npm update' and update the 'cube-ui' to 1.10.0, it's ok
