### ISSUE TITLE
Scroll组件进行连续多次的下拉刷新动作，刷新完成的回弹动画会产生异常

### ISSUE THREAD

**Issue by iceuncle** [didi/cube-ui#177]
### Version
1.8.1

### Reproduction link
[https://github.com/iceuncle/scroll-test](https://github.com/iceuncle/scroll-test)

### Steps to reproduce
进行连续多次连续下拉刷新动作

### What is expected?
连续多次下拉刷新能够正常进行刷新完成的回弹动画

### What is actually happening?
连续多次下拉刷新，出现刷新完成动画消失的异常

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.10.0

**Comment by AmyFoxFN** [comment]
已经定位到问题了，是 scroll 组件里有个重置下拉刷新样式的计时器在忘记在下一次触发时清掉了。明天发版修复啊，谢谢反馈😊

**Comment by AmyFoxFN** [comment]
1.8.3版本已修复
