### ISSUE TITLE
input组件eye控制密码是否可见

### ISSUE THREAD

**Issue by TragueZw** [didi/cube-ui#178]
### Version
1.8.1

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/input](https://didi.github.io/cube-ui/#/zh-CN/docs/input)

### Steps to reproduce
官网案例

### What is expected?
眼睛打开密码显示， 眼睛关闭密码加密

### What is actually happening?
和期待相反

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.10.0

**Comment by dolymood** [comment]
多谢反馈。
这种有两种解释，一种代表状态，一种代表行为，现在我们默认的是代表行为的操作，我们加一个代表控制状态的 prop 来控制行为。

**Comment by AmyFoxFN** [comment]
1.8.3版本已支持，欢迎升级使用~

**Comment by TragueZw** [comment]
感谢回复

**Comment by danielmlc** [comment]
虽然已经更新 不知道该怎么用，文档没有更新吧
