### ISSUE TITLE
使用Form时，model有多级嵌套，modelKey绑定不了值

### ISSUE THREAD

**Issue by zhou0818** [didi/cube-ui#187]
**Version**
1.8.1

**Steps to reproduce**
model为多级嵌套的集合
 model:{
        a:{
          b:123
        }
      }

**What is expected?**
modelKey 使用 'a.b' 的形式绑定不了

**What is actually happening?**
modelKey 绑定不了

**Dependencies Version**
vue: 2.5.2

**Comment by zhou0818** [comment]
@dolymood 还有个问题，form默认配置使用下，例如 input 的 props 怎么绑定到一个变量上去，比如 
props: {
                  placeholder: '请输入',
                  disabled: true
                },
这个 disabled 只能一开始赋值一个 true 或 false？
改变的话需要循环去改数据了

**Comment by dolymood** [comment]
如果是改变的话，建议可以考虑用computed
