### ISSUE TITLE
关于cube-scroll组件在IOS 10.3.2版本中不能滚动

### ISSUE THREAD

**Issue by weixinfei123** [didi/cube-ui#191]
### Version
1.8.3

### Steps to reproduce
最近公司的项目中用到cube-ui, 在scroll组件中发现在IOS 10.3.2版本中不能滚动（通过后端接口返回数据渲染页面），但是在IOS11和安卓上都是可以的，  后来我写个静态页面在组件中也是不能滚动（在IOS 10.3.2版本中），其他的没有问题，也试过this.$refs.scroll.scroll.refresh()也不行， 暂时还没找到原因，大佬可以帮忙看一下吗？ scroll通过设置 observeDOM: true，可以在demo的【首页】【我的】查看效果

### What is expected?
在IOS 10可以正常滚动

### What is actually happening?
scroll组件在IOS 10.3.2版本中不能滚动

### Dependencies Version
vue: 2.5.2
better-scroll: 1.10.3

**Comment by weixinfei123** [comment]
上面问题这个dome可能更清晰一些： https://weixinfei123.github.io/dist101/index.html   

现在主要是在IOS 10.3.2上有问题，QQ浏览器，UC浏览器，以及微信里都不能滚动

在IOS 11和安卓上都没有问题，不知道是不是我使用的问题

**Comment by dolymood** [comment]
目测因为 height 100% 虽然flex 1了，但是你还是需要处理下，注意height 100% 的条件

**Comment by dolymood** [comment]
可参考 https://github.com/didi/cube-ui/pull/184

**Comment by weixinfei123** [comment]
恩，确实是height问题，动态设置一下就可以了，或者是不采用flex布局也是可以的，谢谢。
