### ISSUE TITLE
dateTimePicker第一次创建延迟很严重

### ISSUE THREAD

**Issue by TragueZw** [didi/cube-ui#197]
### Version
1.9.1

### Reproduction link
[https://didi.github.io/cube-ui/example/#/date-picker](https://didi.github.io/cube-ui/example/#/date-picker)

### Steps to reproduce
dateTimePicker第一次创建延迟很严重， 几秒钟以上，具体效果官网demo可以看到

### What is expected?
延迟减小

### What is actually happening?
延迟严重

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.11.1

**Comment by AmyFoxFN** [comment]
确实有这个问题，是第一次生成级联数据的时候花的时间太长了，我们后续会想办法优化一下啊
