### ISSUE TITLE
[New Feature] CascadePicker组件，不支持传入value显示对应的text

### ISSUE THREAD

**Issue by fenglingcao** [didi/cube-ui#209]
### What problem does this feature solve?
CascadePicker组件中
1、希望能增加value参数
2、希望能在alias中能定义children的别名

### What does the proposed API look like?
无

**Comment by AmyFoxFN** [comment]
不支持传入value显示对应的text是指？没太理解你想要的功能

**Comment by fenglingcao** [comment]
你参考 datepicker 有个value属性，而CascadePicker没有，只有个索引（selectedIndex）来显示对应的值，后端数据库只会存value值而不会存索引值吧。

**Comment by dolymood** [comment]
这个暂时不考虑，2.x 考虑统一
