### ISSUE TITLE
添加全局的box-sizing:border-box导致样式错乱

### ISSUE THREAD

**Issue by TragueZw** [didi/cube-ui#216]
### Version
1.9.3

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/introduction](https://didi.github.io/cube-ui/#/zh-CN/docs/introduction)

### Steps to reproduce
全局配置重置样式 * {box-sizing: border-box;}， 导致样式错乱

### What is expected?
组件中使用padding和width、height的元素添加content-box

### What is actually happening?
样式错乱
![image](https://user-images.githubusercontent.com/24466492/40693616-ea6bde74-63ea-11e8-902f-46f626e787d5.png)

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.11.1

**Comment by dolymood** [comment]
下个版本修复
