### ISSUE TITLE
[New Feature] Support ScrollTab

### ISSUE THREAD

**Issue by dolymood** [didi/cube-ui#218]
### What problem does this feature solve?
Tab Scroll

### What does the proposed API look like?
```html
<scroll-tab ... />
```

**Comment by dolymood** [comment]
see https://github.com/didi/cube-ui/blob/dev/example/pages/tab-bar/scroll-tab.vue

**Comment by Hxiaotong** [comment]
不好用呢，可以直接封装成一个组件，使用么，现在好像是需要去看你写的代码，样式什么的容易乱，感觉不好用。
