### ISSUE TITLE
【建议Scoller组件参数修改】建议Socller组件中，对于bscoller的参数统一一个bsOption来配置bscoller插件的配置，增强组件配置的灵活型。

### ISSUE THREAD

**Issue by huangzhenxian** [didi/cube-ui#22]
【当前问题】bscoller有许多配置可用，当前配置被拆分开来一个一个填使得组件十分不灵活，一大部分不能配置例如bounce等。就算把bscoller参数全部配上去，在使用组件的时候需要配置一大堆属性。
【建议修改】建议把bscoller插件的配置统一到bsOption，文档指引到bscoller的配置文档，这样组件使用会不会更方便呢？

**Comment by ustbhuangyi** [comment]
@huangzhenxian , Scroll 只是 better-scroll 的在滚动能力方面做的一层封装，它并不能完全代替。better-scroll 的很多参数并不适用与 Scroll 组件，如果粗暴的添加这个 bsOption 会让使用者更加困惑。
我的想法还是梳理好这个 Scroll 组件本身的一些能力，如果需要新增哪些 feature，可以具体提出来，如果是合理的需求我们再往上加，这样的方式会更好。

**Comment by huangzhenxian** [comment]
@ustbhuangyi 我个人觉得，直接用对象传配置它并不暴力，站着使用者的角度，我觉得理解bsOption 并不困难，如果组件封装出来，被阉割导致太多不适应，我个人觉得许多人都会根据源码重新写一个基于better-scroll的组件出来，至少我现在已经是这样做了【我试过不适应的地方用原生的better-scroll插件来做，但是太多了，代码冗余多，所以我还是自己改了cube的scroll组件】。还有我觉得 按单个属性那个拆分来填入 导致标签属性臃肿，可读程度降低 。其实我一个页面可能有3个scroll组件 然后我相同的标签属性要配置3次 我觉得 还是蛋疼

**Comment by yoyo837** [comment]
@huangzhenxian 我支持@ustbhuangyi 的看法，在你使用cube-ui时，不管cube-ui内置了别的哪个组件的依赖，你应该将其看作cube-ui一个整体，cube-ui提供的任何功能都是cube-ui的，cube-ui加一层控制其内部依赖的其他组件是合理的，如果把内部依赖组件的所有配置都开放出来，可能会引起cube-ui的组件在搭配此内部依赖组件事造成问题，除非cube-ui兼容内部依赖组件的所有配置，否则没必要全部开放。且内部依赖的组件在设计时考虑不到谁会怎样使用它...

**Comment by ustbhuangyi** [comment]
那这个问题就变成了需要支持一个对象对一些属性再包装一层的问题了，但这个对象也不应该直接复用 better-scroll 的配置项，而应该是它的一个子集，我们会梳理哪些必要的属性是要添加到对象中，减少一些代码书写的复杂。

**Comment by yoyo837** [comment]
@ustbhuangyi 配置项较多的话理应使用一个对象，这个对象处理下，不直接丢给better-scroll就可以了，甚至可以叫不同的参数名，但作用一致的话尽量同名较好，避免使用时造成误导。

**Comment by ustbhuangyi** [comment]
@yoyo837 ，目前考虑会设计一个 Object 类型的 Props，然后把这个对象直接扩展传给 better-scroll，所以理论上它就是一个 better-scroll 的一个 Option，但是从文档层面我打算还是只写一些推荐修改的属性。而其它属性的话只是隐式支持，不在文档中体现，还是尽量减少用户的理解成本以及可能会带来的一些副作用。

**Comment by yoyo837** [comment]
@ustbhuangyi 我保留个人意见，
> 除非cube-ui兼容内部依赖组件的所有配置，否则没必要全部开放

**Comment by ustbhuangyi** [comment]
@yoyo837 不会开放，但保留能力，文档层面我们只提供推荐的配置。

**Comment by dolymood** [comment]
已支持，将会在 1.1.0 版本中支持，参数为 options
