### ISSUE TITLE
[New Feature] Swipe组件侧滑点击按钮是否能够传递自定义参数

### ISSUE THREAD

**Issue by GodStream** [didi/cube-ui#222]
### What problem does this feature solve?
目前btn-click事件回调只返回了按钮参数，列表索引。但是在实际需求中，是想要知道当前项的id值，并且还会想要传递跟多的参数进行判断，这样才能知道到底触发事件的是哪一项，仅仅只靠索引是不行的。

### What does the proposed API look like?
<cube-swipe-item @btn-click="onBtnClick(item)">

**Comment by dolymood** [comment]
有了索引index就可以取到item选项了吧

**Comment by GodStream** [comment]
如果同时存在多个列表分组，只有索引就无法确定item了

**Comment by dolymood** [comment]
我们考虑多加一个参数 ，多谢反馈

**Comment by dolymood** [comment]
1.9.7 已经加了第三个参数 item，文档还没同步。

sorry这么晚回复。

**Comment by lhongtao** [comment]
第三个参数怎么使用，能给个例子么
