### ISSUE TITLE
textarea输入emoji表情可以超过maxlength限制

### ISSUE THREAD

**Issue by GuoQichen** [didi/cube-ui#223]
### Version
1.9.5

### Reproduction link
[https://didi.github.io/cube-ui/example/#/textarea](https://didi.github.io/cube-ui/example/#/textarea)

### Steps to reproduce
在手机打开，输入emoji表情，例如maxlength的长度为5，可以输入5个emoji表情，但是length为10，remain显示为-5
![textareabugreproduce](https://user-images.githubusercontent.com/17843661/40903338-9c9aa090-6809-11e8-9a2a-31ba4ee65ed8.PNG)

### What is expected?
输入emoji表情不超过maxlength限制

### What is actually happening?
输入emoji表情超过限制显示负数

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.11.1

**Comment by dolymood** [comment]
这个是个很复杂的问题 https://blog.jonnew.com/posts/poo-dot-length-equals-two lodash 内有解发

但是，浏览器原生行为也是计算的有问题，例如最大长度我们使用的是 maxlength 来控制，实际发现输入五个表情后也不行继续输入了，也就意味着长度达到目标了

**Comment by GuoQichen** [comment]
其实textarea的maxlength把一个emoji表情的长度算作1的方式对用户的理解来说是没问题的。能否把indicator的最小值限制在0

**Comment by dolymood** [comment]
1.10 增加了对 indicator 的配置，可以满足你的 最小值 的需求。但是 emoji的话，目前的话，只能还按照原生的来
