### ISSUE TITLE
文档挂了快两天了

### ISSUE THREAD

**Issue by GodStream** [didi/cube-ui#228]
### Version
1.9.7

### Reproduction link
[https://didi.github.io/cube-ui/](https://didi.github.io/cube-ui/)

### Steps to reproduce
文档消失很久了。。。没有人发现吗
![image](https://user-images.githubusercontent.com/23089466/41188912-80c7f596-6bf8-11e8-9b3d-2dbd25e48790.png)

### What is expected?
恢复文档

### What is actually happening?
404

**Comment by GodStream** [comment]
还有这种操作？？safari 确实可以

**Comment by ustbhuangyi** [comment]
我这 chrome 也没问题呀

**Comment by GodStream** [comment]
macOS 10.13.5, Chrome 67.0.3396.79

**Comment by dolymood** [comment]
这是因为之前有对 didi.github.io 做了 cname 映射，虽然很快下掉了，但是还是会有缓存问题
