### ISSUE TITLE
drawer及scroll的体验问题

### ISSUE THREAD

**Issue by artiely** [didi/cube-ui#229]
### Version
1.9.7

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/drawer](https://didi.github.io/cube-ui/#/zh-CN/docs/drawer)

### Steps to reproduce
scroll组件在快速或多次下拉的情况下， 一定概率出现刷新的那个水滴svg不消失
1. drawer组件可下拉刷新，但文档没暴露pullDown方法。下拉后一直loading
2. scroll组件和drawer组件在下拉后 一定概率出现刷新的那个水滴svg不消失

环境iOS  Android 下微信浏览器和UC浏览器均可重现。

### What is expected?
1.drawer组件无下拉loading
2. 优化svg不消失问题

### What is actually happening?
1. drawer组件可下拉刷新，但文档没暴露方法。下拉后一直loading
2. scroll组件和drawer组件在下拉后 一定概率出现刷新的那个水滴svg不消失

环境iOS  Android 下微信浏览器和UC浏览器均可重现。

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by dolymood** [comment]
多谢反馈。

sorry 这个我们的文档没来得及更新，其实是因为 1.9.6 的版本的scroll的一个bug，所以我们unpublish 了 发布了 1.9.7 .

已经更新。
