### ISSUE TITLE
通过v-show控制的两个cube-scroll只有一个滚动

### ISSUE THREAD

**Issue by u14e** [didi/cube-ui#232]
### Version
1.9.8

### Reproduction link
[https://codesandbox.io/s/x90392r2xp](https://codesandbox.io/s/x90392r2xp)

### Steps to reproduce
点击下面的tab，通过v-show切换两个cube-scroll的显示；
只有第一个cube-scroll滚动，第二个无效；
（codesandbox上面都无效）

### What is expected?
两个cube-scroll都滚动

### What is actually happening?
两个cube-scroll只有第一个滚动

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by dolymood** [comment]
v-show 控制是因为，scroll 依赖外层高度，当你改变的需要 refresh 重新计算高度才可以，display none 元素获取高度 肯定是0了
