### ISSUE TITLE
ActionSheet取消按钮文字如何自定义

### ISSUE THREAD

**Issue by liubin595338764** [didi/cube-ui#234]
### Version
1.9.8

### Reproduction link
[http://none](http://none)

### Steps to reproduce
ActionSheet取消按钮文字如何自定义

### What is expected?
ActionSheet取消按钮文字如何自定义

### What is actually happening?
ActionSheet取消按钮文字如何自定义

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by dolymood** [comment]
下个版本我们新增一个 prop 配置项

**Comment by dolymood** [comment]
1.9.9 支持配置 cancelTxt
