### ISSUE TITLE
[New Feature] Dialog加入z-index属性

### ISSUE THREAD

**Issue by gaozhe3321** [didi/cube-ui#236]
### What problem does this feature solve?
为了可以和其他UI框架兼容性更好，希望可以给弹出层组件加入z-index属性，比如Dialog

### What does the proposed API look like?
this.$createDialog({
    type: 'alert',
    title: 'title',
    content: 'something wrong',
    icon: 'cubeic-alert',
    zindex: 999 // 加入此属性确定这个弹出层可以在最上面显示
}).show()

**Comment by dolymood** [comment]
这种问题，可以考虑使用CSS来做，没必要支持传入 prop 的。
