### ISSUE TITLE
能不能给Toast添加一个自定义class的配置

### ISSUE THREAD

**Issue by liubin595338764** [didi/cube-ui#240]
### Version
1.9.9

### Reproduction link
[http://none](http://none)

### Steps to reproduce
能不能给Toast添加一个自定义class的配置，这样子可以自己控制图标的位置，或者不要图标，或者使用其他的图标

### What is expected?
能不能给Toast添加一个自定义class的配置，这样子可以自己控制图标的位置，或者不要图标，或者使用其他的图标

### What is actually happening?
能不能给Toast添加一个自定义class的配置，这样子可以自己控制图标的位置，或者不要图标，或者使用其他的图标

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by dolymood** [comment]
1.10 可以通过类似做法来搞：

```js
this.$createToast({
  $class: {
    'own-class': true
  }
})
```

**Comment by 452MJ** [comment]
@dolymood 有具体的demo吗
