### ISSUE TITLE
v.1.10.0 not work well

### ISSUE THREAD

**Issue by dongqizhen** [didi/cube-ui#243]
Module parse failed: Unexpected token (10:4)
You may need an appropriate loader to handle this file type.
|
|   const instance = new Vue({
|     ...options,
|     render(createElement) {
|       let children = childrenRenderFn && childrenRenderFn(createElement)

 @ ./node_modules/_cube-ui@1.10.0@cube-ui/src/common/helpers/create-api-component.js 1:0-58
 @ ./node_modules/_cube-ui@1.10.0@cube-ui/src/common/helpers/create-api.js
 @ ./node_modules/_cube-ui@1.10.0@cube-ui/src/modules/image-preview/api.js
 @ ./node_modules/_cube-ui@1.10.0@cube-ui/src/modules/image-preview/index.js
 @ ./src/main.js
 @ multi ./node_modules/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by dolymood** [comment]
参考 https://didi.github.io/cube-ui/#/zh-CN/docs/quick-start#cube-%E5%AE%89%E8%A3%85-anchor

**Comment by dongqizhen** [comment]
v.1.9.9 No such error ，it work well
