### ISSUE TITLE
自定义DatePicker列的排序

### ISSUE THREAD

**Issue by liubin595338764** [didi/cube-ui#244]
### Version
1.10.0

### Reproduction link
[http://none](http://none)

### Steps to reproduce
希望能自定义DatePicker弹窗里面列的排序，现在是固定的从左到右是年月日，希望可以自定义月日年或者日月年。

### What is expected?
希望能自定义DatePicker弹窗里面列的排序，现在是固定的从左到右是年月日，希望可以自定义月日年或者日月年。

### What is actually happening?
希望能自定义DatePicker弹窗里面列的排序，现在是固定的从左到右是年月日，希望可以自定义月日年或者日月年。

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by dolymood** [comment]
这种需求太少见了，建议自己实现。
