### ISSUE TITLE
Slide cube-slide-item 自定义内容 纵向横向可以同时滑动

### ISSUE THREAD

**Issue by dustdu** [didi/cube-ui#246]
### Version
1.10.2

### Reproduction link
[https://didi.github.io/cube-ui/example/#/tab-bar/tab/composite](https://didi.github.io/cube-ui/example/#/tab-bar/tab/composite)

### Steps to reproduce
斜着划出现bug

### What is expected?
在纵向、横向方向都有滑动动作时，只有一个方向的滑动

### What is actually happening?
纵向横向都存在滑动

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

---
使用 Slide cube-slide-item 实现列表切换时遇到的问题

**Comment by theniceangel** [comment]
@dustdu 如果需要锁住一个方向，需要给slide和scroll配置 directionlockthreshold 参数，详细请看[better-scroll文档](https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#directionlockthreshold)

**Comment by TJ-github-del** [comment]
斜着划出现bug解决了？

**Comment by TJ-github-del** [comment]
@dolymood
