### ISSUE TITLE
validate组件做的不友好

### ISSUE THREAD

**Issue by wch0508** [didi/cube-ui#248]
validate组件验证输入，校验时机默认是keyup，不可以添加blur之类的验证时机吗？如果用异步，感觉单纯验证输入格式完全没必要，而且不好设置异步时长，1秒或2秒都不太友好，毕竟每个人的输入速度是不一样的。需要请求后台接口才用异步，比如输入手机号，验证是否已注册过。希望改进下吧......

**Comment by dolymood** [comment]
validator 不处理校验时机，只处理异步校验，也就是发请求的场景。

至于blur校验的问题，我们做到 form 中了，validator纯粹的负责验证
