### ISSUE TITLE
checkbox没有change事件

### ISSUE THREAD

**Issue by sweida** [didi/cube-ui#249]
checkbox组件没有change事件，不能写事件

**Comment by sweida** [comment]
checkbox点击就相当一个开关，就是为了触发某个事件，没有change事件，click也不能写，只能用watch去监听值的变化，结果组件里用watch会出现意想不到的bug，写到崩溃

**Comment by dolymood** [comment]
逻辑问题，和组件无关

**Comment by sweida** [comment]
真的逗，哪个UI的checkbox组件没有change事件？没有change事件写不了逻辑，这是我的逻辑？  算了瞎了眼，不知道看上你们UI哪里

**Comment by suozhao** [comment]
@dolymood 请问,我想实现全选有什么办法么
