### ISSUE TITLE
indexList组件中，点击最后一个list时的currentIndex没有落到lastIndex

### ISSUE THREAD

**Issue by liangxiaoxin** [didi/cube-ui#25]
indexList中，当最后一个list的高度(数据较少时)少于屏幕的高度时，点击最后一个list时的currentIndex时没有落到lastIndex的，这个可否作出优化的处理？

**Comment by ustbhuangyi** [comment]
我们内部讨论了一下，这个并不是一个 bug，而且也难以做出两全其美的办法。
首先，当最后一条数据少的时候，虽然点击右侧索引没有落到，但实际上它的内容已经可以看到了，这是符合预期的，右侧索引的高亮还是应该跟随吸顶的索引。这个也参考微信公众号列表的交互，也是这么实现的。
