### ISSUE TITLE
做的像一坨屎

### ISSUE THREAD

**Issue by sweida** [didi/cube-ui#251]
忍不住过来说几句，真的做的像一坨屎，form表单里的input框连number都不支持，maxlength也不支持，就是一坨屎

**Comment by dolymood** [comment]
还请注意自己的态度，这里是开源 issue，不是用来你去发泄自己的情绪的地方。

PS: 至于我们的组件做的好不好，这是一个问题；但是不能满足您大佬的需求，惹到您了，那不好意思。
