### ISSUE TITLE
iPhone 6sp 系统版本11.0.3拍照上传预览的图片旋转了

### ISSUE THREAD

**Issue by liubin595338764** [didi/cube-ui#253]
### Version
1.10.6

### Reproduction link
[http://none](http://none)

### Steps to reproduce
iPhone 6sp 系统版本11.0.3拍照上传预览的图片旋转了-90°

### What is expected?
iPhone 6sp 系统版本11.0.3拍照上传预览的图片旋转了-90°

### What is actually happening?
iPhone 6sp 系统版本11.0.3拍照上传预览的图片旋转了-90°

### Dependencies Version
vue: 2.5.17-beta.0
better-scroll: 1.12.0

**Comment by liubin595338764** [comment]
上传的进度条也有较大的误差，经常停在99%，已经设置了progressInterval:1000  也没效果

**Comment by dolymood** [comment]
照片我们没有做任何处理，

至于进度 这个误差的话 可能要看API 返回的了，因为这个比值是根据 progress 事件计算得出的

经常停留在 99% 目测是因为 progress  中计算的值已经是 100% 了，但是因为整个请求还没成功，所以强制设置了 100%，待到请求响应200后变为 100%

**Comment by liubin595338764** [comment]
照片没有做任何处理感觉是不对的，应该需要对图片的Orientation判断下，不然的话cube-upload-file这个组件有缺陷。
因为不同机型的摄像头拍出来图片的Orientation不一样，会有旋转的。

**Comment by dolymood** [comment]
这个应该是后端或者额外的处理工具来处理了，我们也提供了钩子可以支持预处理，例如图片压缩等，详见 https://github.com/didi/cube-ui/blob/dev/example/pages/upload/compress.vue

**Comment by liubin595338764** [comment]
预览的blob:http://图片是本地的，还没有到后端。这个和图片压缩是没有关系的

**Comment by phoeshow** [comment]
我也认为可以在组件中增加对EXIF信息的检测，这个可以在组件里先预处理优化一下

**Comment by dolymood** [comment]
组件层面不负责这部分的能力，有需求的可以自己通过钩子处理
