### ISSUE TITLE
cube-tab-bar配合cube-tab-panels或者cube-slide的时候高度问题

### ISSUE THREAD

**Issue by hezhongfeng** [didi/cube-ui#254]
### Version
1.10.4

### Reproduction link
[https://didi.github.io/cube-ui/example/#/tab-bar/tab/basic](https://didi.github.io/cube-ui/example/#/tab-bar/tab/basic)

### Steps to reproduce
如下，如果cube-slide-item或者cube-tab-panel的内容高度不一致，那么cube-slide高度总会一直是最大值，也就是说当我切换到高度不高的slide的时候仍然会出现滚动条
![](http://ww1.sinaimg.cn/large/b2395f3dly1fte3wb785ug20bp0hiwpf.gif)
```
    <cube-tab-bar :value="value" @input="input" :useTransition="disabled" ref="tabNav" :data="tabs">
    </cube-tab-bar>
    <div class="tab-slide-container">
      <cube-slide ref="slide" :loop="loop" :initial-index="initialIndex" :auto-play="autoPlay" :show-dots="showDots" :options="options" @scroll="scroll" @change="changePage">
          <cube-slide-item>
          </cube-slide-item>
      </cube-slide>
    </div>
```

### What is expected?
想让高度随着切换的内容切换

### What is actually happening?
现在是固定的高度

### Dependencies Version
vue: 2.5.16
better-scroll: 1.12.0

**Comment by dolymood** [comment]
这个修改下 tab-panels 的样式就好了，只要里边内容滚动就好了

**Comment by liouer** [comment]
这个问题现在还会有。
