### ISSUE TITLE
建议 timepicker 增加属性，可以设置显示当前时间之前的时间

### ISSUE THREAD

**Issue by tkggusraqk** [didi/cube-ui#26]
有以下两点问题：

1.  timepicker只能显示和设置当前时间之后的时间，而不能设置当前时间之前的时间。这极大的限制了timepicker的应用场景。建议增加属性，以支持设置当前时间之前的时间。

2. 对于时间的显示，建议可以直接显示时间 ，而不是默认显示【今天】

**Comment by ustbhuangyi** [comment]
cube-ui 的 timepicker 的来源是滴滴预约的场景，只能选择当前时间之后某个时间间隔的数据，所以有数据联动的需求，会比较复杂。
你这个需求，完全可以用普通的 Picker 就可以实现，只需要把时间数据传入即可。
@AmyFoxFN ，可以在我们的 Picker Demo 里增加一个年月日以及时分秒的 Picker 示例。

**Comment by AmyFoxFN** [comment]
嗯，可以啊

**Comment by levai** [comment]
继续跟着黄老师学习，😄 。

**Comment by dolymood** [comment]
选择时间的： https://github.com/didi/cube-ui/blob/dev/example/components/normal-time-picker.vue

选择日期的： https://github.com/didi/cube-ui/blob/dev/example/components/date-picker.vue

可以做参考
