### ISSUE TITLE
A example's bug with  Safari

### ISSUE THREAD

**Issue by hezhongfeng** [didi/cube-ui#261]
watch the header.It's diff between chrome.
The safari's header hasn't changed.

![Safari](http://ww1.sinaimg.cn/large/b2395f3dly1ftmzt5jxtwg20a00gmqlf.gif)
![chrome](http://ww1.sinaimg.cn/large/b2395f3dly1ftm6i40xoyg20a00gmalv.gif)

**Comment by hezhongfeng** [comment]
找到问题了
是page和head的z-index不同导致
等我提一个PR吧，可是现在clone不下来

**Comment by hezhongfeng** [comment]
@dolymood 
你好，
这个问题我们已经解决了，想提PR但是需要修改咱们很多地方，所以比较迟疑
罪归祸首是`example/components/cube-page.vue`里面77行位置的`overflow: auto`
这个滚动是为了给一般页面，例如button的例子提供一个会自然滚动的wrapper
我找了很久也不知道是为什么会引起（只有在ios移动端才会有这个问题）
我们的解决办法是：
1、去除这个`overflow: auto`
2、在各个使用page的页面自己添加滚动，但我总感觉不是很好
所以来请教下

**Comment by dolymood** [comment]
已经修了 我把 overflow scolling 去掉了

**Comment by hezhongfeng** [comment]
@dolymood 
请问为什么你知道吗？我虽然知道问题在哪，但是并不清楚引起问题的原因

**Comment by dolymood** [comment]
不知道，现在移动端很多问题 不能解释 😄
