### ISSUE TITLE
[New Feature] cube-ui好像没有做国际化，有后续计划吗？

### ISSUE THREAD

**Issue by vvchen** [didi/cube-ui#262]
### What problem does this feature solve?
产品多语言切换

### What does the proposed API look like?
提供语言包和用户自定义语言包方法

**Comment by yangxiufang1994** [comment]
直接用的vue-i18n，不需要ui框架直接做国际化，cube-ui 本来对文案就可以进行设置，所以只需放在语音包，用变量就可以
//具体可以参考vue-i18n  [http://kazupon.github.io/vue-i18n/guide/started.html#javascript]
import en from '@/static/lang/en.js';--自己语言包的目录
en.js 的格式 类似 export default {
  message: {
    Cancel: '取消',
    OK: '确定'
   }
}
import zhCHS from '@/static/lang/zhCHS.js';
import VueI18n from 'vue-i18n';
const messages = {
    en,
    zhCHS
  }
let lang
if (sessionStorage.lang) {
    if (sessionStorage.lang == 'en-US') {
        lang = 'en'
    } else if (sessionStorage.lang == 'zh-CN'){
        lang = 'zhCHS'
    } else {
        lang = 'en'
    }
} else {
    if (navigator.language == 'en-US') {
        lang = 'en'
    } else if (navigator.language == 'zh-CN') {
        lang = 'zhCHS'
    } else {
        lang = 'en'
    }
}
const i18n = new VueI18n({
//定义默认语言
    locale: lang, 
    messages
})
new Vue({ i18n }).$mount('#app')

<div >{{$t("message.OK")}}</div>

**Comment by vvchen** [comment]
这个我知道，但是提供语言包更方便，不用自己来写到模板和js代码里了

**Comment by dolymood** [comment]
1.x 暂无计划

2.x 的话应该会考虑

**Comment by 2014guai** [comment]
现在有了，只是不知道咋用。。。这文档没看明白啊。
