### ISSUE TITLE
[New Feature] picker组件不支持自定义布局吗？

### ISSUE THREAD

**Issue by since911** [didi/cube-ui#263]
### What problem does this feature solve?
比如添加自定义按钮，绑定事件，因为这个dom是通过构造函数创建的，并不知道如何个性化他的布局

### What does the proposed API look like?
无

**Comment by ustbhuangyi** [comment]
picker 的布局应该是相对固定的，而且已经支持了传入的元素是一个 html，如果自定义很强的建议自己去开发一个组件。
