### ISSUE TITLE
关于datePicker

### ISSUE THREAD

**Issue by Eaststart** [didi/cube-ui#267]
请问是怎么解决 输入日期 xxx年 12月xxx日 变为 xxx+1年的问题？

**Comment by dolymood** [comment]
没明白具体需求

**Comment by Eaststart** [comment]
我在调试cube框架源码的时候，结束日期设置为 new Date(2020,12,31) 但是在前端页面显示的时候 会显示到2021年1月31号。也就是多了一个月。

**Comment by AmyFoxFN** [comment]
![image](https://user-images.githubusercontent.com/24366060/43438852-df386ad2-94c2-11e8-858d-95215be701b3.png)
date构造函数参数的月份是从0-11的

**Comment by AmyFoxFN** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Date
