### ISSUE TITLE
datePicker性能问题

### ISSUE THREAD

**Issue by Eaststart** [didi/cube-ui#268]
如果将时间跨度设置为超过1000   也就是 开始时间 new Date(2000,2,2) 结束时间 new Date(4000,2,2), 页面会出现明显的卡顿，请问有计划解决这个性能问题嘛？其他的picker组件也是。

**Comment by ustbhuangyi** [comment]
为什么会有这样的需求（包括其他 picker）

**Comment by Eaststart** [comment]
目前还没有这样的需求，只是试了试性能。

**Comment by ustbhuangyi** [comment]
我的理解，如果真有这样的场景（海量数据），是不是就不适合用 picker 组件实现了（对用户的使用也非常不友好），应该用其他的交互方式呢？
