### ISSUE TITLE
ImagePreview图片浏览图片长度过长手机切换有问题

### ISSUE THREAD

**Issue by SupperMan1992820** [didi/cube-ui#270]
代码完全是用的官方的例子ImagePreview的自定义使用的例子 但是其中一张图片我换成了百度找的一张图片https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1533203632049&di=47e25dff3bccc71d70fffe0987cb5fc4&imgtype=0&src=http%3A%2F%2Fd.paper.i4.cn%2Fmax%2F2017%2F01%2F04%2F11%2F1483499507919_134159.jpg  然后在手机上浏览切换是有问题的

**Comment by dolymood** [comment]
1.10.10 已修复
