### ISSUE TITLE
【input】组件在失去焦点之后，清除按钮应该隐藏

### ISSUE THREAD

**Issue by LeeRayno** [didi/cube-ui#271]
### Version
1.10.10

### Reproduction link
[https://github.com/didi/cube-ui/blob/44f2a28d4651971a8b92d1df3d60af10ca8b8e86/src/components/input/input.vue#L101](https://github.com/didi/cube-ui/blob/44f2a28d4651971a8b92d1df3d60af10ca8b8e86/src/components/input/input.vue#L101)

### Steps to reproduce
https://github.com/didi/cube-ui/blob/44f2a28d4651971a8b92d1df3d60af10ca8b8e86/src/components/input/input.vue#L101

### What is expected?
失去焦点时，清除按钮隐藏

### What is actually happening?
失去焦点时，没有隐藏

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

---
``` js
_showClear() {
        return this.clearable && this.inputValue && !this.readonly && !this.disabled && !this.isBlur
      },
```

**Comment by dolymood** [comment]
主流都是不隐藏的，GitHub Google等，而且清除是为了清除内容，任何时候都应该可以清空才对

**Comment by LeeRayno** [comment]
只有在他有输入的动作的时候才会显示啊！比如我这条输入完成了，我要输入下一条了，已经失去了交点，上一条的清除按钮还在那里显示着，不觉得怪怪的吗。那我总共要输入10条20条，后面都显示着清除按钮。不觉得有问题啊。我看微信，支付宝都是失去焦点之后都隐藏了的。

发自我的 iPhone

**Comment by dolymood** [comment]
如果是你的场景 你可以通过样式就满足需求，当获得焦点的时候，input 会有 `cube-input_active` 的 class，当失去焦点的时候就没有这个 class 了

**Comment by LeeRayno** [comment]
好的，谢谢，我根据你们的从新写了个input. 

还有 `popup`组件为什么没有在`cube-popup-mask` 和 `cube-popup-content`上面加上 `@touchmove.prevent`事件阻止遮罩层下面的类容滚动了？

我看所有 `popup`弹框类的组件 好像`actionSheet`组件里面 在 `<cube-popup />`容器上面加了`@touchemove.prevent`，但是也不起作用，后面我用 `popup`重新写了个dialog，并用插槽 `slot=mask` 样式`height: 100%;` 在`slotMask`上面加上 `@touchmove.prevent`可以阻止遮罩下面滚动。但是在 `cube-popup-content`上面滑动，遮罩下面的内容还是会滚动。。。

**Comment by dolymood** [comment]
1.11 已支持
