### ISSUE TITLE
use slide tabBar scroll 组件遇到一个问题

### ISSUE THREAD

**Issue by jimmylinzl** [didi/cube-ui#275]
参考的是  https://didi.github.io/cube-ui/example/#/tab-bar/tab/composite 写法 发现在de mo改动也有问题  问题如下： 1.在包裹tab和tab内容的外层加上overflow:auto 然后禁掉cube-ui组件包裹的滚动，发现只有tab可以滑动，被slide组件和scroll组件包裹的不可以滑动  2.使用的官方推荐快速上手的https://cube-ui.github.io/cube-application-guide/  测试了一下也有问题 求解决，换组件代价太大～谢谢！

**Comment by dolymood** [comment]
为啥要 overflow auto 呢，如果真想要auto的效果，同时保留默认行为的话，可以设置 slide或者scroll的options. preventDefault 的值为 false
