### ISSUE TITLE
Slide should update its `currentPageIndex` value when `initialIndex` value changed

### ISSUE THREAD

**Issue by tinymins** [didi/cube-ui#278]
### Version
1.10.10

### Reproduction link
[https://codesandbox.io/s/jzy76zjroy](https://codesandbox.io/s/jzy76zjroy)

### Steps to reproduce
Change slide's `initialIndex` in page's `mounted` method.

### What is expected?
Slide will init with new `initialIndex` value which was set in `mounted`

### What is actually happening?
Slide still use the default `initialIndex` value in `data()`

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

---
I've created a PR, just with one line added to solve this problem.

**Comment by dolymood** [comment]
1.10.11 fixed this issue
