### ISSUE TITLE
ios 使用slide组件来回滑动切换tab

### ISSUE THREAD

**Issue by jimmylinzl** [didi/cube-ui#280]
问题：ios7以后，苹果推出了手势滑动返回功能，也就是从屏幕左侧向右滑动可返回上一个界面。
            目前我发现手指滑动区域在slide包裹的元素区间，也会左滑滑出页面，体验不太好，请问有什么 
            解决方案吗？

**Comment by dolymood** [comment]
并不是那个区间，手势返回有一个条件就是手指一定是从屏幕边缘滑动才算，如果是里边滑动并不算

这属于浏览器推荐交互行为，感觉这个体验没问题。
