### ISSUE TITLE
[New Feature] CheckboxGroup未来是否有计划支持可以设置最大最小选中的个数

### ISSUE THREAD

**Issue by songyazhao** [didi/cube-ui#284]
### What problem does this feature solve?
我有很多checkbox，但是业务规定了只能其中两个，这个时候我不得不自己写很多针对选中数量限制的代码逻辑，所以希望能够自组件上自支持，，这在开发中是很省心省力的。O(∩_∩)O~

### What does the proposed API look like?
类似 vux 中 [checklist](https://doc.vux.li/zh-CN/components/checklist.html) 组件属性的 `max` 和 `min`

**Comment by dolymood** [comment]
1.11 已支持
