### ISSUE TITLE
中文文档和英文文档不一样

### ISSUE THREAD

**Issue by Ding-Fan** [didi/cube-ui#287]
### Version
1.10.10

### Reproduction link
[https://didi.github.io/cube-ui/#/en-US/docs/slide](https://didi.github.io/cube-ui/#/en-US/docs/slide)

### Steps to reproduce
打开 https://didi.github.io/cube-ui/#/zh-CN/docs/slide
打开 https://didi.github.io/cube-ui/#/en-US/docs/slide

### What is expected?
文档内容一样

### What is actually happening?
文档内容不一样！

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

---
我照着英文文档写了半天 slide 感觉不对，一看中文文档果然不出所料

**Comment by dolymood** [comment]
已修复
