### ISSUE TITLE
刷新的时候会有抖动

### ISSUE THREAD

**Issue by zqs9004** [didi/cube-ui#29]
上拉加载或者下拉刷新的时候 会有回弹的抖动啊
部分苹果7的版本

**Comment by ustbhuangyi** [comment]
抖动的表现是什么，能否录一个 gif 图说明

**Comment by dolymood** [comment]
@zqs9004  多谢反馈，希望可以给出更多详细内容或者demo链接 录屏都可以，根据目前信息我们不能定位问题。建议重新提一个新的 Issue
