### ISSUE TITLE
stickyEle  模块暴露出错

### ISSUE THREAD

**Issue by lion-git** [didi/cube-ui#293]
### Version
1.10.10

### Reproduction link
[ https://github.com/didi/cube-ui/blob/dev/src/modules/sticky/index.js]( https://github.com/didi/cube-ui/blob/dev/src/modules/sticky/index.js)

### Steps to reproduce
https://github.com/didi/cube-ui/blob/dev/src/modules/sticky/index.js
StickyEle 没有暴露出去

import Sticky from '../../components/sticky/sticky.vue'
import StickyEle from '../../components/sticky/sticky-ele.vue'

Sticky.install = function (Vue) {
  Vue.component(Sticky.name, Sticky)
  Vue.component(StickyEle.name, StickyEle)
}

Sticky.Ele = Sticky

export default Sticky

### What is expected?
StickyEle 被正确暴露

### What is actually happening?
StickyEle 没有被正常暴露

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

**Comment by dolymood** [comment]
要想获取 StickyEle 就使用 Sticky.Ele 就可以了
