### ISSUE TITLE
外部JS调用过Toast后再通过this.$createToast调用会报错

### ISSUE THREAD

**Issue by easonzhang2015** [didi/cube-ui#295]
### Version
1.10.11

### Steps to reproduce
1.外部js文件先调用Toast.$create({ ... }).show();
2.Vue作用域内调用this.$createToast({...})
报错：oldOwnerInstance.$off is not a function
    at VueComponent.create [as $createToast] 

### What is expected?
js外调用和Vue内调用可以同时使用

### What is actually happening?
一起使用会报错

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

**Comment by dolymood** [comment]
1.10.13 resolved this error

**Comment by thisAries** [comment]
我也遇到了 现在就区更新~
