### ISSUE TITLE
增加骨架屏组件，当前没有一个通过简单的方法来实现

### ISSUE THREAD

**Issue by celverbamboo** [didi/cube-ui#301]
对应文章参考:[点击跳转](https://xiaoiver.github.io/coding/2017/07/30/%E4%B8%BAvue%E9%A1%B9%E7%9B%AE%E6%B7%BB%E5%8A%A0%E9%AA%A8%E6%9E%B6%E5%B1%8F.html)
效果图
![image](https://user-images.githubusercontent.com/24216880/45069320-82f3d600-b0fe-11e8-86bf-d5f0e8f46ca7.png)

**Comment by dolymood** [comment]
这个并不属于组件层面做的事情，方案有很多，属于应用层感知优化的部分，建议自己应用内自己实现即可。

**Comment by celverbamboo** [comment]
好的谢谢
