### ISSUE TITLE
最新版本 scroll 加载动画 位置显示有问题

### ISSUE THREAD

**Issue by Wildlifes** [didi/cube-ui#304]
下拉加载动画位置异常，下拉列表加载高度pulldown-wrapper高度异常 设置stop属性无效

**Comment by dolymood** [comment]
pulldown-wrapper 的高度是撑起来的，options.pullDownRefresh则是对应的 https://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options-advanced.html#pulldownrefresh

**Comment by Wildlifes** [comment]
我使用cube-ui 1.2.6 就不会出现类似问题
