### ISSUE TITLE
下拉加载动画位置异常，下拉列表加载高度pulldown-wrapper高度异常 设置stop属性无效

### ISSUE THREAD

**Issue by Wildlifes** [didi/cube-ui#305]
我使用cube-ui 1.2.6 就不会出现类似问题
但是使用最新帮帮1.10.14的就遇到问题，

**Comment by Wildlifes** [comment]
测试 cube-ui 1.9.7出现这个问题

**Comment by Wildlifes** [comment]
![image](https://user-images.githubusercontent.com/26505011/45261520-578f2500-b437-11e8-9ff3-b4bbd64e2fc9.png)

**Comment by Wildlifes** [comment]
加载动画显示位置比预想的高度   高

**Comment by Wildlifes** [comment]
应为项目是不方便分享
只能提供部分demo

**Comment by Wildlifes** [comment]
![image](https://user-images.githubusercontent.com/26505011/45339196-e466e980-b5c3-11e8-8097-1f0a02e8e491.png)
这边fa'xian发现这个top值 使用1.9.5版本显示正常的时候是10px 到-60px指尖，
但是我使用了最新版本top值一直都是负数

**Comment by Wildlifes** [comment]
![image](https://user-images.githubusercontent.com/26505011/45339364-d06fb780-b5c4-11e8-8778-92c7bb01b9e5.png)

**Comment by guigui730** [comment]
最后怎么解决的？
