### ISSUE TITLE
Swipe组件，左滑当前选项的时候，需要自己手动写其它滑入

### ISSUE THREAD

**Issue by celverbamboo** [didi/cube-ui#307]
为什么？不指定一个属性来控制？人之初，性本懒
而是通过@active自己来手写
![screenshot 2018-09-11_14-31-20](https://user-images.githubusercontent.com/24216880/45342085-67da0800-b5cf-11e8-9f0e-dc5911ad5d6c.png)
![screenshot 2018-09-11_14-31-33](https://user-images.githubusercontent.com/24216880/45342088-6a3c6200-b5cf-11e8-875c-c95dba71e837.png)

**Comment by thisAries** [comment]
确实很伤 如果底部导航栏点击有滑动效果 那么下面的也应该是有滑动功能的。为了做到这个效果，我把内部的组件改成了slide

**Comment by dolymood** [comment]
1.11 supported
