### ISSUE TITLE
cube-ui的scroll组件，在使用keep-alive的页面里，无法用scrollto方法保存上次浏览的位置

### ISSUE THREAD

**Issue by GOGOGOSIR** [didi/cube-ui#311]
### Version
1.10.14

### Reproduction link
[http://m.harohouse.com/#/](http://m.harohouse.com/#/)

### Steps to reproduce
我在进入子页面之前会保存当前页面的startY，然后从子页面里面退回来是，在利用scrollto重新定位至上次的位置

### What is expected?
能够保存上次用户的浏览的位置

### What is actually happening?
在多次操作后，会出现突然返回最开始的位置

### Dependencies Version
vue: 2.5.17
better-scroll: 1.12.0

**Comment by tank0317** [comment]
见 Cube-UI QA https://github.com/cube-ui/question-answer/issues/18
