### ISSUE TITLE
[New Feature] 希望$createTimePicker里面可以加入min以及max属性

### ISSUE THREAD

**Issue by gaozhe3321** [didi/cube-ui#314]
### What problem does this feature solve?
时间选择器中加入最小时间以及最大时间的选项，使用户方面快捷的选择到业务当前可用的时间

### What does the proposed API look like?
this.$createTimePicker({
    title: '运营时间',
    min:'6:30',
    max:'23:00'
})

**Comment by dolymood** [comment]
这个可以使用 datepicker 就可以满足需求了
