### ISSUE TITLE
官网上的CascadePicker组件下的异步加载数据：<cube-button @click="showAsyncPicker">Async Load Data</cube-button>里的showAsyncPicker方法找不到呀？？

### ISSUE THREAD

**Issue by xueyunanhai** [didi/cube-ui#319]
官网上的CascadePicker组件下的异步加载数据：<cube-button @click="showAsyncPicker">Async Load Data</cube-button>里的showAsyncPicker方法找不到呀？？

异步加载数据

当数据量太大时，可能难以在最开始就生成完整的级联数据树。这时，你可以配置 async 属性开启异步加载级联数据，在 change 事件时，去更新数据，并且在你更新完数据之前，用户点击确认会是无效的。

<cube-button @click="showAsyncPicker">Async Load Data</cube-button>

**Comment by theniceangel** [comment]
文档里没写出来。相关实现你可以看下示例的源码。[CascadePicker异步加载](https://github.com/didi/cube-ui/blob/dev/example/pages/cascade-picker.vue)

**Comment by theniceangel** [comment]
我现在在文档里面补充下吧
