### ISSUE TITLE
表单绑定@submit事件后，有默认跳转，会在路由后加入?这个符号

### ISSUE THREAD

**Issue by jamesXG** [didi/cube-ui#324]
<cube-form :model="loginForm" @validate="validateLogin" @submit="submitLogin"></cube-form>

**Comment by dolymood** [comment]
如果都是同步校验，在submit中你是要自己阻止默认行为的，如果有异步行为，则不需要。

**Comment by jamesXG** [comment]
请问cube时如何组织默认行为的呢？？我在文档中没有找到相关说明

**Comment by dolymood** [comment]
我们的示例中是一直阻止的，这个其他的是没说明的。后边我们可以在文档中做个补充。
