### ISSUE TITLE
Scroll 组件嵌套，外层纵向滚动 内层横向滚动 目前表现有点奇怪

### ISSUE THREAD

**Issue by GodStream** [didi/cube-ui#330]
### Version
1.11.0

### Reproduction link
暂无

### Steps to reproduce
1、外层纵向滚动 内层横向滚动 nestMode="native"
2、外层纵向滚动 内层横向滚动 nestMode="free"

### What is expected?
1、滚动内层Scroll 能正确滚动纵向整个页面
2、内层横向滚动时不触发click事件

### What is actually happening?
1、nestMode 为 native 时，内层只能横向滚动，不能带动整个页面纵向滚动，感觉这样是不合理的
2、free时，内层在滚动边界时能正常带动外层纵向滚动，不在边界时就无效
3、内层滚动都会触发click事件

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

---
```
<cube-scroll>
  <cube-scroll direction="horizontal"></cube-scroll>
</cube-scroll>
```

**Comment by tank0317** [comment]
你可以尝试给内层 Scroll 组件传递 better-scrol 配置项 `eventPassthrough: 'vertical'`。

这种情况和内层使用 cube-scroll 实现横向滚动，外层使用浏览器原生滚动的情况是一样的。都需要传递 better-scroll 配置项 [peventPassthrough](http://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#eventpassthrough) 。

**Comment by GodStream** [comment]
@tank0317 感谢回复，eventPassthrough我了解到了，不过还会有个问题内层滚动时会触发click事件如何处理呢？使用stopPropagation就会将外层滚动给禁止了

**Comment by GodStream** [comment]
@tank0317   默认配置 click 已经是false, 并没有改动, 内层scroll里的一个div绑定的click被触发，奇怪的是同一页面上，有多个内层横向滚动 scroll，只有第一个滚动会触发click，其余是正常的点击才会触发，第一个与其它不同点只有dom的层级不同

**Comment by tank0317** [comment]
cube-scroll 中 click 是默认设置为 true 的。

**Comment by GodStream** [comment]
@tank0317 项目中已经引入了fastclick，外层设置click 为 false 是有效果的，第一个正常了，但是会导致之前正常的scroll内click无效，确定内层的scroll配置都是一致的。这种表现是正常的吗？1.10.x 中是正常的，更新到1.11.0后出现的问题。

**Comment by tank0317** [comment]
不正常，能提供个重现的 demo 吗。

不好意思回晚了

**Comment by GodStream** [comment]
可以的，有搭好cube-ui环境的codesandbox之类的吗？或者晚点我本地搭一个传到github上来

**Comment by dolymood** [comment]
@GodStream  试下 1.11.2 是否还有上述说的那个不一致的问题

**Comment by GodStream** [comment]
试了一下问题还存在，目前单独做demo没能重现出来，只能暂时不使用scroll做外层滚动，我再尝试是否能重现

**Comment by dolymood** [comment]
1.12 可以考虑 

1.11 我们会 deprecate 掉

**Comment by yishangtanhuan** [comment]
> 你可以尝试给内层 Scroll 组件传递 better-scrol 配置项 `eventPassthrough: 'vertical'`。
> 
> 这种情况和内层使用 cube-scroll 实现横向滚动，外层使用浏览器原生滚动的情况是一样的。都需要传递 better-scroll 配置项 [peventPassthrough](http://ustbhuangyi.github.io/better-scroll/doc/zh-hans/options.html#eventpassthrough) 。

请问，怎么给 Scroll 组件传递 better-scroll 配置项
