### ISSUE TITLE
[bug] cobu-input 不支持自定义placeholder的样式

### ISSUE THREAD

**Issue by 94club** [didi/cube-ui#331]
我在源码input.vue里面看到placeholder的color有一个important属性， 请问加这个属性的原因能告知一下吗

**Comment by dolymood** [comment]
如果我记得不错的话，是为了解决部分机型的样式问题

**Comment by goldencolor** [comment]
\deep\  css

**Comment by dolymood** [comment]
1.12 已将 important 去掉
