### ISSUE TITLE
checkbox label点击

### ISSUE THREAD

**Issue by lemonwong** [didi/cube-ui#334]
checkbox的label点击会自动切换chackbox选中或者不选中，我的需求是 我在label里面写了许可协议。我想当用户点击许可协议的时候，能跳转到详细的许可协议页面，应该怎么处理

**Comment by lemonwong** [comment]
还有  switch为什么不能默认把label显示在左边····在右边看着好不舒服

**Comment by tennessine** [comment]
@lemonwong 你知道怎么引入SlideItem吗？

**Comment by dolymood** [comment]
@lemonwong  协议的话，可以考虑插槽，然后阻止冒泡即可

switch 放在后边的case 那个应该是和其他布局组合使用的情况

**Comment by lemonwong** [comment]
@dolymood 请问怎么使用插槽  我要修改源码吗？
