### ISSUE TITLE
form表单input框iso关闭软件键盘后，再次点击获取不了焦点

### ISSUE THREAD

**Issue by zhupp034** [didi/cube-ui#337]
<!--
IMPORTANT: Please use the following link to create a new issue:

  https://cube-ui.github.io/cube-issue-helper/

If your issue was not created using the app above, it will be closed immediately.

ios必须在input框停留1秒才能获取焦点

**Comment by zhupp034** [comment]
iso必须停留在input上1秒左右才能获取焦点，呼出键盘

**Comment by theniceangel** [comment]
你是用了fastclick么

**Comment by dolymood** [comment]
之前fastclick 是有报错问题的在iOS11上，目测是这个问题引起的。

**Comment by dolymood** [comment]
目测 fastclick 的问题，在ios11下会有报错导致点击取消。

**Comment by zhupp034** [comment]
谢谢，检测了是这个问题，对input过滤了就好了

**Comment by dongqizhen** [comment]
这个怎么把组件下的input 忽略掉的 我为啥没有作用

**Comment by dongqizhen** [comment]
@zhupp034 @dolymood
