### ISSUE TITLE
全局引用cube，没有加载样式

### ISSUE THREAD

**Issue by ysxlinux** [didi/cube-ui#34]
入口文件全局加载cube-ui，在页面中引用某个组件后，页面能正常渲染出组件的dom结构，但是组件相关的css样式一个都没有加载，这是什么原因？

**Comment by dolymood** [comment]
是不是没引入样式部分。

PS：建议提供关键代码，这样就只能确切知道问题所在

**Comment by lk19940215** [comment]
import { Style } from 'cube-ui'
发现，并没有跟 Style 组件内容一样，去import Stylus 文件。
解决方法 在组件script 处 调用 import 'cube-ui/lib/style.css';

**Comment by zuiqiangqishao** [comment]
> import { Style } from 'cube-ui'
> 发现，并没有跟 Style 组件内容一样，去import Stylus 文件。
> 解决方法 在组件script 处 调用 import 'cube-ui/lib/style.css';

感谢，已解决，我觉得官方文档没写怎么引入样式，建议加上说明
![image](https://user-images.githubusercontent.com/20850040/61615350-60c46180-ac98-11e9-8bc8-1bef77ab1f0b.png)
