### ISSUE TITLE
一个移动端bug！！！

### ISSUE THREAD

**Issue by SkyWblack** [didi/cube-ui#346]
案例介绍 ：使用TabBar组件中的官方tab-composite.vue 案例
场景：移动端设备
描述：

1.完全复制官方的ab-composite.vue 案例代码，在初始进去tab页面时，所有的效果可以正常显示，可以进行tab切换，slide正常滑动，

2.当在cube-slide-item标签中，设置一个按钮，跳转到另外一个页面 (注：此页面有input框)，并且在input输入值，

3.返回tabBar所在页面，出现问题：slide组件不能滑动。

希望官方给予解决！！！

**Comment by dolymood** [comment]
请按照issue规范提。
