### ISSUE TITLE
[New Feature] textarea有值的情况下显示不全

### ISSUE THREAD

**Issue by ShieldCN** [didi/cube-ui#348]
### What problem does this feature solve?
打开表单页面，textarea默认有值的情况下是折叠状态，信息显示不全，建议应该在有值的情况下打开。或者加一属性是关闭这种自动打开折叠的功能，就想原生一样固定高度。

### What does the proposed API look like?
建议价格属性可以变得就想原生的一样

**Comment by dolymood** [comment]
1.12 支持了 autoExpand
