### ISSUE TITLE
使用upload后端一直没有返回，用的php，后端如何配置

### ISSUE THREAD

**Issue by ahz549467483** [didi/cube-ui#350]
### Version
1.11.2

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
使用upload后端一直没有返回，用的php，后端如何配置

### What is expected?
使用upload后端一直没有返回，用的php，后端如何配置

### What is actually happening?
使用upload后端一直没有返回，用的php，后端如何配置

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

**Comment by dolymood** [comment]
这属于后端需要处理的事情了吧，简单来说就是看php怎么处理上传
