### ISSUE TITLE
dialog.vue和form/fields/index.js三个点拷贝报错

### ISSUE THREAD

**Issue by Lsky1026** [didi/cube-ui#355]
例如：
error  in ./node_modules/cube-ui/src/components/dialog/dialog.vue
Syntax Error: Unexpected token (112:10)
  110 |       default() {
  111 |         return {
> 112 |           ...defConfirmBtn
      |           ^
  113 |         }
  114 |       }
  115 |     },
 @ ./node_modules/cube-ui/src/components/dialog/dialog.vue 8:0-235 9:0-248
 @ ./node_modules/cube-ui/src/modules/dialog/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server ./src/main.js

**Comment by Lsky1026** [comment]
我现在是直接将扩展运算符拷贝去掉，dev编译是通过的

**Comment by dolymood** [comment]
https://github.com/cube-ui/question-answer/issues 了解下
