### ISSUE TITLE
一个移动端bug！！！

### ISSUE THREAD

**Issue by SkyWblack** [didi/cube-ui#357]
### Version
1.12.5

### Reproduction link
[https://github.com/didi/cube-ui/blob/master/example/pages/tab-bar/tab-composite.vue](https://github.com/didi/cube-ui/blob/master/example/pages/tab-bar/tab-composite.vue)

### Steps to reproduce
案例介绍 ：使用TabBar组件中的官方tab-composite.vue 案例
场景：移动端设备
业务需求：类似网易云音乐APP的tab slide需求；
描述：
1.按照官方的tab-composite.vue 案例代码，在初始进去tab页面时，所有的效果可以正常显示，可以进行tab切换，slide正常滑动，
2.当在cube-slide-item组件中，点击跳转另一个页面路由组件（注：此页面有表单控件，比如input,textarea)
3.在表单域中输入值（注：移动端软键盘弹出）
4.返回tab slide组件页面，出现问题：slide组件不能滑动（scroll事件不执行，失效）。

### What is expected?
slide组件能够继续滚动

### What is actually happening?
slide组件不能滑动

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

**Comment by SkyWblack** [comment]
修改了官方slide组件源码，问题已解决。还是希望官方给出更加细节的修改。
原因是移动端的软键盘弹出事件并没有触发slide组件的resize事件，导致不能滚动。
`    activated() {
      /* istanbul ignore next */
      if (this.autoPlay) {
        /* 自动滚动到下一页 */
        this._play()
      }

       /* 官方源码  window.addEventListener('resize', this._resizeHandler) */ 
      /* 这里直接执行 _resizeHandler */
      this._resizeHandler();
    },`

**Comment by dolymood** [comment]
所以你是用了 keep-alive 实现的吧，目测的是需要在 activated 中需要调用一次 resize

**Comment by SkyWblack** [comment]
@dolymood  是的 用了 keep-alive  其实只要在activated里面强制调用下 this._resizeHandler() 这个自定义方法就ok了

**Comment by dolymood** [comment]
可以考虑使用 refresh 试下

**Comment by zhixinpeng** [comment]
标签页一般都需要使用keep-alive来缓存这个页面，如果这时候出现跳转到详情页，返回是会出现问题的。不过我只在IOS下发现了问题，在PC和安卓手机下，从详情页面返回是不会出现问题的。如果使用refresh去调用，会给使用者造成困扰。我这里还是在源码层面调用_resizeHandler()

**Comment by youngcao2015** [comment]
我这边是：使用Slide组件,在PC/Android/iOS均是跳转到另外一个页面再返回后，slide无法滑动。
