### ISSUE TITLE
action-sheet

### ISSUE THREAD

**Issue by yeungtg** [didi/cube-ui#358]
长按 触发 actionSheet功能，
ontouchstart(e) {
  this.timer = setTimeout(() => {
    this.createActionSheet(...)
    }, 500)
},
ontouchend() {
    clearTimeout(this.timer);
    this.timer = null;
},
maskClosable： true
ontouched 会触发 createActionSheet  遮罩的 onCancel 事件
导致 长按显示 抬手触发onCancel 又关闭了

**Comment by dolymood** [comment]
这属于逻辑问题吧

**Comment by yeungtg** [comment]
是也不是，  我抬起手指，就会触发 createActionSheet 遮罩的 onCancle 事件， 我觉得这个这个遮罩的点击事件 应该吧 onTouchEnd 过滤掉

**Comment by dolymood** [comment]
在移动端 click 就是根据 touch 事件触发的，只要你 touch 了就会触发 click 这很正常 没有所谓的过滤一说
