### ISSUE TITLE
级联选择器在手机端打开的状态下，横竖屏之间转换后文字会发生颠倒的情况

### ISSUE THREAD

**Issue by guohui666** [didi/cube-ui#360]
### Version
1.12.5

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/cascade-picker](https://didi.github.io/cube-ui/#/zh-CN/docs/cascade-picker)

### Steps to reproduce
级联选择器在手机端打开的状态下，横竖屏之间转换后文字会发生颠倒的情况

### What is expected?
希望能在横竖屏之间转换

### What is actually happening?
级联选择器在手机端打开的状态下，横竖屏之间转换后文字会发生颠倒的情况

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

**Comment by dolymood** [comment]
这种情况目测太奇葩了，希望可以提供更新信息
