### ISSUE TITLE
官网案例from表单中的input在微信h5移动端，ios12以上系统的苹果手机会出现input输入完,点完成，整个页面上移的情况

### ISSUE THREAD

**Issue by caiyuncheng** [didi/cube-ui#361]
### Version
1.12.5

### Reproduction link
[https://didi.github.io/cube-ui/example/](https://didi.github.io/cube-ui/example/)

### Steps to reproduce
1. ios12以上系统的苹果手机打开微信扫码，扫官网案例二维码，
2. 然后点击From表单的From选项,在选择Classic style进入目标页面,
3.然后点input获取焦点，输入点东西，点完成,
4.整个页面上移

### What is expected?
希望解决一下

### What is actually happening?
如果可以就解决一下

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

**Comment by yddLucky** [comment]
这个应该是微信的问题，微信6.7.4版本会有这个问题，其他版本的微信没有这个问题，我也遇到了这个问题，可以试一下其他的版本的微信。

**Comment by NickYangZY** [comment]
请问解决了吗？我现在用微信最新版的7.0.10的版本还有问题
