### ISSUE TITLE
如何兼容rem

### ISSUE THREAD

**Issue by Ray2Tang** [didi/cube-ui#362]
用了框架自带的REM转换，可是组件样式缩小严重，调整的话需要花大量时间，有没有好的解决方案呀

**Comment by dolymood** [comment]
我们基准值必须是 37.5

**Comment by luckelectricity** [comment]
我也是用来写了好久才发现这个问题的,然后我说下我的解决方案,
下载别人改的一个postcss-pxtorem的插件
`npm i postcss-px2rem-exclude`
修改你的.postcssrc.js文件
`module.exports = {
  "plugins": {
    // to edit target browsers: use "browserslist" field in package.json
    "postcss-import": {},
    "autoprefixer": {},
    // "postcss-px2rem": {
    //   "remUnit": 75
    // }
    'postcss-px2rem-exclude': {
      remUnit: 75,
      exclude: /node_modules/i
    }
  }
}`
这样cube用px,自己转的rem
本来想在loader里面忽略的,但是后来发现了这个插件

**Comment by aslzl** [comment]
我试了一下你的方法，貌似 postcss-px2rem-exclude 已经版本过低，解决不了问题，请问有好的解决方案么

**Comment by luckelectricity** [comment]
> 我试了一下你的方法，貌似postcss-px2rem-exclude已经版本过低，解决不了问题，请问有好的解决方案么

我觉得如果这样的话，你可以在打包的时候写个插件，把cube的css中的px转换成大写的PX，然后使用px2rem转换，浏览器是认识大写PX的，但是打包的时候不会自动转换为rem，或者每次打包之前找到文件去匹配然后替换。别的方法可能我暂时想不到了。
