### ISSUE TITLE
[New Feature] 是否考虑Form组件添加password及其可配置的图标

### ISSUE THREAD

**Issue by insipidness** [didi/cube-ui#366]
### What problem does this feature solve?
1.form组件是否可以添加password类型
2.form组件是否可以添加图标，类似cube-input可以自己自定义添加眼睛图标

### What does the proposed API look like?
 {type: 'password', },

**Comment by dolymood** [comment]
type input

然后增加 props 配置就可以了

**Comment by dolymood** [comment]
props: {
  type: 'password',
  eye: {...}
}

**Comment by myGitHubHuLin** [comment]
form input前缀或者后缀图标怎么配置
