### ISSUE TITLE
[New Feature] Slide 轮播图之间的间距 希望可以配置

### ISSUE THREAD

**Issue by GodStream** [didi/cube-ui#367]
### What problem does this feature solve?
Slide 轮播图之间的间距 配置，效果如下：

![image](https://user-images.githubusercontent.com/23089466/49575916-dfc18f80-f97e-11e8-8342-132a863cbcd3.png)

### What does the proposed API look like?
无

**Comment by dolymood** [comment]
说下具体需求吧 你这个是PC的效果吧

**Comment by GodStream** [comment]
对 截图的是pc端的，移动端类似。可以参考饿了么app首页的轮播图效果。

**Comment by dolymood** [comment]
目测和 https://didi.github.io/cube-ui/example/#/image-preview 的效果比较相似

可以作为参考。

**Comment by GodStream** [comment]
是的，但是需要在Slide里实现，不滚动的时候宽度是填满容器，滚动时当前项与下一项能有一定的间隔，目前单纯去覆盖css 好像无法实现

**Comment by dolymood** [comment]
建议群里讨论吧，这个目测可以实现。
