### ISSUE TITLE
picker的问题

### ISSUE THREAD

**Issue by zyh19941109** [didi/cube-ui#37]
版本v.1.0.2
代码：
mounted(){
this.picker = this.$createPicker({
                title: '选择文章类型',
                data: this.linkageData,
                onChange: (i, newIndex) => {
                    // console.log(i, newIndex)
                    if (newIndex !== this.tempIndex[i]) {
                        for (let j = 2; j > i; j--) {
                            this.tempIndex.splice(j, 1, 0)
                            this.picker.scrollTo(j, 0)
                        }
                        this.tempIndex.splice(i, 1, newIndex)
                        this.picker.setData(this.linkageData, this.tempIndex)
                    }
                }
            })
}
![image](https://user-images.githubusercontent.com/26808622/33606122-51b4ea68-d9f7-11e7-99b4-f6fed6058cec.png)
此版本报forEach错误
![image](https://user-images.githubusercontent.com/26808622/33606210-a763f60c-d9f7-11e7-9060-60294493b48a.png)

版本v.1.1.0
代码：
mounted(){
this.picker = this.$createPicker({
                title: '选择文章类型',
                data: this.linkageData,
                onChange: (i, newIndex) => {
                    // console.log(i, newIndex)
                    if (newIndex !== this.tempIndex[i]) {
                        for (let j = 2; j > i; j--) {
                            this.tempIndex.splice(j, 1, 0)
                            this.picker.scrollTo(j, 0)
                        }
                        this.tempIndex.splice(i, 1, newIndex)
                        this.linkagePicker.setData(this.linkageData, this.tempIndex)
                    }
                }
            })
}
![image](https://user-images.githubusercontent.com/26808622/33606122-51b4ea68-d9f7-11e7-99b4-f6fed6058cec.png)
此版本报forEach错误，联动也失效

目前解决办法（只是联动起效，forEach仍报错）将linkagePicker改为picker，另外在获取数据之后再加上
this.picker.setData(this.linkageData, this.tempIndex)

**Comment by AmyFoxFN** [comment]
linkagePicker只是一个变量名，只要create时定义的变量和watch里用的保持一致就可以了。
```javascript
this.linkagePicker = this.$createPicker({...})
```
```javascript
watch: {
    linkageData() {
        this.linkagePicker.refresh()
    }
}
```
关于forEach的报错，应该是因为在这个linkagePicker组件示例show之前，还没初始化完选择器的时候，就执行了refresh()导致的。这就有一些组件内部的细节问题，我们准备在下个版本单独封装一个联动选择器，处理这些逻辑。暂时的话，你可能需要自己控制，不要再linkagePicker,show之前执行到this.linkagePicker.refresh()了。

**Comment by AmyFoxFN** [comment]
关联到issue: #38

**Comment by zyh19941109** [comment]
官方示例的picker组件变量名--picker，还有很多未被更改为linkagePicker，希望加以纠正。。。谢谢您的回复。。。

**Comment by AmyFoxFN** [comment]
好的。谢谢你的建议～o(^▽^)o～
