### ISSUE TITLE
[New Feature] 希望cube-scroll-nav组件中的cube-scroll-nav-panel可配置是否显示

### ISSUE THREAD

**Issue by alexnest** [didi/cube-ui#377]
### What problem does this feature solve?
如果需要用cube-scroll-nav这个组件，需要cube-scroll-nav-panel这个组件配合。目前，cube-scroll-nav中有多少个组件列表就会有多少条记录，但有时不想展示某个cube-scroll-nav-panel，希望可以用v-if或者v-show隐藏。cube-scroll-nav-panel新增一个props可以设置display以便控制该cube-scroll-nav-panel是否显示。

### What does the proposed API look like?
```javascript
<cube-scroll-nav @change="changeHandler">
    <cube-scroll-nav-panel :display="false">
        <ul><li></li></ul>
    </cube-scroll-nav-panel>
    <cube-scroll-nav-panel :display="true">
        <ul><li></li></ul>
    </cube-scroll-nav-panel>
</cube-scroll-nav>

<!-- generated by cube-issue-helper. DO NOT REMOVE -->

**Comment by dolymood** [comment]
还是没太明白这个场景。

那如果有panel不显示的话，对应的 nav 导航部分该怎么样的表现 感觉不大好处理吧

而且 这个可以不是panel的显示隐藏，如果这样的话 依旧可以在 panel 里设置 ul 的状态 但是这个会影响结果 就是高度会发生变化 需要每次发生变化的时候重新 refresh 再计算一次才是正确的

**Comment by alexnest** [comment]
使用场景是这样子的：因为一个app页面要填写很多信息，所以用 cube-scroll-nav 对信息做分类方便用户定位到对应需要填写的地方，但不同的类型用户需要填写不同的信息，所以需要根据后台返回的配置信息用v-if或v-show把不需要显示的panel或者panel中li的文本隐藏起来。

尝试改了下代码，在panel加了个v-if="display"的prop，可以隐藏掉panel，但导航依然有那个label，不知如何把 cube-scroll-nav-panel 和 cube-scroll-nav-bar关联起来，如果  cube-scroll-nav-panel 隐藏的话 对应 cube-scroll-nav-bar 的那个类别也隐藏。

**Comment by dolymood** [comment]
如果不需要 构造数据的时候直接删除就好了吧 

还有如果是直接写的 那可以给 panel 加 v-if 就OK了吧

**Comment by alexnest** [comment]
好的，谢谢
