### ISSUE TITLE
是否考虑imagePreview 组件分组预览以及图片的双指缩放或双击放大功能？

### ISSUE THREAD

**Issue by Royalzxl** [didi/cube-ui#378]
是否考虑imagePreview 组件分组预览以及图片的双指缩放或双击放大功能？

**Comment by dolymood** [comment]
分组预览？这个自己实现就可以了吧

然后双指缩放 双击放大缩小 这个已经提供了的功能

**Comment by lxmbetterman** [comment]
@dolymood  请问一下 cube-ui里面是如何实现 双指缩放 双击放大缩小 这样的功能的，有没有文档可以查看。
