### ISSUE TITLE
自定义表单结构checkbox-group报错

### ISSUE THREAD

**Issue by poulSoul** [didi/cube-ui#380]
https://github.com/didi/cube-ui/blob/aacf098dd07dc0101abf0abfc34ffbe3f85c9cda/src/components/checkbox-group/checkbox-group.vue#L24-L27
这个地方缺默认值

**Comment by dolymood** [comment]
checkbox group 是需要自己传入 value 的，即 需要使用 v-model 的

**Comment by poulSoul** [comment]
https://jsfiddle.net/libowen/eywraw8t/536546/ 

这么配置不行么，文档上是可以的

**Comment by poulSoul** [comment]
> checkbox group 是需要自己传入 value 的，即 需要使用 v-model 的
https://jsfiddle.net/libowen/eywraw8t/536546/
这么配置不行么，文档上是可以的

**Comment by dolymood** [comment]
你的 modelKey 'meeting' 不存在 肯定会报错的，而且 meeting 的值应该是数组类型
