### ISSUE TITLE
如何在cube-template初始化后取消rem布局

### ISSUE THREAD

**Issue by vincent2d** [didi/cube-ui#381]
### Version
1.12.8

### Reproduction link
[https://github.com/cube-ui/cube-template/wiki](https://github.com/cube-ui/cube-template/wiki)

### Steps to reproduce
在项目初始化后，由于运营需求必须取消rem布局，采用写死px的方式，请问有办法在不重新搭脚手架的情况下做到吗？谢谢

### What is expected?
取消rem布局

### What is actually happening?
无文档提示

### Dependencies Version
vue: 2.5.21
better-scroll: 1.13.0

**Comment by dolymood** [comment]
你是 vue-cli @3 的还是 vue-cli@2 创建的项目？
