### ISSUE TITLE
checker组件建议增加change类事件

### ISSUE THREAD

**Issue by adongroom** [didi/cube-ui#388]
实际开发中用户的多选操作,可能是希望有规律的选择
比如:1-12节课,用户可能是希望 12, 34,56 是这个是同时选择的
如果有个变动的事件,就可以很容易去做自定义的操作
目前使用你们的组件是通过重新copy了下你们的checker实现,自己做的点击.....很鸡肋

**Comment by dolymood** [comment]
本身是有 input 事件的，而且这种感觉还是可以利用纯数据 改变达到目的的
