### ISSUE TITLE
Popup 弹层建议多加点demo案例(比如内容是多个input,footer部分是确定,取消=>类似modal)

### ISSUE THREAD

**Issue by adongroom** [didi/cube-ui#389]
实际开发中移动端还是有好多东西是通过modal层的那种方式来做的
增加形象的实例,相信大家会更喜欢的

**Comment by dolymood** [comment]
1. 移动Web端最好不要再弹框中输入
2. 如果带了 确定 取消，为何不是 Dialog
3. 如果是自定义需求，肯定需要自己实现，需求有很多，我们肯定覆盖不到
