### ISSUE TITLE
import 'cube-ui'报错

### ISSUE THREAD

**Issue by DevinLwx** [didi/cube-ui#39]
vue官网vue-cli搭建新项目
npm install cube-ui --save 后提示stylus-loader、stylus模块未install
待把这两个modules install 后，还是报错  
1. Module parse failed: Unexpected token (5:18)
    You may need an appropriate loader to handle this file type.
    | export default function parseRenderData(data = {}, events = {}) {
    |   events = parseEvents(events)
    |   const props = { ...data }
    |   const on = {}
    |   for (const name in events) {
    。。。。。。
2. These relative modules were not found:
* ./cubeic.ttf in ./node_modules/css-loader?{"sourceMap":false}!./node_modules/postcss-loader/lib?{"sourceMap":false}!./node_modules/stylus-loader?{"sourceMap":false}!./node_modules/cube-ui/src/common/stylus/index.styl
望大佬看看是什么问题，如何解决

**Comment by dolymood** [comment]
请参照 https://didi.github.io/cube-ui/#/zh-CN/docs/quick-start
