### ISSUE TITLE
from 表单 :field="fields[index]" 不能接受 index吗??

### ISSUE THREAD

**Issue by 348086239** [didi/cube-ui#391]
<cube-form-group>
              <div v-for=" {item,index} in childNum" :key="index">
                <cube-form-item :field="fields[index]"></cube-form-item>
              </div>
            </cube-form-group>

 :field="fields[index]" 没有接受index变量吗??,循环出来input元素

  watch: {
    countValueHistory(newValue, oldValue) {
      for (let i = 0; i < newValue; i++) {
        this.model.chilVauleArr.push("child_name" + i);
        // this.this.fields[i + 3].modelKey = this.model.chilVauleArr[i];
        this.fields.push({
          type: "input",
          modelKey: this.model.chilVauleArr[i],
          label: "子女姓名",
          props: {
            placeholder: "请输入子女姓名"
          },
          rules: {
            required: true
          }
        });
      }
      this.childNum = this.model.chilVauleArr.length;
    }
  },

**Comment by dolymood** [comment]
没明白问题，还请按照issue规范
