### ISSUE TITLE
datepicker 滚动动画结束前无法点击确定获取时间

### ISSUE THREAD

**Issue by JL-Code** [didi/cube-ui#392]
datepicker 滚动动画结束前无法点击确定获取时间，必须等待动画结束才能点击确定按钮，在滚动动画之前点击是无效的。希望能解决这个问题，就算动画没有执行完毕也能通过点击确定 关闭picker

**Comment by dolymood** [comment]
在动画没结束之前 是不知道确定的滚动的日期的，这个目前必须等到结束后点击才有效

而且，动画都没结束 你怎么知道是选到了什么位置，也不大合理吧
