### ISSUE TITLE
[New Feature] <cube-form>组件使用 fields 定义表单字段,参数props 无法设置readonly 属性??

### ISSUE THREAD

**Issue by 348086239** [didi/cube-ui#393]
### What problem does this feature solve?
1.<cube-form>组件支持统一设置 readonly属性.
在需要对保表单只读时,减少花费时间逐一设置,当需要修改时取消掉readonly属性,进行修改表单.
2.<cube-form>组件, 对input 等表单标签所支持的属性, 很多属性不能使用 fields 定义表单字段, 参数props设置. 希望能够完善,支持自带属性的传递.

### What does the proposed API look like?
      fields: [ {
          type: "input",
          modelKey: "loginTel",
          label: "手机",
          props: {
            placeholder: "请输入11位手机号",
            type: "tel",
            maxlength: 11
            readonly: 'true',
            ......//其他属性
          rules: {
            required: true,
            type: "tel",
          }
        } ]

**Comment by dolymood** [comment]
readonly是布尔值，我实验了下 是可以传入的
