### ISSUE TITLE
创建项目时使用的vw，但是使用原有组件时，字体和高度都格外小

### ISSUE THREAD

**Issue by waittingbar** [didi/cube-ui#396]
### Version
1.12.8

### Reproduction link
[https://jsfiddle.net/bz0oLdaj/](https://jsfiddle.net/bz0oLdaj/)

### Steps to reproduce
使用命令创建项目时，选择使用了vw，postcssrc.js中配置： viewportwidth： 750， viewprotHeight: 1334。在一个需要选择时间的页面使用的cube-ui的DatePicker 组件，打开后高度和字体大小都过于小了。

### What is expected?
正常显示

### What is actually happening?
显示太小了

### Dependencies Version
vue: 2.6.0-beta.1
better-scroll: 1.14.0

**Comment by waittingbar** [comment]
我 把 基准值改回原来了， viewportwidth： 375， viewprotHeight: 667，看来你们这个也不能动，麻烦介绍里面提醒一下，免的下一位新手来又遇到这个问题啊..

**Comment by dolymood** [comment]
多谢提醒。
是不能动的，因为两种方式的兼容。
