### ISSUE TITLE
picker、scroll相关滚动的组件在PC端部分浏览器无法使用的bug

### ISSUE THREAD

**Issue by duoremix** [didi/cube-ui#397]
### Version
1.12.9

### Steps to reproduce
在政务微信1.5版本以上的浏览器中使用picker、scroll等组件即可复现，效果为无法滚动

### What is expected?
建议在picker、scroll等组件里，调用better-scroll进行初始化时，设置disablemouse为false。即在pc端同时绑定touch和mouse事件，这样两种场景都能得到满足。

### What is actually happening?
原因是better-scroll使用window对象上是否存在ontouchstart事件来判断浏览器为移动端还是pc端，从而决定把滚动事件绑定到touch事件上还是mouse事件上。
而在政务微信1.5版本上，浏览器的window对象是存在ontouchstart事件的，原因推测可能是需要满足目前可支持触碰的笔记本电脑设备。因此在该环境下使用鼠标操作滚动毫无反应。

### Dependencies Version
vue: 2.6.0-beta.1
better-scroll: 1.14.0

**Comment by dolymood** [comment]
多谢反馈。
那 如果存在的话 但是还不会响应 touch事件吗？而是响应的 mouse事件？那就变得好奇怪了

**Comment by dolymood** [comment]
手机端是会响应 mouse事件的 这个还是有所区分的吧 感觉更多的应该集中在怎么判断 是否是真正的支持 touch 事件上来

**Comment by dolymood** [comment]
如果算issue的话，更多应该属于better scroll的判断问题，在2.0 的bs中我们会考虑这个问题。Thanks
