### ISSUE TITLE
关于recycleListview

### ISSUE THREAD

**Issue by she246** [didi/cube-ui#399]
首先非常感谢didi团队的分享，我是做Android原生开发，最近为了快速开发一个移动web，上手学习vue，h5的列表item的回收与复用一直是我诟病移动web的地方，当看到我们的ui提供了recycleview的时候我非常欣喜，但是认真使用之后感觉有点不完美
1.在模拟加载失败的时候 
   onFetch() {
        console.log('onFetch');
        let items = [];
        var that = this;
        return new Promise((resolve) => {
          setTimeout(() => {
            if (that.currentPageIndex === 2) {
              resolve([]);
              // resolve(false);
              return;
            }
            that.currentPageIndex++;
            for (let i = 0; i < this.size; i++) {
              items.push(this.getItem(this.id++));
            }
            resolve(items);
          }, 500);
        });
      },
resolve([]);或者resolve(false);这时在列表底部向上滑动的时候会不断recycleview组件会不断调用onFetch（）回调，做过一些尝试都没有解决
2.能否与scroll套用，将recycle嵌套在scroll中，我想做上拉刷新，由于上面bug，所以这个我还没做尝试。
3.希望能进一步扩展该组件，丰富其功能
由于我是java+Android studio原生出身，js和vue理解还很一般，如果以后有时间，我一定也会参与recycleview组件的完善
最后还是感激didi团队，感激ustbhuangyi ，我在慕课欠你一笔学费，有空一定补上

**Comment by dolymood** [comment]
第一个问题 px转rem建议直接使用postcss插件做就足够了 也不用mixin就介意
第二个问题 应该需要设置eventpassthrough 为 vertical

**Comment by she246** [comment]
嗯，已经正常了，非常感谢前辈指点

**Comment by yulongwukong** [comment]
RecycleList 这个在安卓手机上快速往回滑动会白屏
