### ISSUE TITLE
下拉刷新和下拉加载的时候用default插槽的时候数据只能刷新一次

### ISSUE THREAD

**Issue by nosillytrying** [didi/cube-ui#40]
#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

### Specify your

* vue version:
* cube-ui version:

**Comment by nosillytrying** [comment]
如果不用默认插槽就不会出现这种情况

**Comment by AmyFoxFN** [comment]
你好，我们的示例中并没发现这个问题。请按Issue规范提供一下test code啊~

**Comment by AmyFoxFN** [comment]
Hi, @nosillytrying~如果没有提供 test code，这个issue暂时会被关闭哦~~如果之后还有问题，你可以随时open啊~
