### ISSUE TITLE
为什么表单类的组件没有返回change事件

### ISSUE THREAD

**Issue by qiantaobao** [didi/cube-ui#403]
### What problem does this feature solve?
在checker组件里面，用户点击另外一个按钮时候，需要返回一个change事件，我们这边需要根据你们返回的事件进行下一步操作。也许你会说为什么不监听v-model绑定的值，然而事实上我们是用的数组渲染的checker组件，每个数组里面都有单独的v-model绑定的值，监听数组中值的变化有点难度，所以我们觉得你们应该在改变数据的时候返回一个事件

### What does the proposed API look like?
methods: {
      onChange() {

      }
    }

**Comment by dolymood** [comment]
目前还没有，可以使用 input 事件。
