### ISSUE TITLE
cube-slide  当图片有4张的时候（3张的时候没发现）   轮播到第一张会有闪白的效果

### ISSUE THREAD

**Issue by whl122677** [didi/cube-ui#404]

**Comment by tank0317** [comment]
在电脑上还是手机上？

**Comment by whl122677** [comment]
我的是oppo 手机  我同事的是华为的  也有这种情况，就是他先发现的

**Comment by tank0317** [comment]
当前的话，你可以给 class `cube-slide-item` 添加如下的样式，看下是否能够解决
```CSS
-webkit-backface-visibility: hidden
-webkit-transform-style: preserve-3d
```
之后我们再看下有没有更好的方式。

**Comment by whl122677** [comment]
嗯  我试了试，还有问题。  不过整体不影响我们先用着。

**Comment by tank0317** [comment]
https://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform

**Comment by tank0317** [comment]
相关问题你可以先参考下：
https://stackoverflow.com/questions/3461441/prevent-flicker-on-webkit-transition-of-webkit-transform

**Comment by tank0317** [comment]
@whl122677 可以尝试下，如果是 andriod，给 slide `options` 添加：`useTransition: false`。
我们这边手机不是必现，你试完，可以反馈下效果。

**Comment by whl122677** [comment]
嗯嗯 可以了  谢谢你
