### ISSUE TITLE
ScrollNav 组件中 prepend前置内容，怎么默认滚动到前置内容，即顶部

### ISSUE THREAD

**Issue by dengshaomin86** [didi/cube-ui#405]
ScrollNav 组件中 prepend前置内容，怎么默认滚动到前置内容，即顶部

**Comment by dolymood** [comment]
还请详细描述下case

**Comment by Barrycca** [comment]
@dolymood 就是这个例子https://didi.github.io/cube-ui/example/#/scroll-nav/side

**Comment by Barrycca** [comment]
想默认 滚动到插槽prepend的位置

**Comment by dolymood** [comment]
如果没有 current 的值 就是在顶部的位置
