### ISSUE TITLE
打包的时候，会打包重复的依赖，better-scroll会被打包多次

### ISSUE THREAD

**Issue by 392417426** [didi/cube-ui#406]
使用vuecli3开发，同时使用slide和scroll组件，打包的时候chunk-vendors文件里会有两个beter-scroll打包进来，请问打包的时候如何去掉重复的依赖

**Comment by dolymood** [comment]
这个是按需的case吧，且是使用的编译后的版本，这种没有办法的，因为单独打包的每份都有bs的依赖了已经。

建议，可以使用后编译或者只能全部引入了。
