### ISSUE TITLE
[New Feature] 关于createAPI在typescript里面使用被tslint警告的问题。

### ISSUE THREAD

**Issue by vtesoho** [didi/cube-ui#407]
### What problem does this feature solve?
在vue里面写this.$create***，tslint检查出来Property '****' does not exist on type '***'，这种能通过写d.ts来通过检查吗？

### What does the proposed API look like?
在vue里面写this.$create***，tslint检查出来Property '****' does not exist on type '***'，这种能通过写d.ts来通过检查吗？

**Comment by dolymood** [comment]
这种需要手工增加 d.ts 来扩展vue的原型方法才可以，类似于

https://github.com/didi/cube-ui/blob/dev/types/cube-ui.d.ts#L119
