### ISSUE TITLE
npm run test 会有提示Vue warn

### ISSUE THREAD

**Issue by necrodiver** [didi/cube-ui#408]
### Version
1.12.10

### Reproduction link
[https://github.com/didi/cube-ui](https://github.com/didi/cube-ui)

### Steps to reproduce
使用官方文档提供的创建步骤:vue init cube-ui/cube-template,不论使用jest还是karma mocha进行单元测试，在初始化项目后,使用:npm run test,都会有提示Vue warn,因为里边默认的有引用cube-button

### What is expected?
能够正确进行单元测试，而不是提示一些错误

### What is actually happening?
ERROR LOG: '[Vue warn]: Unknown custom element: <cube-button> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

(found in <Root>)'

### Dependencies Version
vue: 2.6.6
better-scroll: 1.14.0

**Comment by dolymood** [comment]
目前来看可以参考 

https://stackoverflow.com/questions/49723473/vue-component-register-warning-in-unit-tests-with-element-ui

https://github.com/vuejs/vue-test-utils/issues/31

https://lmiller1990.github.io/vue-testing-handbook/stubbing-components.html#stubbing-components

第一个应该最接近 使用现有的 cube-tempate 的版本

**Comment by dolymood** [comment]
修了 template 部分

https://github.com/cube-ui/cube-template/commit/9065eebeeb8d7cfb99c1eb216095bf194df73c99

**Comment by necrodiver** [comment]
多谢支持，赞一个(〃'▽'〃)
