### ISSUE TITLE
请问如何清空RecycleList？

### ISSUE THREAD

**Issue by mabobj** [didi/cube-ui#415]
### What problem does this feature solve?
改变了查询条件，如何清空列表内容？

### What does the proposed API look like?
1

**Comment by theniceangel** [comment]
目前可以自己手动 vm._data 下面的响应式属性，并且调用 load 方法。不过我们会提供一个 api 来清空列表内容。

**Comment by dolymood** [comment]
1.12.13 增加了 reset API
