### ISSUE TITLE
input被键盘遮挡

### ISSUE THREAD

**Issue by shirleyLsm** [didi/cube-ui#416]
### Version
1.12.11

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/example](https://didi.github.io/cube-ui/#/zh-CN/example)

### Steps to reproduce
1、点击demo中 
https://didi.github.io/cube-ui/#/zh-CN/example 
中form表单
2、选择classic style ，点击input , 谈起键盘，安卓手机该input被遮挡，在ios12.1弹起键盘，关闭后，页面下方出现空白

机型：oppo r11 (大部分安卓下都有该问题)

### What is expected?
安卓手机中input 框不被遮挡
ios中键盘收起，页面样式恢复正常

### What is actually happening?
安卓中input 被遮挡
ios中键盘收起，页面样式乱

### Dependencies Version
vue: 2.6.6
better-scroll: 1.14.0

**Comment by dolymood** [comment]
建议看示例里效果 而非文档中嵌套的示例效果
