### ISSUE TITLE
demo：cube-ui/example/pages/radio.vue有错误

### ISSUE THREAD

**Issue by lienmac** [didi/cube-ui#419]
原代码：
第十行开始：
`
<cube-radio-group v-model="selected4">
     <cube-radio
          v-for="(option, index) in options4"
          :key="index"
          :option="option">
          <img :src="option.src">
        </cube-radio>
      </cube-radio-group>
`

其中v-model="selected4" 应该放在cube-radio上，而不是在cube-radio-group

**Comment by dolymood** [comment]
没有错误，在 1.12.11 版本后是支持写在 group 上的。

然后之前的版本是像文档里一样，写在 radio 上的
