### ISSUE TITLE
cube-scroll滚动时会有抖动和掉帧现象

### ISSUE THREAD

**Issue by w-e-d** [didi/cube-ui#420]
### Version
1.12.1

### Reproduction link
[http://m.xmfp.xadazhihui.cn/help-poor-detail?id=28](http://m.xmfp.xadazhihui.cn/help-poor-detail?id=28)

### Steps to reproduce
使用cube-scroll组件包裹一个有富文本内容的可滚动的页面，使用iPhone X或iPhone 8 Plus用微信浏览器打开上述页面上下滑动时会出现标题说的问题

### What is expected?
希望修复好滚动掉帧的问题

### What is actually happening?
滚动掉帧

### Dependencies Version
vue: 2.5.17
better-scroll: 1.13.0

---
better-scroll的版本是1.13.2

**Comment by dolymood** [comment]
最好不要在scroll中嵌套 输入类元素，问题可能会比较多，我们希望能在下各大版本解决 但是会比较困难，只能调研。

**Comment by w-e-d** [comment]
嗯，好

**Comment by ShuaiShuaiguo** [comment]
@w-e-d 请问这个问题解决了吗？
