### ISSUE TITLE
input组件清空按钮失效

### ISSUE THREAD

**Issue by XiaoMu0712** [didi/cube-ui#421]
### Version
1.12.11

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/input](https://didi.github.io/cube-ui/#/zh-CN/docs/input)

### Steps to reproduce
input组件
设置属性
:clearable="{visible: true, blurHidden: true}"

### What is expected?
实现的效果是清空按钮会在input失去焦点后隐藏，而且清空输入框内容

### What is actually happening?
点击清空按钮后input失去焦点后清空按钮未触发上面的handleClear方法，输入框内容未清空

### Dependencies Version
vue: 2.6.7
better-scroll: 1.14.0

**Comment by dolymood** [comment]
这个在PC上是无效的，在手机上或者PC的移动端模式都是有效的

**Comment by XiaoMu0712** [comment]
> 这个在PC上是无效的，在手机上或者PC的移动端模式都是有效的
我刚刚试了一下，在PC端上chrome的移动端模式这个功能无效，Firefox的有效，谢谢解答

**Comment by dolymood** [comment]
我这边实验是OK的，群里也有人反馈这个问题，同样看了chrome的移动端模式是有效的。
建议群内讨论吧。
