### ISSUE TITLE
Swipe component error:'shrink'of undefined

### ISSUE THREAD

**Issue by mike-hor** [didi/cube-ui#422]
Swipe components use custom slots that cause 'shrink' of undefined if a data source is deleted
The fundamental reason is that the swipe-item component beforeDestroy has not reset the activeIndex of swipe
Solution: Add this. activeIndex = -1 to swipe's removeItem method
so,like this
![tim 20190302160511](https://user-images.githubusercontent.com/17822235/53679236-0afd1600-3d05-11e9-863b-0876e8068a86.png)

**Comment by dolymood** [comment]
Please provide a demo link for this case. Thanks.

**Comment by mike-hor** [comment]
@dolymood 
i found the problem , just i use the vue-cli-plugin-cube-ui  .so the cube-ui ‘s  version is 1.11.2
but in this version,not fixing the problem.
