### ISSUE TITLE
input组件中配置clearable，清空按钮可显示，但是点击没有清空数据

### ISSUE THREAD

**Issue by arrayListTwo** [didi/cube-ui#423]
### Version
1.12.11

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/input](https://didi.github.io/cube-ui/#/zh-CN/docs/input)

### Steps to reproduce
input组件中配置clearable，清空按钮可显示，但是点击没有清空数据   https://didi.github.io/cube-ui/#/zh-CN/docs/input

### What is expected?
input框内数据被清空

### What is actually happening?
input输入框内数据没有动作

### Dependencies Version
vue: 2.6.8
better-scroll: 1.14.0

**Comment by dolymood** [comment]
See https://github.com/didi/cube-ui/issues/421
