### ISSUE TITLE
SegmentPicker is 参数 无法使用 cube-form cube-checkbox-group等

### ISSUE THREAD

**Issue by bigzs** [didi/cube-ui#424]
### Version
1.12.11

### Reproduction link
[https://98yoy9no1p.codesandbox.io/](https://98yoy9no1p.codesandbox.io/)

### Steps to reproduce
点击调用SegmentPicke的按钮按钮报错.

### What is expected?
显示表单或者多选

### What is actually happening?
[Vue warn]: Error in callback for immediate watcher "value": "TypeError: Cannot read property 'concat' of undefined"

### Dependencies Version
vue: 2.6.8
better-scroll: 1.14.0

**Comment by dolymood** [comment]
picker 只支持Picker类 不支持其他组件
这个文档里没写清楚，我们后续会更新下。
