### ISSUE TITLE
[New Feature] 希望能增加Table数据表格功能

### ISSUE THREAD

**Issue by ZeronYuan** [didi/cube-ui#426]
### What problem does this feature solve?
首先感谢开发团队的奉献，希望后续能增加Table功能。

### What does the proposed API look like?
Table功能

**Comment by dolymood** [comment]
目前不考虑。
移动端场景并不适合用表格，样子差异也会比较大，可以根据table遍历循环 应该比较容易实现。

**Comment by ZeronYuan** [comment]
好的   确实有这部分原因

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: doly mood <notifications@github.com>
发送时间: Tuesday, March 12, 2019 10:36:39 AM
收件人: didi/cube-ui
抄送: Zeron; Author
主题: Re: [didi/cube-ui] [New Feature] 希望能增加Table数据表格功能 (#426)


目前不考虑。
移动端场景并不适合用表格，样子差异也会比较大，可以根据table遍历循环 应该比较容易实现。

―
