### ISSUE TITLE
ScrollNav组件导航底部默认多出空白边距

### ISSUE THREAD

**Issue by zhengziyun** [didi/cube-ui#427]
![image](https://user-images.githubusercontent.com/24427587/54107044-fe6a7300-4412-11e9-96a0-c3b24f838c24.png)
在使用ScrollNav组件的时候因为CSS样式原因导致导航底部多出一段空白，希望能优化一下

**Comment by dolymood** [comment]
1.12.13 fixed this issue. Thank you.
