### ISSUE TITLE
异步加载数据时scroll-nav-bar的txts属性不能为空

### ISSUE THREAD

**Issue by coolucifer** [didi/cube-ui#428]
### Version
1.12.13

### Reproduction link
[https://jsfiddle.net/coolucifer/fm4jd2oc/6/](https://jsfiddle.net/coolucifer/fm4jd2oc/6/)

### Steps to reproduce
打开控制台报错
"[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'clientWidth' of undefined"

found in

---> <CubeScrollNavBar>
       <Root>"

### What is expected?
正常运行

### What is actually happening?
控制台报错, 组件不渲染

### Dependencies Version
vue: 2.6.8
better-scroll: 1.14.0

---
异步获取数据时cube-scroll-nav-bar-items的子元素个数为0, 获取元素时出现错误, 设置txts属性后正常.

**Comment by theniceangel** [comment]
组件没有处理异步的逻辑。建议通过 `v-if` 结合 labels 的长度来控制 scroll-nav-bar 组件的渲染。
