### ISSUE TITLE
CascadePicker组件 优化问题

### ISSUE THREAD

**Issue by vincent-cong** [didi/cube-ui#429]
### What problem does this feature solve?
目前的默认值带出 只支持  selectedIndex 的带出，这样就需要通过值来反查出 index放入数组才可以，对于地址这样的大数据来说就不太方便了 

可否直接由值来带出，比如  一开始 动态带出的数据是  上海 上海 浦东新区   弹框的时候 直接指向 上海 上海 浦东新区  

### What does the proposed API look like?
希望可以增加一个默认数据的 参数  

```
如 ：initValue:['上海市'，'上海市'，'浦东新区']
```
来对应目前的 ：
```
selectedIndex：[0,1,1]
```

**Comment by dolymood** [comment]
其实是一样的，区别就是内部需不需要做这个index 的索引计算，建议还是应用来做比较合适。

这部分要看场景，可能不同的场景得到的初始值不同，在应用层也会更好处理。

**Comment by vincent-cong** [comment]
` getAreaIndex(pro, city, area) {
                var arrIndex = [];
                addressData.forEach((item, index) => {
                    if (item.text === pro) {
                        arrIndex.push(index);
                        item.children.forEach((item_city, index_city) => {
                            if (item_city.text === city) {
                                arrIndex.push(index_city)
                                if (area) {
                                    item_city.children.forEach((item_area, index_area) => {
                                        if (item_area.text === area) {
                                            arrIndex.push(index_area)
                                        }
                                    })
                                }
                            }
                        })
                    }
                })
            },`
好吧 
自己写了一个方法 仅供大家参考；
如果还有更好的，请大佬指正。
