### ISSUE TITLE
横向的slide嵌套横向的scroll发生事件冒泡

### ISSUE THREAD

**Issue by FliexLin** [didi/cube-ui#430]
### Version
1.12.13

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/example](https://didi.github.io/cube-ui/#/zh-CN/example)

### Steps to reproduce
1.项目地址：https://hjkf.huijintech.com.cn/channel/micromall/#/Home
2.首页内层嵌套了横向的scroll，tab切换本来想写成slide组件，但是会出现一起滚动的问题，
3.希望能跟scroll组件嵌套横向滚动

### What is expected?
希望能跟scroll组件嵌套横向滚动

### What is actually happening?
横向的slide嵌套横向的scroll会有事件冒泡，scroll横向滚动的同时会触发slide滚动

### Dependencies Version
vue: 2.6.8
better-scroll: 1.15.0

**Comment by dolymood** [comment]
如果想要不触发 slide 那就可以设置 slide 的options 中，阻止冒泡即可。

**Comment by FliexLin** [comment]
你说的我也试过了但是项目应用场景比较复杂,我想问下有没有其他办法做到像scroll嵌套,内层滚动触发外层滚动

**Comment by dolymood** [comment]
那可以选择参考嵌套scroll的逻辑，对BetterScroll实例本身做状态控制。
但是还是建议简化交互，不建议存在嵌套场景。

**Comment by FliexLin** [comment]
好的,我试试看,谢谢
