### ISSUE TITLE
主题设置不生效

### ISSUE THREAD

**Issue by spiroo** [didi/cube-ui#436]
使用vue-cli3创建项目，然后使用vue add cube-ui添加cube，使用后编辑、主题；配置如：
// 第三方插件配置
  pluginOptions: {
    'cube-ui': {
      postCompile: true,
      theme: true
    }
  },

  css: {
    loaderOptions: {
      stylus: {
        'resolve url': true,
        'import': [
          './src/theme'
        ]
      }
    }
  }

在theme.styl中
@require "~cube-ui/src/common/stylus/var/color.styl"

$m-primary-bg = #00f

/// primary
$btn-primary-color := $color-white
$btn-primary-bgc := $m-primary-bg
$btn-primary-bdc := $m-primary-bg
$btn-primary-active-bgc := $m-primary-bg
$btn-primary-active-bdc := $m-primary-bg

使用<cube-button :primary="true">Primary Button</cube-button>，仍然显示橙色主题，请问如何设置？
![image](https://user-images.githubusercontent.com/7858201/54614421-54848980-4a97-11e9-9814-36fc0613015b.png)

**Comment by cuijing1031** [comment]
按照你的配置设置了一下，可以生效，没有发现你说的问题。

vue-cli:3.5.0。
创建项目过程 vue create xxx ，vue add cube-ui

**Comment by spiroo** [comment]
@cuijing1031 刚试了一下，只有在vue-cli创建项目时，选择css-processor，必须使用stylus，才能生效，能支持其他预编译语言吗，比如less？

**Comment by dolymood** [comment]
这样的话 只能选择共用 stylus 和 less 了 修改变量必须是 stylus

**Comment by yohanceli** [comment]
我设置主题的时候也遇到了不生效的问题，设置自定义变量的时候，把`=`前面的`:`删掉就生效了
