### ISSUE TITLE
[New Feature] support rem

### ISSUE THREAD

**Issue by dolymood** [didi/cube-ui#44]
### A feature or reporting a bug?
Feature

### What is the current behavior?
If used [postcss-px2rem](https://www.npmjs.com/package/postcss-px2rem), some components or behaviors will be not perfect.

### What is the expected behavior?
Support rem.

### Specify your

* vue version: 2.5.2
* cube-ui version: 1.1.1

**Comment by dolymood** [comment]
Only postcss-px2rem remUnit=750/10/2=37.5

**Comment by dolymood** [comment]
Only support viewport width = device-width, like https://github.com/amfe/lib-flexible 2.0

**Comment by ChineseEngineer** [comment]
我们ui是750规范的 怎么办？
