### ISSUE TITLE
IE11下 出现  SCRIPT1010: 缺少标识符

### ISSUE THREAD

**Issue by bigzs** [didi/cube-ui#441]
### Version
1.12.13

### Reproduction link
[http://212.64.25.100:9102](http://212.64.25.100:9102)

### Steps to reproduce
将cube-ui 引入项目 , 打开首页不显示, 控制台报错. 去掉就好了.已经babel .

### What is expected?
IE11下显示出页面

### What is actually happening?
IE11下没有显示页面

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
我们是移动端的组件库，PC的 IE11 不在兼容范围内。也不适合用在PC上的，组件交互都不适用的。

**Comment by bigzs** [comment]
问题是我PC 移动端都打包在一起,把你们剔除就好了,加上cubeui就报错

**Comment by dolymood** [comment]
我们也实验下吧，理论上是不会有问题才对

**Comment by maoamao** [comment]
我们按照你所描述的情况，并没有复现出问题，可以提供一个项目供我们排查。

**Comment by maoamao** [comment]
我们按照你所描述的情况，并没有复现出问题，可以提供一个项目供我们排查。

**Comment by bigzs** [comment]
> 我们按照你所描述的情况，并没有复现出问题，可以提供一个项目供我们排查。

https://github.com/bigzs/cube-ui-bug.git

**Comment by bigzs** [comment]
没人吗？

**Comment by dolymood** [comment]
节后看吧 @maoamao
