### ISSUE TITLE
微信浏览器 安卓手机 upload组件上传会出现闪退的问题

### ISSUE THREAD

**Issue by carol95** [didi/cube-ui#445]
有没有人出现过这样的问题  微信浏览器 安卓手机 upload组件上传图片会出现闪退

**Comment by dolymood** [comment]
upload用的原生input实现，如果闪退的话，应该自己写也会闪退 可能开发者自身根据环境有降级方案才可以。

目前了解到的是，会有一些机型根本拿不到file对象也是有可能的。
