### ISSUE TITLE
ScrollNav 组件按照 demo 实现，导航可滚动但底部内容不联动

### ISSUE THREAD

**Issue by jack-don** [didi/cube-ui#446]

**Comment by 531431988** [comment]
我也遇到

**Comment by jack-don** [comment]
> 我也遇到

沟通下，有没有好的解决方案。

**Comment by jack-don** [comment]
> 我也遇到

沟通下，有没有好的解决方案。

**Comment by dolymood** [comment]
还请提供下复现线上 case

**Comment by 531431988** [comment]
怎么提供，官方文档的源码搞过去，直接就不行，也不报错

**Comment by jack-don** [comment]
> 还请提供下复现线上 case

跟demo一模一样

**Comment by 531431988** [comment]
表示不服，刚又复制了一份，卧槽效果出来了

**Comment by jack-don** [comment]
> 表示不服，刚又复制了一份，卧槽效果出来了

差在哪里了

**Comment by 531431988** [comment]
哪都没差，只是新建了一个页面，以前是其他页面有其他东西

**Comment by jack-don** [comment]
> 哪都没差，只是新建了一个页面，以前是其他页面有其他东西

v-cli 还是 引用的vue.js?

**Comment by 531431988** [comment]
cli3.0

**Comment by wangyujie1207** [comment]
> cli3.0

我直接复制的demo,将demo当根入口,还是不能联动.. 也是cli3.0

**Comment by lxmbetterman** [comment]
没人解释一下吗？怎么解决？

**Comment by wangyujie1207** [comment]
异步数据需要v-if

**Comment by jacksplwxy** [comment]
@dolymood 这么多人报问题，不给个回复就这样关了么？

**Comment by aichi2006** [comment]
这个是样式问题，给scrollNav包个父级div，给个height 就解决了  看看better-scroll的文档

**Comment by huyaxiong** [comment]
> 这个是样式问题，给scrollNav包个父级div，给个height 就解决了 看看better-scroll的文档

亲测有效 谢谢
