### ISSUE TITLE
[New Feature] 关于checkbox组件的input事件

### ISSUE THREAD

**Issue by suozhao** [didi/cube-ui#448]
### What problem does this feature solve?
最好能在文档上给补充上,费了老半天劲才找到

### What does the proposed API look like?
checkbox组件的input事件

**Comment by dolymood** [comment]
支持 v-model 的所有相关都会添加 input 事件文档 @hu0950

**Comment by dolymood** [comment]
https://github.com/didi/cube-ui/pull/468
