### ISSUE TITLE
cube-scroll如何获取滚动的初始位置startX

### ISSUE THREAD

**Issue by FliexLin** [didi/cube-ui#451]
### Version
1.12.14

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/scroll](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll)

### Steps to reproduce
https://didi.github.io/cube-ui/#/zh-CN/docs/scroll

### What is expected?
cube-scroll如何获取滚动的初始位置startX

### What is actually happening?
cube-scroll获取滚动的初始位置startX

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
cube-scroll如何获取滚动的初始位置startX

**Comment by dolymood** [comment]
取到 bs 实例就可以

refs.scroll.scroll 就是bs 实例
