### ISSUE TITLE
scroll组件在滚动中被隐藏会无限触发scroll事件，且参数为{x: NaN, y: NaN}

### ISSUE THREAD

**Issue by whm-js** [didi/cube-ui#457]

**Comment by tank0317** [comment]
可以尝试在隐藏的时候，设置 `<scroll组件>.scroll.isInTransition = false`

**Comment by tank0317** [comment]
底层 better-scroll 会在惯性滚动过程中不断派发 scroll 事件，同时通过监听原生的 transitionend 事件，在 transition 结束的时候停止派发 scroll 事件。

由于你隐藏了组件，导致浏览器不再派发 transitionend 事件

所以会出现无限派发 scroll 的现象。

**Comment by originalix** [comment]
虽然没有使用这个 UI 库，但是谢谢 @tank0317 的对于 better-scroll 的问题解答，帮助我解决了问题
