### ISSUE TITLE
[New Feature] cube-radio-group,cube-switch,CheckboxGroup,select组件希望可以加点击事件，用于统计用户行为

### ISSUE THREAD

**Issue by gmzd2008** [didi/cube-ui#458]
### What problem does this feature solve?
为了统计用户行为，需要统计点击了按钮，并获取值，@input 可以获取 用户点击了按钮并获取值，但是直接通过修改v-model 绑定的变量值，也会触发 input 这不是用户点击触发的值改变。
希望加一个独立事件可以监听用户点击并获取值

### What does the proposed API look like?
```html
<template>
    <label class="cube-radio-wrap" :class="_wrapClass" @click="clickHandle"></label>
<template>
```
```javascript
methods:{
    clickHandle(){
        this.$emit("click", checked);
    }
}
```

**Comment by dolymood** [comment]
先使用 click.native 吧，后续2.0我们统一考虑下
