### ISSUE TITLE
[New Feature] 日期选择是否可以设计为单例模式

### ISSUE THREAD

**Issue by yeyan1996** [didi/cube-ui#462]
### What problem does this feature solve?
如果同一个页面需要多个日期选择器,类似起止日期,,目前是不是只能通过$createDatePicker来创建多个实例,然后每个实例再分别配置不同的配置项来执行不同的onSelect函数?

文档上好像也并没有说明多个日期选择器该如何使用的场景

### What does the proposed API look like?
可以考虑将日期选择器变成单例模式,给show方法传入onSelect,onCancel的回调函数

this.datePicker =  this.$createDatePicker({
                    title: '选择日期',
                    min: new Date(2000, 1, 1),
                    max: new Date(2050, 12, 31),
                    value: new Date(),
                })

 this.datePicker.show(onSelect,onCancel)

**Comment by dolymood** [comment]
如果是多个的话 还是建议多个实例比较好，避免相互关联 影响
