### ISSUE TITLE
radio文档中的radio-group的默认插槽案例代码错误

### ISSUE THREAD

**Issue by yeyan1996** [didi/cube-ui#463]
### Version
1.12.15

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/radio](https://didi.github.io/cube-ui/#/zh-CN/docs/radio)

### Steps to reproduce
打开官网即可~

### What is expected?
```
<cube-radio-group v-model="selected4">
  <cube-radio
    v-for="(option, index) in options4"
    :key="index"
    :option="option">
    <img :src="option.src" />
  </cube-radio>
</cube-radio-group>
```

### What is actually happening?
```
<cube-radio-group>
  <cube-radio
    v-for="(option, index) in options4"
    :key="index"
    :option="option"
    v-model="selected4">
    <img :src="option.src" />
  </cube-radio>
</cube-radio-group>
```

---
在使用官网的默认插槽的案例,发现在cube-radio中写v-model的值在初始化的时候,始终是undefined,最后追溯到源码,我发现`src/components/radio/radio.vue:49`将this.radioValue = radioGroup.radioValue,而radioGroup.radioValue因为没有在cube-radio-group中定义所以是undefined,所以this.radioValue会变成undefined,并且在data中将radioValue = thi.value,所以就会导致cube-radio的v-model在初始化的时候始终是undefined

**Comment by dolymood** [comment]
这个 https://github.com/didi/cube-ui/issues/419 ？

**Comment by dolymood** [comment]
新版本应该两种写法都支持的。
