### ISSUE TITLE
[New Feature] 如何在js文件中调用Toast？

### ISSUE THREAD

**Issue by WormGirl** [didi/cube-ui#467]
### What problem does this feature solve?
我在项目中使用Vue.$createToast()报错，请问应该如何调用，import {Toast} from 'cube-ui' Toast这样调用也不对，报Toast不是一个方法，想知道正确的调用方式

### What does the proposed API look like?
import {Toast} from 'cube-ui'，然后Toast()可以直接调用

**Comment by WormGirl** [comment]
这样可以调用，这是正确方式么？
```
import { Toast } from 'cube-ui'
Toast.$create({
     time: 1000,
     txt: error.message,
     type: 'txt'
 }).show()
```

**Comment by tank0317** [comment]
是不是缺了一句 Vue.use(Toast)

发自我的 iPhone

在 2019年4月23日，下午12:12，lady Liu <notifications@github.com<mailto:notifications@github.com>> 写道：


这样可以调用，这是正确方式么？

import { Toast } from 'cube-ui'
Toast.$create({
     time: 1000,
     txt: error.message,
     type: 'txt'
 }).show()

**Comment by WormGirl** [comment]
我使用了部分引入组件，在cube-ui.js中全局注册过该组件，只是不知道怎么在.js文件里调用

**Comment by tank0317** [comment]
确定你上面的语句，是在 cube-ui.js 执行之后，执行的吗

**Comment by WormGirl** [comment]
是的，这样是不是就没问题了

**Comment by tank0317** [comment]
？？？

确定你上面的语句，是在 cube-ui.js 执行的，那就不会有问题。

所以你那现在还有问题吗

**Comment by WormGirl** [comment]
```js
import Vue from 'vue'
import './cube-ui'
import App from './App.vue'
import router from './router'
import store from './store'
import 'amfe-flexible'
import '@/style/common.scss'
```
我在store.js里使用了Toast,目前是没问题的，有问题我在提，谢谢

**Comment by suchenglin2017** [comment]
`
import { Toast } from 'cube-ui'

Vue.use(Toast)

Toast.$create({
  txt: 'Loading...',
  mask: true
}).show()
`
js文件调用Toast，报以下错误，请问知道为什么吗？
./node_modules/cube-ui/src/common/stylus/index.stylModule build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):ModuleNotFoundError: Module not found: Error: Can't resolve './cubeic.ttf' in 'E:\code\fe-m-supplier\node_modules\cube-ui\src\common\stylus'    at factory.create (E:\code\fe-m-supplier\node_modules\webpack\lib\Compilation.js:888:10)    at factory (E:\code\fe-m-supplier\node_modules\webpack\lib\NormalModuleFactory.js:401:22)    at resolver (E:\code\fe-m-supplier\node_modules\webpack\lib\NormalModuleFactory.js:130:21)    at asyncLib.parallel (E:\code\fe-m-supplier\node_modules\webpack\lib\NormalModuleFactory.js:224:22)    at E:\code\fe-m-supplier\node_modules\neo-async\async.js:2830:7    at E:\code\fe-m-supplier\node_modules\neo-async\async.js:6877:13    at normalResolver.resolve (E:\code\fe-m-supplier\node_modules\webpack\lib\NormalModuleFactory.js:214:25)    at doResolve (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\Resolver.js:184:12)    at hook.callAsync (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\Resolver.js:238:5)    at _fn0 (eval at create (E:\code\fe-m-supplier\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)    at resolver.doResolve (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)    at hook.callAsync (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\Resolver.js:238:5)    at _fn0 (eval at create (E:\code\fe-m-supplier\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)    at hook.callAsync (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\Resolver.js:238:5)    at _fn0 (eval at create (E:\code\fe-m-supplier\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)    at resolver.doResolve (E:\code\fe-m-supplier\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)

**Comment by dolymood** [comment]
快速上手看下，stylus options

**Comment by dolymood** [comment]
快速上手看下，stylus options

**Comment by WormGirl** [comment]
type: 'txt',我指定了type所以没报错，你的没指定应该不是纯文本形式，看提示的意思是toast字体图标路径有问题
