### ISSUE TITLE
[New Feature] 组件【ImagePreview】期望可添加个option 可以直接修改mask的透明度

### ISSUE THREAD

**Issue by xiaoyexiang** [didi/cube-ui#472]
### What problem does this feature solve?
如题，组件基本满足功能使用，也不想造轮子了，万恶的产品和设计师非要背景全黑无透明！？～？！

我能怎么办，我也很绝望啊！我调整还是不太优雅，毕竟还是组件提供可设置option 或者 暴露方法调整。

### What does the proposed API look like?

        this.$createImagePreview({
          imgs: this.imagePreviewUrls,
          initialIndex: this.imagePreviewIndex,
          loop: false,
          speed: 500,
          maskOpacity: 1,  // 可设置option
          onChange: (i) => {
            this.imagePreviewIndex = i
          },
          onHide: () => {
            console.log('hide')
          }
        }).show()

**Comment by theniceangel** [comment]
样式覆盖即可。
