### ISSUE TITLE
关于ImagePreview 组件，手势滑动放大缩小,双击放大的问题。

### ISSUE THREAD

**Issue by lxmbetterman** [didi/cube-ui#474]
请教一下，ImagePreview是如何实现h5页面内对手势滑动的检测，以及ImagePreview中图片放大缩小的实现机制是什么？这对我来说是一个很难的问题，能否指点一下

附 :ImagePreview官方示例的图片链接失效了，请更换

**Comment by shanger** [comment]
缩放是基于[better-scroll](https://github.com/ustbhuangyi/better-scroll)实现的，可以去看看源码。

**Comment by dolymood** [comment]
多谢反馈，已更新

**Comment by lxmbetterman** [comment]
> 多谢反馈，已更新

很棒的框架，受益了！
