### ISSUE TITLE
feature: scroll-nav-bar添加点击事件的触发

### ISSUE THREAD

**Issue by kanweiwei** [didi/cube-ui#475]
feature

https://github.com/didi/cube-ui/blob/6696ed08664a98a4fcbe2d5e114244f4c5fe07a9/src/components/scroll-nav/scroll-nav.vue#L18

scroll-nav scroll-nav-bar 需要添加点击事件的触发，有时候需要在点击nav-bar的时候做一些操作，现在只有一个current属性，只能知道当前哪个bar是active。

**Comment by dolymood** [comment]
点击会触发 active 的改变，这个就可以根据这个做对应的逻辑处理就可以。

**Comment by kanweiwei** [comment]
@dolymood  active不变的情况下，就不行了，我需要在active不变的情况，点击当前的nav bar也要有触发的动作，监听active没有用。

**Comment by dolymood** [comment]
你的场景比较特殊，目前为了满足需求的话，可以考虑使用自定义插槽实现。
