### ISSUE TITLE
Upload 选择图片调起系统相册单选问题 设置 multiple 为 false 后,在 iOS 上打开相册仍可多选,android上无此问题 

### ISSUE THREAD

**Issue by swants** [didi/cube-ui#477]
### Version
1.12.15

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/upload](https://didi.github.io/cube-ui/#/zh-CN/docs/upload)

### Steps to reproduce
Upload 选择图片调起系统相册单选问题 设置 multiple 为 false 后,在 iOS 上打开相册仍可多选,android上无此问题 

### What is expected?
设置 multiple 为 false 后,在 iOS 系统相册选择照片为单选

### What is actually happening?
设置 multiple 为 false 后,在 iOS 系统相册选择照片仍为多选

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这个在移动端是无法控制的，只能自己逻辑控制了，移动端实现比较乱一些。

**Comment by swants** [comment]
> 这个在移动端是无法控制的，只能自己逻辑控制了，移动端实现比较乱一些。

可以简略介绍下自己怎么逻辑控制吗? 谢谢!

**Comment by dolymood** [comment]
走文件过滤的逻辑即可。

**Comment by tanxiaoj** [comment]
文件过滤不是过滤文件类型吗，没发现能过滤照片选中数量

**Comment by dolymood** [comment]
参考文档 files-added 事件，添加 file ignore
