### ISSUE TITLE
indexList without title property may cause some problem

### ISSUE THREAD

**Issue by litong534** [didi/cube-ui#48]
### A feature or reporting a bug?
Bug

### What is the current behavior?
IndexList component without title property may cause the position of uppercase bar unpredictable,also when tapping the fast navigation bar , for example, I should tap below the letter C to choose C.

### What is the expected behavior?
Running as the demo shows to me.

### How to reproduce the current behavior (if this is a bug)?
Not declaring the title property

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js
<cube-index-list :data="cityData" @select="selectItem" ></cube-index-list>
```

### Specify your

* vue version: 2.5.2
* cube-ui version: 1.1.0

**Comment by AmyFoxFN** [comment]
[commit: get actual title hight](https://github.com/didi/cube-ui/commit/f289263be615f3b7e6105d088ff1d8dcad53eb71) will fix this issue. Please wait our next version, published tomorrow perhaps ~
