### ISSUE TITLE
[New Feature] actionSheet 组件的的 active 配置不能动态的修改

### ISSUE THREAD

**Issue by zhugy-cn** [didi/cube-ui#480]
### What problem does this feature solve?
每次都需要调用 this.$createActionSheet 重新创建来修改 active 的值，希望能动态的修改 active 配置
    showPicker() {
      if (!this.sendGoodTypePicker) {
        let data = [{
          content: '送货',
          id: 1,
        }, {
          content: '送货上门',
          id: 2,
        }, {
          content: '送货上楼',
          id: 3,
        }, {
          content: '不需要送货',
          id: 4,
        }];
        this.sendGoodTypePicker = this.$createActionSheet({
          // 希望能动态的修改 active 的，不然每次都需要重新调用 this.$createActionSheet
          active: -1,
          data,
          onSelect: (item, index) => {
            const { content, id } = item;
            this.send_good_type = content;
            this.formData.send_good_type = id;
          },
        }).show()
      }
      // this.sendGoodTypePicker.active = 2
      this.sendGoodTypePicker.show()
    }

### What does the proposed API look like?
this.sendGoodTypePicker.setActive()

**Comment by dolymood** [comment]
参考 https://didi.github.io/cube-ui/#/zh-CN/docs/create-api 或者 https://github.com/cube-ui/vue-create-api/blob/master/README_zh-CN.md

核心就是可以：

```html
<script>
export default {
data() {
  return {active: -1}
},
methods: {
showX() {
this.$createActionSheet({
  $props: {active:'active', //...}
}).show()
}
}
}
</script>
```

**Comment by zhangyanan0525** [comment]
> 参考 https://didi.github.io/cube-ui/#/zh-CN/docs/create-api 或者 https://github.com/cube-ui/vue-create-api/blob/master/README_zh-CN.md
> 
> 核心就是可以：
> 
> ```
> <script>
> export default {
> data() {
>   return {active: -1}
> },
> methods: {
> showX() {
> this.$createActionSheet({
>   $props: {active:'active', //...}
> }).show()
> }
> }
> }
> </script>
> ```


## 版本 
 "cube-ui": "~1.12.15",
## 代码描述
![image](https://user-images.githubusercontent.com/20139082/64245481-91f1ac00-cf3d-11e9-84fc-44558232268a.png)
## 结果
并没有添加高亮

**Comment by dolymood** [comment]
active: 'pickerFaAtive' 类似这样的
