### ISSUE TITLE
scrollnav的滚动 在div标签中会失效

### ISSUE THREAD

**Issue by XueiuR** [didi/cube-ui#483]
### Version
1.12.19

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
- 直接用[cube-ui示例代码](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll-nav#cube-%E7%A4%BA%E4%BE%8B-anchor)测试就好

### What is expected?
正常应该是点击导航栏会定位到对应的内容上

### What is actually happening?
并无任何反应

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
当在<cube-scroll-nav @change="changeHandler">外面加一个<div>标签后，点击上方导航栏将不会跳转到对应内容的锚点上

**Comment by dolymood** [comment]
依赖于 样式， 需要有固定高度，因为 height 100%

**Comment by Hxiaotong** [comment]
I also fell into this pit.
