### ISSUE TITLE
scroll组件初始化页面时不能滚动

### ISSUE THREAD

**Issue by applelihongzhi** [didi/cube-ui#484]

**Comment by EvanSpring** [comment]
刷新后才能滚动说明你的css样式设置没有问题，问题应该出在数据加载的时期，必须等到页面获取到数据后并且dom渲染完毕，better-scroll插件计算出了容器高度/宽度超出了父容器，才会滚动。查看获取数据的生命周期函数的使用，可以在created或者mounted钩子里调用接口获取数据，然后在this.$nextTick回调里初始化数据，也可以用setTimeout(()=>{},200)；
