### ISSUE TITLE
scroll组件中的options配置项中click设置true或者false，均会派发constructed属性，且都是true，无法区分

### ISSUE THREAD

**Issue by EvanSpring** [didi/cube-ui#485]
### Version
1.12.15

### Reproduction link
[https://github.com/cube-ui/cube-application-guide](https://github.com/cube-ui/cube-application-guide)

### Steps to reproduce
这个是官方提供的教程地址，代码运行后在MatchList.vue组件内的clickItem方法中添加一个event参数并且对应的dom内改为@click="clickItem(index,$event)"，如下：
clickItem(index,event){console.log(event._constructed)},当该组件内部的scroll组件配置项options: {click: true}时，点击事件触发两次输出，且都是true。当设置options:{click:false}时,点击事件触发一次输出，且为true，无法区分到底哪个是better-scroll组件派发的事件，不解决这个问题，打包app时点击事件会出现不起作用的情况。

### What is expected?
options: {click:false}时不再是better-scroll派发的事件，event._constructed=false,否则options: {
click:true}时是由better-scroll派发的事件，event._constructed=true

### What is actually happening?
无论options: {}中的click选项是否为true和false,event._constructed属性均为true,和better-scroll官方文档描述的不符。

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
之前使用better-scroll插件打包app时就遇到一个问题，better-scroll插件默认阻止了浏览器的原生 click 事件，click:false/true配置项必须设置为true,否则打包后，app点击事件无法响应。

**Comment by dolymood** [comment]
那个 click 是 存在嵌套的场景的，click false的时候 是因为 slide里派发了 click
click false 因为存在两层 所以会派发两次click事件
