### ISSUE TITLE
cube-checker外层增加点击事件，iOS微信浏览器点击事件失效，安卓正常

### ISSUE THREAD

**Issue by andyqier88** [didi/cube-ui#487]
### Version
1.12.1

### Reproduction link
[https://codepen.io/anon/pen/arJjQG](https://codepen.io/anon/pen/arJjQG)

### Steps to reproduce
1.根据社保（有，无）去请求不同的数据
2.在iOS微信浏览器可以正常切换，但点击事件失效
3.安卓正常

### What is expected?
iOS微信浏览器可以点击请求数据

### What is actually happening?
iOS微信浏览器click事件失效

### Dependencies Version
vue: 2.5.2
better-scroll: 1.15.0

---
<div class="wbk-item">
            <div class="social-sec">社保</div>
            <div class="right-item social-sec-check" @click="GetHealthRenewalInfoBysoc">
              <cube-checker v-model="socialValue" :options="options" type="radio"/>
           </div>
</div>
vue中的data设置:
options: [
        {
          value: 1,
          text: '有',
        },
        {
          value: 0,
          text: '无',
        },
      ],

**Comment by dolymood** [comment]
本地实验 没问题，目测其他的收到了影响

**Comment by andyqier88** [comment]
嗯，找到原因了
