### ISSUE TITLE
scroll组件中的元素不响应touch事件

### ISSUE THREAD

**Issue by HZzzzy** [didi/cube-ui#490]
![image](https://user-images.githubusercontent.com/18050675/58315241-bec4fc00-7e43-11e9-9096-d2769e4f3343.png)
在scroll中的子元素上添加touch事件，PC浏览器上可以正常使用，在手机上不响应

**Comment by dolymood** [comment]
还请提供最小复现链接

**Comment by HZzzzy** [comment]
> 还请提供最小复现链接

由于没有固定的外网地址，这里分别录了在微信开发者工具中操作和在微信中操作的视频
![wechat_dev_tool](https://user-images.githubusercontent.com/18050675/58463934-5c336f00-8167-11e9-9287-b78ceeccc398.gif)
![wechat_mobile_browser](https://user-images.githubusercontent.com/18050675/58463940-5f2e5f80-8167-11e9-9e36-0238dca92aac.gif)

**Comment by dolymood** [comment]
复现链接并不是指的你们项目的链接，而是把核心部分模拟实现，但是是有问题的一个 链接就可以，可以是一个小git仓库，也可以是线上的一个demo地址

**Comment by HZzzzy** [comment]
> 复现链接并不是指的你们项目的链接，而是把核心部分模拟实现，但是是有问题的一个 链接就可以，可以是一个小git仓库，也可以是线上的一个demo地址

https://github.com/HZzzzy/scroll-test.git  demo地址

**Comment by dolymood** [comment]
你的demo试验有效

**Comment by HZzzzy** [comment]
> 你的demo试验有效

在您那边手机上长按列表每次都有效？我在手机上测试多次点按才会偶尔响应一次，测试机型华为荣耀9

**Comment by dolymood** [comment]
touch事件是有效的，长安逻辑自己参考成熟库实现吧

**Comment by HZzzzy** [comment]
> touch事件是有效的，长安逻辑自己参考成熟库实现吧

已验证，确实是touch逻辑处理的问题，但是在PC端浏览器使用没有问题啊

**Comment by citrusjunoss** [comment]
> > touch事件是有效的，长安逻辑自己参考成熟库实现吧
> 
> 已验证，确实是touch逻辑处理的问题，但是在PC端浏览器使用没有问题啊

我也发现了, input 在scroll (移动端)里无法触发失焦事件, PC 可以

**Comment by citrusjunoss** [comment]
是better scroll的问题

> touch事件是有效的，长安逻辑自己参考成熟库实现吧

是better scroll 的问题哦, 默认禁用了touch 事件

![image](https://user-images.githubusercontent.com/18432488/64590281-c6e87d80-d3d9-11e9-9037-e2a5154e9a49.png)
