### ISSUE TITLE
popup与dialog在scroll上表现不同

### ISSUE THREAD

**Issue by HZzzzy** [didi/cube-ui#491]
在scroll上使用popup,遮罩层没有阻止事件穿透，底下的内容仍然可以滚动或者点击，且popup的内容部分是相对scroll部分的全部高度居中，而不是相对于可见部分居中
，但dialog的遮罩层可以阻止下层元素的事件被触发，且dialog内容始终在可见区域居中

![GIF](https://user-images.githubusercontent.com/18050675/58528055-b2f08580-8207-11e9-92ee-94780dbdb765.gif)
![GIF2](https://user-images.githubusercontent.com/18050675/58528060-c0a60b00-8207-11e9-836f-6a1860ba8716.gif)

**Comment by dolymood** [comment]
弹出层类 使用 crateAPI 实例化

**Comment by dolymood** [comment]
popup组件也一样，不过建议 popup作为基础组件，而不是直接使用
