### ISSUE TITLE
Fastclick caused a click problem on ios12

### ISSUE THREAD

**Issue by AYWK** [didi/cube-ui#492]
### Version
1.12.19

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/example](https://didi.github.io/cube-ui/#/zh-CN/example)

### Steps to reproduce
When you use input or textarea above ios12, quick clicks don't evoke the keyboard. This is because ios12 updates a problem caused by scrolling smoothness, and I don't quite understand why there is a need to apply fastclick on ios10. Hope to answer, thank you.

### What is expected?
Quick single click to evoke the keyboard

### What is actually happening?
Quick single click does not evoke the keyboard

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
This https://github.com/ftlabs/fastclick/issues/549 ?

**Comment by AYWK** [comment]
no,it does'nt work.
