### ISSUE TITLE
[New Feature] 请教一下，按需引入，<cube-sticky-ele/>这个组件怎么样按需引入

### ISSUE THREAD

**Issue by snnairow** [didi/cube-ui#493]
### What problem does this feature solve?
我想按需引入Sticky组件。发现Sticky可以引入，但是<cube-sticky-ele/>这个组件不知道怎么样按需引入

### What does the proposed API look like?
<cube-sticky-ele/>这个组件怎么样按需引入

**Comment by dolymood** [comment]
如果使用use的方式，Sticky就够了，ele是会自动注册的。

其他 Sticky.Ele 就是 ele 组件
