### ISSUE TITLE
cube-form表单内部的button怎么添加事件

### ISSUE THREAD

**Issue by trayvon2017** [didi/cube-ui#494]
`
fields: [
              {
                type: 'button',
                label: '登录',
                props: {
                  icon: 'cubeic-right'
                },
                events: {
                  click: function () {
                    alert(123)
                  }
                }
              },
...
]
`
请问cube-form中的类型为button的filed如何触发事件,我按照上面的方式去写,没办法触发

**Comment by dolymood** [comment]
最新版本吗？

**Comment by trayvon2017** [comment]
"cube-ui": "^1.12.19"

**Comment by dolymood** [comment]
https://github.com/didi/cube-ui/commit/2fc8f3c7e039b04e30048b01e23e1e111546f595#diff-6e9d084d7ad7a8704faab2b2be7f714f

1.12.20 这个版本就好了
