### ISSUE TITLE
封装 axios 的 request.js 中如何添加toast

### ISSUE THREAD

**Issue by frandior** [didi/cube-ui#495]
import axios from 'axios'
import qs from 'qs'
import store from '../store'
import Vue from 'vue'
import { Toast } from 'cube-ui'
Vue.use(Toast)
// import { getToken } from '@/utils/auth'
const ToasT = function (text) {
  return Toast.$create({
    txt: text,
    time:1000,
    type: 'error'
  })
}

**Comment by dolymood** [comment]
按照正常封装即可
