### ISSUE TITLE
picker里面的children是否可以换成其他参数名字

### ISSUE THREAD

**Issue by lhongtao** [didi/cube-ui#497]

**Comment by dolymood** [comment]
picker 没有 children.

如果是说的 CascadePicker 的话，也只能是约定的数据结构。

**Comment by lhongtao** [comment]
就是CascadePicker这个 
原数据结构是：
const cascadeData = [
  {
    value: 'Fruit',
    text: 'Fruit',
    children: [
      {
        value: 'Apple',
        text: 'Apple',
        children: [{ value: 1, text: 'One' }, { value: 2, text: 'Two' }]
      },
      {
        value: 'Orange',
        text: 'Orange',
        children: [{ value: 3, text: 'Three'}, { value: 4, text: 'Four' }]
      }
    ]
  }
]
我的数据结构一样 字段不一样（children名字换了）
const cascadeData = [
  {
    value: 'Fruit',
    text: 'Fruit',
    item: [
      {
        value: 'Apple',
        text: 'Apple',
        item: [{ value: 1, text: 'One' }, { value: 2, text: 'Two' }]
      },
      {
        value: 'Orange',
        text: 'Orange',
        item: [{ value: 3, text: 'Three'}, { value: 4, text: 'Four' }]
      }
    ]
  }
]
