### ISSUE TITLE
文档有不对的地方 action-sheet

### ISSUE THREAD

**Issue by yyccQQu** [didi/cube-ui#499]
![image](https://user-images.githubusercontent.com/32674176/58926549-e4240500-8775-11e9-932e-b733ae47dc90.png)

**Comment by dolymood** [comment]
多谢反馈

**Comment by dolymood** [comment]
https://github.com/didi/cube-ui/commit/b4dfb1eb396aeb9b085fd884502bce19ddaee3d2
