### ISSUE TITLE
[New Feature] cascade-picker support config cancelTxt and confirmTxt

### ISSUE THREAD

**Issue by ustbhuangyi** [didi/cube-ui#50]
### A feature or reporting a bug?

feature

### What is the current behavior?

`cancelTxt` and `confirmTxt` can not be configured.

### What is the expected behavior?

can config them using props as picker does.

**Comment by AmyFoxFN** [comment]
[fix issue](https://github.com/didi/cube-ui/commit/1deca092164386b7b43ecfc6ca0f137e211bb19b) #50
