### ISSUE TITLE
swipe btn-click方法 第三个自定义参数怎么传入

### ISSUE THREAD

**Issue by lhongtao** [didi/cube-ui#501]

**Comment by lhongtao** [comment]
<cube-swipe-item ref="swipeItem" :btns="btns" :index="i" @btn-click="onBtnClick">

**Comment by dolymood** [comment]
那不是方法 那是事件

**Comment by lhongtao** [comment]
// 左滑删除列表
   @btn-click="onBtnClick"
    onBtnClick(btn,index) 这个如何传入第三个参数呢，

**Comment by lhongtao** [comment]
> 那不是方法 那是事件
@btn-click="onBtnClick"
onBtnClick(btn,index) 这个如何传入第三个参数呢，

**Comment by lhongtao** [comment]
@dolymood 我想传入第三个参数
