### ISSUE TITLE
[New Feature] cube-ui rem布局方案是使用"remUnit": 37.5，但是大部分公司的设计图是750的

### ISSUE THREAD

**Issue by zphtown** [didi/cube-ui#508]
### What problem does this feature solve?
我很遗憾cube-ui为什么要这么设计，其次应该怎么解决，如果按照37.5布局，将导致布局偏小，如果使用75，则导致cube-ui组件偏小，这是一个很头疼的问题，issue和百度也没有一个明确的解决方案，希望cube-ui团队能指导一下，谢谢

### What does the proposed API look like?
希望能更好使用

**Comment by dolymood** [comment]
这个和设计图没多大关系的，设计图750，就意味着说你在写的时候除以2就可以了。

至于说为什么这么设计，就是因为我们是使用的px进行布局的，这个就只能按照750的设计稿/2 来做。

也正是因为这个，所以cube-ui 既默认自持px布局，也可以支持 rem vw 等布局方案

**Comment by zphtown** [comment]
> 这个和设计图没多大关系的，设计图750，就意味着说你在写的时候除以2就可以了。
> 
> 至于说为什么这么设计，就是因为我们是使用的px进行布局的，这个就只能按照750的设计稿/2 来做。
> 
> 也正是因为这个，所以cube-ui 既默认自持px布局，也可以支持 rem vw 等布局方案

如果写的时候把尺寸变成一半大小，如果设计稿是300的宽度，按照"remUnit": 37.5布局，就应该写成1.5rem，对吗，这样宽度更小了，你要回我啊

**Comment by zphtown** [comment]
> 这个和设计图没多大关系的，设计图750，就意味着说你在写的时候除以2就可以了。
> 
> 至于说为什么这么设计，就是因为我们是使用的px进行布局的，这个就只能按照750的设计稿/2 来做。
> 
> 也正是因为这个，所以cube-ui 既默认自持px布局，也可以支持 rem vw 等布局方案

这是原来的布局
  .logo{
    width: 1.56rem;
    height: 1.56rem;
    margin-top: 40%
  }
修改成这样
  .logo{
    width: 0.78rem;
    height: 0.78rem;
    margin-top: 40%
  }
改成这个更小了

**Comment by zphtown** [comment]
> 这个和设计图没多大关系的，设计图750，就意味着说你在写的时候除以2就可以了。
> 
> 至于说为什么这么设计，就是因为我们是使用的px进行布局的，这个就只能按照750的设计稿/2 来做。
> 
> 也正是因为这个，所以cube-ui 既默认自持px布局，也可以支持 rem vw 等布局方案

我知道该怎么布局了，设计稿上logo是156*156px的
  .logo{
    width: 78px;
    height: 78px;
    margin-top: 40%
  }
这样写postcss-px2rem会自动帮我们转化成rem

**Comment by zphtown** [comment]
这样就等比布局了，注意，设计稿量的px要除以2，这是一种兼容cube-ui和750设计稿的写法
