### ISSUE TITLE
[New Feature] scroll组件 当上拉加载结束后，怎么隐藏加载更多loading，和禁用上拉加载更多

### ISSUE THREAD

**Issue by zphtown** [didi/cube-ui#509]
### What problem does this feature solve?
当上拉加载结束后，怎么隐藏加载更多loading，和禁用上拉加载更多 ，我主要用到两个方法， this.$refs.scroll.forceUpdate(true, true)，和options.pullUpLoad.visible = false，但是无济于事，请指教

### What does the proposed API look like?
当上拉加载结束后，怎么隐藏加载更多loading，和禁用上拉加载更多 ，我主要用到两个方法， this.$refs.scroll.forceUpdate(true, true)，和options.pullUpLoad.visible = false，但是无济于事，请指教

**Comment by zphtown** [comment]
pullUpLoad=false设置成false的话，没有更多数据 的提示又隐藏了

**Comment by dolymood** [comment]
获取到 bs 实例 然后在完成的时机调用 closePullUp 就可以

bs的实例可以通过 this.$refs.scroll.scroll 即可获取 `<cube-scroll ref="scroll" ... />`

**Comment by dolymood** [comment]
后边我们文档上也加上相关说明吧

**Comment by zphtown** [comment]
问题没有解决， this.$refs.scroll.scroll.closePullUp 提示没有这个方法，我打印出来看了 this.$refs.scroll.scroll是一个方法，并不是一个对象

**Comment by zphtown** [comment]
> 后边我们文档上也加上相关说明吧

我还是纠正一下吧，我用的是indexLIst组件，使用了插槽，下拉刷新，刷新完，迅速弹回去，上拉加载，只要一直拉，就会显示菊花loading，我把pullUpLoad设置为false，可以不在显示菊花loading，但是没有数据的提示，没有了，列表下面是空白的

**Comment by zphtown** [comment]
> 获取到 bs 实例 然后在完成的时机调用 closePullUp 就可以
> 
> bs的实例可以通过 this.$refs.scroll.scroll 即可获取 `<cube-scroll ref="scroll" ... />`

indexList组件没有实例上找不到closePullUp
