### ISSUE TITLE
there is no data rendered on mobile phone when using indexlist,but shows data on computer

### ISSUE THREAD

**Issue by litong534** [didi/cube-ui#51]
### A feature or reporting a bug?
Bug

### What is the current behavior?
When using indexList component, it goes well in windows, but when I published my project on server and then access my domain,there is no data shows in the page, I don't know why...

### What is the expected behavior?
some data, I think.

### How to reproduce the current behavior (if this is a bug)?
publish on server.

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:
http://rozwel.club/tby/#/list
Test code
Here is my code , I use the vConsole in my code to prove the xhr goes well, you can try to access the url above on computer and on your mobile.
```js
<template>
...
<div v-if="cityData.length !==0">
<cube-index-list :data="cityData" @select="selectItem" :title="'列表'"></cube-index-list>
</div>
...
</template>

<script>
import { getDoc } from "@/api/document/document.js";
import { formatDocs } from "@/common/js/index.js";
export default {
  data() {
    return {
      cityData: []
    };
  },
  methods: {
  created() {
    getDoc().then(res => {
      this.cityData = formatDocs(res.data);
      //I try to convert the structure of data, I think there is no mistake in formatDocs function because it shows data on computer.
    })
  }
};
</script>
```

### Specify your

* vue version:
* cube-ui version:

**Comment by litong534** [comment]
vue version: 2.5.2
cube-ui version: 1.1.0
sorry for missing this

**Comment by ustbhuangyi** [comment]
Seems your mobile's problem, it works well for me.
