### ISSUE TITLE
indexList组件上拉和下拉的问题

### ISSUE THREAD

**Issue by zphtown** [didi/cube-ui#514]
### Version
1.12.24

### Reproduction link
[https://github.com/zphtown/cube-ui-bug](https://github.com/zphtown/cube-ui-bug)

### Steps to reproduce
问题：
1.上拉刷新，无法禁用上拉刷新，同时显示暂无数据
2.下拉刷新，刷新完，loading和刷完完成的提示立刻收回去，没有动画效果
3.版本：~1.12.15

首先先说一下数据源，数据源是一个一维数组，要自己分类，做成两级，无论是刷新，或者加载更多，都要重新整理整个数据，并没有用push的方法

### What is expected?
希望上拉加载，下拉刷新都可以正常使用

### What is actually happening?
1.上拉刷新，无法禁用上拉刷新，同时显示暂无数据
2.下拉刷新，刷新完，loading和刷完完成的提示立刻收回去，没有动画效果

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
github地址是这么留吗，希望cube团队能认真看一下，为了这么bug折腾了一周

**Comment by dolymood** [comment]
https://github.com/didi/cube-ui/issues/509

**Comment by zphtown** [comment]
> #509

解决速度真的无法等待

**Comment by tank0317** [comment]
@zphtown 项目代码 run dev 后似乎有问题，看不到任何东西。你看下？

**Comment by tank0317** [comment]
@zphtown

**Comment by tank0317** [comment]
> 1.上拉刷新，无法禁用上拉刷新，同时显示暂无数据

问题1，是不可能的。暂无数据的展示就是 上拉刷新的一部分，你禁用上拉刷新肯定也会禁止了暂无数据提示的展示。

**Comment by tank0317** [comment]
解决办法：

1. 禁用上拉刷新后，你自己展示 暂无数据的提示。
2. 使用下述代码，使用 `noMore` 变量标记没有更多数据，上拉动作后直接`forceUpdate(false)`展示没有更多数据

```
    onPullingUp () {
      if (this.noMore) {
        this.$refs.indexList.forceUpdate(false)
        return
      }
      this.getList()
    }
```

**Comment by zphtown** [comment]
> @zphtown 项目代码 run dev 后似乎有问题，看不到任何东西。你看下？

现在程序亲测可以跑起来了，目前还存在两个问题，1上拉刷新动画闪烁，2，下拉刷新一直都会触发，确实是可以用
  onPullingUp () {
      if (this.noMore) {
        this.$refs.indexList.forceUpdate(false)
        return
      }
      this.getList()
    }
这端代码阻止上拉刷新，但是依旧会触发onPullingUp，我也能接收
我还是希望你能够git clone git@github.com:zphtown/cube-ui-bug.git 这个demo，看下具体的bug，谢谢

git@github.com:zphtown/cube-ui-bug.git

最后，还是很开心的，以为没有人回复，等了好久

**Comment by zphtown** [comment]
> 解决办法：
> 
> 1. 禁用上拉刷新后，你自己展示 暂无数据的提示。
> 2. 使用下述代码，使用 `noMore` 变量标记没有更多数据，上拉动作后直接`forceUpdate(false)`展示没有更多数据
> 
> ```
>     onPullingUp () {
>       if (this.noMore) {
>         this.$refs.indexList.forceUpdate(false)
>         return
>       }
>       this.getList()
>     }
> ```

bug

> > 1.上拉刷新，无法禁用上拉刷新，同时显示暂无数据
> 
> 问题1，是不可能的。暂无数据的展示就是 上拉刷新的一部分，你禁用上拉刷新肯定也会禁止了暂无数据提示的展示。



> > 1.上拉刷新，无法禁用上拉刷新，同时显示暂无数据
> 
> 问题1，是不可能的。暂无数据的展示就是 上拉刷新的一部分，你禁用上拉刷新肯定也会禁止了暂无数据提示的展示。

bug已经解决，主要还是indexList和scroll文档写的有问题，导致迟迟写不对
下拉刷新结束时，如果有更多数据，不能使用    this.$refs.indexList.forceUpdate(true)，直接赋值到列表，就会自动刷新列表，如果使用则导致下拉刷新动画异常
错误示例
      this.list = arr
      this.$refs.indexList.forceUpdate(true)      true表示有数据
 
此时应该写：
     this.list = arr
    如果arr数组长度为0 
   还要加 this.$refs.indexList.forceUpdate() 这句话文档是有说的
其实scroll组件和indexList都应该这么做，而cube-ui官网文档，以及github文档都做了错误demo
下拉刷新同时使用两个
      this.list = arr
      this.$refs.indexList.forceUpdate(true)      true表示有数据

上拉加载更多，无论是否有数据，都要调this.$refs.indexList.forceUpdate(布尔值)
因为文档的问题，导致浪费了两周的时间
