### ISSUE TITLE
[New Feature] Upload组件单次上传多个文件

### ISSUE THREAD

**Issue by asypost** [didi/cube-ui#515]
### What problem does this feature solve?
业务场景中经常有一次多个文件和参数一起提交的情况，目前的Upload组件并不能做到做到这一点。
多个文件上传文件时文件的参数名的参数名一样都没有关系，关键是要能多个文件和参数一起上传。

### What does the proposed API look like?
比如提供一个props选项batchUpload,设置为true时，所有选中的文件一起上传。

**Comment by dolymood** [comment]
upload目前不支持，这种需求感觉很奇怪，大家应该都是会选择拆开传，合并传，岂不是更容易失败。

**Comment by asypost** [comment]
都是传一些小文件，失败率不高。合并传也是一次HTTP请求，总数据量不大。

**Comment by dolymood** [comment]
需求太特异了，建议自己实现。

**Comment by MeetYouZi** [comment]
数组循环拆开传，第一次获取upload组件不更新action怎么解决，打开控制台，修改源码，发现第一次选中图片的时候会computed会更新一次数据，之后获取接口参数再传递action，computed就不更新了。怎么解决呀？

**Comment by DogeJian** [comment]
How to chocie more pictures to upload by android?
