### ISSUE TITLE
cli3下怎么通过cdn引入js和css？

### ISSUE THREAD

**Issue by wxr524720** [didi/cube-ui#517]
CDN引用cube.min.js时，提示
![图片](https://user-images.githubusercontent.com/3362340/59561177-b8dfc680-904f-11e9-88a1-cda06875196a.png)
，样式引入要怎么样配置？

**Comment by wxr524720** [comment]
这是引入的js配置
![图片](https://user-images.githubusercontent.com/3362340/59561222-40c5d080-9050-11e9-92b0-76d1be52bd3e.png)
![图片](https://user-images.githubusercontent.com/3362340/59561227-48857500-9050-11e9-8396-c55c22850d96.png)

**Comment by dolymood** [comment]
如果是这种，就不需要vue-cli-plugin-cube-ui了，直接配置即可了。报错就是因为引入了插件才会报错的

**Comment by wxr524720** [comment]
> 
> 
> 如果是这种，就不需要vue-cli-plugin-cube-ui了，直接配置即可了。报错就是因为引入了插件才会报错的
可以了
