### ISSUE TITLE
checker后台获取的数据，无法选中

### ISSUE THREAD

**Issue by make-dream** [didi/cube-ui#518]

**Comment by ChelFannie** [comment]
想问一下，是否有解决

**Comment by make-dream** [comment]
已经解决，看index.js里面加了max,min的判断出现问题，然后绑定后台数据的时候，给它绑定一个最大值 :max=option.length  就可以了




------------------ 原始邮件 ------------------
发件人: "ChelFannie"<notifications@github.com>; 
发送时间: 2019年6月17日(星期一) 下午2:17
收件人: "didi/cube-ui"<cube-ui@noreply.github.com>; 
抄送: "晓晨"<923354233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [didi/cube-ui] checker后台获取的数据，无法选中 (#518)




想问一下，是否有解决
