### ISSUE TITLE
Picker、DatePicker 、ActionSheet 等新增配置项class-name

### ISSUE THREAD

**Issue by Litor** [didi/cube-ui#521]
Picker、DatePicker 、ActionSheet等组件渲染时dom元素是直接放在body下面的，如果需要微调样式目前很难精准定位，需要加入配置项class-name给这个dom自定义个class类。

**Comment by dolymood** [comment]
目前可以考虑

```js
this.$createDialog({
  $class: {'xxxx-class': true}
// ...
})
```

实现

**Comment by JiqidDev** [comment]
@dolymood 我设置了样式，html也生效了，就是效果没有出来。 大佬有demo么？
