### ISSUE TITLE
scroll组件的一点疑问

### ISSUE THREAD

**Issue by trayvon2017** [didi/cube-ui#522]
开启pullUpLoad之后,scroll的实际内容区域,".imgs-wrapper"的实际高度未达到".content-scroll-wrapper"的时候,会给".cube-scroll-list-wrapper"区域添加一个min-height,并且此时pullUpLoad还是生效的,有没有办法不添加这个min-height,并且这个时候不让pullUpLoad生效

**Comment by trayvon2017** [comment]
`<div class="content-scroll-wrapper">
        <div class="content-scroll-list-wrap" ref="scrollWrapper">
          <cube-scroll
            ref="contentScroll"
            :data="content"
            :options="options"
            @pulling-down="onPullingDown"
            @pulling-up="onPullingUp">
            <ul class="imgs-wrapper">
              <li v-for="(item, index) in content" :key="index" class="imgs-item">
                <img :src="item.url" @load="onImgLoad">
              </li>
            </ul>
</div>
</div>`

**Comment by dolymood** [comment]
As https://github.com/didi/cube-ui/issues/514
