### ISSUE TITLE
createAPI创建自定义组件，打包后名称被转译

### ISSUE THREAD

**Issue by yinminhe** [didi/cube-ui#529]
### Version
1.12.24

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/create-api](https://didi.github.io/cube-ui/#/zh-CN/docs/create-api)

### Steps to reproduce
createAPI创建自定义组件，调试开发模式下正常，但通过webpack打包后组件类名被转译，导致无法按正常组件名称进行使用。

我选用的是 vue-cli3.0 ts 

组件
@Component({
        name: 'Barcode'
  })
export default class Barcode extends Vue {}

createAPI使用
Barcode.install = function (Vue: any) {
    Vue.component('barcode', Barcode);
    createAPI(Vue, Barcode, ['hide'], true)
};

打包后barcode组件类名被转译成t，导致无法正常使用$createBarcode调用，只能通过$createT进行使用

### What is expected?
解决编译后类名转译后，无法正常使用$create。

### What is actually happening?
编译后类名转译后，无法正常使用$create。

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
就是打包后获取的 Barcode.name 变成了t，而不是 `Barcode` 是吧，

那是不是认为 

```js
@component({
name: 'Barcode'
})
```

这里无效了~

**Comment by yinminhe** [comment]
@dolymood 是的，目前解决办法是 引入组件 通过组件绑定的$create() 进行创建组件

**Comment by dolymood** [comment]
这个感觉可以深入研究下，如果是这种效果的话，目测在原本的vue环境也会有问题，例如强依赖组件name的场景，建议调试下，看看结果是真的丢掉了，还是没有获取到
