### ISSUE TITLE
ActionSheet 数据列表过多溢出不能滑动

### ISSUE THREAD

**Issue by lhongtao** [didi/cube-ui#530]

**Comment by dolymood** [comment]
ActionSheet 的设计本身就考虑不会太多场景，如果是太多的选项，就不建议是ActionSheet，而是走Picker了。

**Comment by wangqi060934** [comment]
但是确实有可能会有这样的使用场景，而且iOS的 UIAlertController 显示actionsheet时是可以滑动的。
