### ISSUE TITLE
popup组件里面内容设置overflow:scroll在移动端无法滚动

### ISSUE THREAD

**Issue by make-dream** [didi/cube-ui#531]

**Comment by make-dream** [comment]
![1561526694(1)](https://user-images.githubusercontent.com/20986400/60153119-e417a200-9815-11e9-80b1-73567b2960a2.jpg)

**Comment by dolymood** [comment]
需要在你的内容的容器元素上加上 @touchmove.stop 才可以

因为我们为了避免在弹出层的时候滚动，加了阻止事件，

**Comment by make-dream** [comment]
好优秀，真是顶呱呱



------------------ 原始邮件 ------------------
发件人: "doly mood"<notifications@github.com>; 
发送时间: 2019年6月27日(星期四) 上午10:29
收件人: "didi/cube-ui"<cube-ui@noreply.github.com>; 
抄送: "晓晨"<923354233@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [didi/cube-ui] popup组件里面内容设置overflow:scroll在移动端无法滚动 (#531)




需要在你的内容的容器元素上加上 @touchmove.stop 才可以
 
因为我们为了避免在弹出层的时候滚动，加了阻止事件，

**Comment by wuyounanhai55** [comment]
createElement创建的怎么添加

**Comment by verybeautyTang** [comment]
但是监听不到滚动事件

**Comment by jsoncode** [comment]
既然加了限制，应该在文档里说明情况 。
