### ISSUE TITLE
cube-scroll里面内容设置overflow:scroll;移动端无法滚动

### ISSUE THREAD

**Issue by make-dream** [didi/cube-ui#532]
![RCXN%E%6~5WBA0YH~7Y DUT](https://user-images.githubusercontent.com/20986400/60245012-3d530480-98ee-11e9-9a3d-5d43a54a2891.png)
![K4VI$Q_L A(N_H3%64{{VE](https://user-images.githubusercontent.com/20986400/60245039-4cd24d80-98ee-11e9-8c1b-89d4decb8d52.png)

**Comment by dolymood** [comment]
scroll就是用来处理滚动的 为何还要overflow的滚动 不合理啊
