### ISSUE TITLE
[New Feature] textarea组件没有change事件

### ISSUE THREAD

**Issue by steavengong** [didi/cube-ui#533]
### What problem does this feature solve?
我再使用textarea组件时候发现米有change事件，但是input组件有change事件

### What does the proposed API look like?
希望textarea组件加入change事件

**Comment by dolymood** [comment]
多谢反馈，1.12.25 支持了

**Comment by steavengong** [comment]
Hi

之后 我在测试的时候。发现其实 使用input事件也可以
