### ISSUE TITLE
[New Feature] 期望scroll组件watch传入的data属性时，设置deep: true

### ISSUE THREAD

**Issue by wj20160318** [didi/cube-ui#536]
### What problem does this feature solve?
如果传入的data是复杂的数据结构，如data = [ { label: 'A', list: ['a', 'aa'] } ]，当动态向data[index].list里面push数据时，就watch不到了，就不能自动forceUpdate了。
当然，在动态加入数据时，可以使用一点别的技巧，如重新给那个item负新值，
或者手动forceUpdate。
但还是希望可以加上deep: true

**Comment by dolymood** [comment]
deep true 太消耗性能了，这种需求还是建议自己主动去调用就可以。毕竟数据更改的时机是自己可控的。
