### ISSUE TITLE
cube-recycle-list 第一次请求数据撑不满一屏的时候，滚动加载就会出现问题

### ISSUE THREAD

**Issue by xiaoyexiang** [didi/cube-ui#537]
### Version
1.12.25

### Reproduction link
[https://github.com/didi/cube-ui/blob/dev/example/pages/recycle-list/recycle-list-default.vue](https://github.com/didi/cube-ui/blob/dev/example/pages/recycle-list/recycle-list-default.vue)

### Steps to reproduce
cube-recycle-list 第一次请求数据撑不满一屏的时候，滚动加载就会出现问题：

1、滚动加载会出现闪烁的现象
2、会出现无法加载下一屏数据无法显示
3、多屏数据不会往下撑开

重现很简单，在 本 dev 案例 里面 cube-recycle-list 的例子，把size 改成 3， 5 第一次数据不满一屏即可重现

### What is expected?
当撑不满一屏的时候，会自动加载第二屏数据

### What is actually happening?
cube-recycle-list 第一次请求数据撑不满一屏的时候，滚动加载就会出现问题

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by theniceangel** [comment]
@xiaoyexiang 组件内部是依赖 size 来渲染对应的 DOM 数量，所以确保 DOM 的高度能够撑满。你可以调节 size 的大小

**Comment by xiaoyexiang** [comment]
如果是这样最好在文档中写明吧，这个问题我一直还以为是我使用的方法不对，调整了老半天

**Comment by xiaoyexiang** [comment]
同时，有没有办法一轮 size 撑不满自动加载下一屏的 size ？
