### ISSUE TITLE
tab-bar 在popup中的问题

### ISSUE THREAD

**Issue by steavengong** [didi/cube-ui#538]
### Version
1.12.15

### Reproduction link
[https://rusrn.codesandbox.io/](https://rusrn.codesandbox.io/)

### Steps to reproduce
tab-bar  设置 showSlider 为true  
在popup中使用时，发现首次加载页面默认选项下面没有下划线

### What is expected?
在popup中使用时 tab-bar首次加载后默认选项下面没有下划线

### What is actually happening?
tab-bar首次加载默认选项没有下划线

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by theniceangel** [comment]
@steavengong 需要提供下你的代码

**Comment by steavengong** [comment]
@theniceangel 

1.HelloWorld.vue
<template>
  <div class="hello">
    <cube-tab-bar v-model="seletedTab" :data="tabs" showSlider/>
    <cube-button :style="{marginTop:'20px'}" @click="showPopup">Hello</cube-button>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      picker: null,
      selelctedIndex: [-1],
      column1: [],
      seletedTab: 0,
      tabs: [{ value: 0, label: "test1" }, { value: 1, label: "test2" }]
    };
  },
  methods: {
    showPopup() {
      this.$createMyPopup({
        tabIndex: this.seletedTab,
        onChange: event => {
          this.seletedTab = event;
        }
      }).show();
    },
    showPicker() {
      this.picker = this.$createPicker({
        data: this.column1.length ? [this.column1] : [],
        selectedIndex: this.selelctedIndex,
        onSelect: (val, index, text) => {
          console.log(val);
          console.log(index);
          console.log(text);
        }
      });

      this.picker.show();
    }
  }
};
</script>


<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>


2. popup.vue

<template>
  <cube-popup v-model="visible" type="my-popup" position="bottom">
    <cube-tab-bar v-model="seletedTab" :data="tabs" show-slider/>
    <div :style="{width:'100%',height:'200px',marginTop:'20px',background:'red'}">
      <cube-slide
        :initialIndex="seletedTab"
        :showDots="false"
        :autoPlay="false"
        :loop="false"
        :options="slideOptions"
        ref="slide"
      >
        <cube-slide-item>
          <div v-for="i in 10" :key="i">{{i}}</div>
        </cube-slide-item>
        <cube-slide-item>
          <div v-for="i in 10" :key="10+i">{{10+i}}</div>
        </cube-slide-item>
      </cube-slide>
    </div>
    <cube-button :style="{marginTop:'20px'}" @click="hide">关闭</cube-button>
  </cube-popup>
</template>

<script>
export default {
  name: "my-popup",
  data() {
    return {
      visible: false,
      seletedTab: 0,
      slideOptions: {
        probeType: 3,
        click: false
      },
      tabs: [{ value: 0, label: "test1" }, { value: 1, label: "test2" }]
    };
  },
  props: {
    tabIndex: {
      type: Number,
      default: 0
    }
  },
  watch: {
    visible(val) {
      if (val) {
        this.seletedTab = this.tabIndex;
      }
    },
    seletedTab(val) {
      this.$emit("change", val);
    }
  },
  mounted() {
    setTimeout(() => {
      this.$nextTick(() => {
        this.$refs.slide.refresh();
      });
    }, 200);
  },
  methods: {
    show() {
      this.visible = true;
    },
    hide() {
      this.visible = false;
    }
  }
};
</script>
<style lang="scss">
.cube-my-popup {
  & > .cube-popup-bottom {
    & > .cube-popup-content {
      height: 100%;
      background-color: #FFF;
    }
  }
}
</style>


3. main.js
import CUBE from "cube-ui";
import Vue from "vue";
import App from "./App.vue";

import { createAPI } from "cube-ui";

import MyPopup from "./components/popup";

MyPopup.install = Vue => {
  Vue.component("MyPopup", MyPopup);
  createAPI(Vue, MyPopup, ["change"], true);
};

Vue.config.productionTip = false;

Vue.use(CUBE);
Vue.use(MyPopup);

new Vue({
  render: h => h(App)
}).$mount("#app");

**Comment by steavengong** [comment]
@theniceangel 

1.  HelloWorld.vue
`
<template>
  <div class="hello">
    <cube-tab-bar v-model="seletedTab" :data="tabs" showSlider/>
    <cube-button :style="{marginTop:'20px'}" @click="showPopup">Hello</cube-button>
  </div>
</template>

<script>
export default {
  name: "HelloWorld",
  data() {
    return {
      picker: null,
      selelctedIndex: [-1],
      column1: [],
      seletedTab: 0,
      tabs: [{ value: 0, label: "test1" }, { value: 1, label: "test2" }]
    };
  },
  methods: {
    showPopup() {
      this.$createMyPopup({
        tabIndex: this.seletedTab,
        onChange: event => {
          this.seletedTab = event;
        }
      }).show();
    },
    showPicker() {
      this.picker = this.$createPicker({
        data: this.column1.length ? [this.column1] : [],
        selectedIndex: this.selelctedIndex,
        onSelect: (val, index, text) => {
          console.log(val);
          console.log(index);
          console.log(text);
        }
      });

      this.picker.show();
    }
  }
};
</script>


<style scoped>
h3 {
  margin: 40px 0 0;
}
ul {
  list-style-type: none;
  padding: 0;
}
li {
  display: inline-block;
  margin: 0 10px;
}
a {
  color: #42b983;
}
</style>

`

2. popup.vue
`
<template>
  <cube-popup v-model="visible" type="my-popup" position="bottom">
    <cube-tab-bar v-model="seletedTab" :data="tabs" show-slider/>
    <div :style="{width:'100%',height:'200px',marginTop:'20px',background:'red'}">
      <cube-slide
        :initialIndex="seletedTab"
        :showDots="false"
        :autoPlay="false"
        :loop="false"
        :options="slideOptions"
        ref="slide"
      >
        <cube-slide-item>
          <div v-for="i in 10" :key="i">{{i}}</div>
        </cube-slide-item>
        <cube-slide-item>
          <div v-for="i in 10" :key="10+i">{{10+i}}</div>
        </cube-slide-item>
      </cube-slide>
    </div>
    <cube-button :style="{marginTop:'20px'}" @click="hide">关闭</cube-button>
  </cube-popup>
</template>

<script>
export default {
  name: "my-popup",
  data() {
    return {
      visible: false,
      seletedTab: 0,
      slideOptions: {
        probeType: 3,
        click: false
      },
      tabs: [{ value: 0, label: "test1" }, { value: 1, label: "test2" }]
    };
  },
  props: {
    tabIndex: {
      type: Number,
      default: 0
    }
  },
  watch: {
    visible(val) {
      if (val) {
        this.seletedTab = this.tabIndex;
      }
    },
    seletedTab(val) {
      this.$emit("change", val);
    }
  },
  mounted() {
    setTimeout(() => {
      this.$nextTick(() => {
        this.$refs.slide.refresh();
      });
    }, 200);
  },
  methods: {
    show() {
      this.visible = true;
    },
    hide() {
      this.visible = false;
    }
  }
};
</script>
<style lang="scss">
.cube-my-popup {
  & > .cube-popup-bottom {
    & > .cube-popup-content {
      height: 100%;
      background-color: #FFF;
    }
  }
}
</style>


`

3. main.js
`
import CUBE from "cube-ui";
import Vue from "vue";
import App from "./App.vue";

import { createAPI } from "cube-ui";

import MyPopup from "./components/popup";

MyPopup.install = Vue => {
  Vue.component("MyPopup", MyPopup);
  createAPI(Vue, MyPopup, ["change"], true);
};

Vue.config.productionTip = false;

Vue.use(CUBE);
Vue.use(MyPopup);

new Vue({
  render: h => h(App)
}).$mount("#app");

`

**Comment by steavengong** [comment]
`
<div>Hello</div>
`

**Comment by steavengong** [comment]
@theniceangel 
https://github.com/steavengong/rusrn.git

**Comment by theniceangel** [comment]
@steavengong createAPI 的场景比较特殊，因为你还未调用 show 的时候，cube-popup 就已经存在，DOM 也生成了，但是 display 为 none 了。嵌套的 tab-bar 是依赖外层父容器的宽度来做计算的。所以确保在父元素 DOM 存在再实例化 tab-bar。tab-bar 加一个 v-if 判断条件即可。修改如下：

```html
<cube-popup v-model="visible" type="my-popup" position="bottom">
    <cube-tab-bar v-if="visible" v-model="seletedTab" :data="tabs" show-slider/>
```

**Comment by steavengong** [comment]
@theniceangel 
好的明白了 谢谢
