### ISSUE TITLE
Picker component,how to change the key & value name of data 

### ISSUE THREAD

**Issue by guozuji** [didi/cube-ui#54]
### A feature or reporting a bug?
No

### What is the current behavior?
...
### What is the expected behavior?
...
### How to reproduce the current behavior (if this is a bug)?
...

#### Provide the test code and the tested page URL (if applicable)

Tested page URL:

Test code

```js

```

Picker component .How can I change the key & value name of data 。such as : [{name: JACK, id: 12},{name: TOM, id: 18}]   .thanks

### Specify your

* vue version: 2.42
* cube-ui version: 1.1.0

**Comment by AmyFoxFN** [comment]
Sorry, we haven't supported customizing the key alias at present, but we will consider this feature, and may add in next version. Thanks for your suggest~:simple_smile:

**Comment by AmyFoxFN** [comment]
Refer to #57
