### ISSUE TITLE
cube-slide中使用cube-scroll造成2此点击事件

### ISSUE THREAD

**Issue by steavengong** [didi/cube-ui#540]
### Version
1.12.15

### Reproduction link
[https://xednf.codesandbox.io/](https://xednf.codesandbox.io/)

### Steps to reproduce
cube-slide中使用cube-scroll造成2此点击事件

### What is expected?
正常点击

### What is actually happening?
造成双倍伤害

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这个可以设置scroll的options的click为false即可，这个是因为click是bs手工触发的，所以两次的bs实例会派发两次，这个在2.x 中会比较好解决，目前的话只能这样手工配置。

**Comment by steavengong** [comment]
好的  谢谢  我刚才也发现了，修改click为false就行了

另外一个问题： cube-slider中有没有方法可以手动调用slider某个页面index？

**Comment by steavengong** [comment]
@dolymood 好的谢谢
