### ISSUE TITLE
popup中cube-slide 滑动问题

### ISSUE THREAD

**Issue by steavengong** [didi/cube-ui#541]
### Version
1.12.15

### Reproduction link
[https://rusrn.codesandbox.io/](https://rusrn.codesandbox.io/)

### Steps to reproduce
主页 与 popup页面 互传传递tab选中项，
popup中使用slide组件，当首次显示popup页面时，slide页面滑动正常，切换popup中的tab选项，选中的tab值会被传递给主页，popup中slide滑动也正常，问题来了，关闭popup页面，主页切换tab选项，打开popup后，slide页面没有切换，popup中的tab切换两次后slide才会滑动正常

### What is expected?
popup中cube-slide 滑动问题

### What is actually happening?
popup中cube-slide滑动问题也能正常，或者提供手动切换cube-slide页面

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
有个和 #538  类似的
