### ISSUE TITLE
input   当输入类型是number  的时候   maxlength   失效了

### ISSUE THREAD

**Issue by whl122677** [didi/cube-ui#544]

**Comment by dolymood** [comment]
这个是和原生的行为保持一致的，如果需要控制，就需要自己手工控制了。

**Comment by whl122677** [comment]
好的   谢谢你




------------------ 原始邮件 ------------------
发件人: "doly mood"<notifications@github.com>; 
发送时间: 2019年7月5日(星期五) 中午1:13
收件人: "didi/cube-ui"<cube-ui@noreply.github.com>; 
抄送: "王鸿禄"<122677892@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [didi/cube-ui] input   当输入类型是number  的时候   maxlength   失效了 (#544)




这个是和原生的行为保持一致的，如果需要控制，就需要自己手工控制了。
