### ISSUE TITLE
vue-cli3 初始化的项目，使用后编译，引入cube-ui报错

### ISSUE THREAD

**Issue by itHulk** [didi/cube-ui#547]
* ./cubeic.woff in ./node_modules/css-loader??ref--11-oneOf-3-1!./node_modules/postcss-loader/src??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/cube-ui/src/common/stylus/index.styl
![image](https://user-images.githubusercontent.com/22711051/60854834-356f5a80-a234-11e9-85a7-a3d3bb5db6a7.png)

**Comment by itHulk** [comment]
已经解决

**Comment by William-WFC** [comment]
麻烦问一下是如何解决的，我遇到了跟你一样的报错，谢谢。

**Comment by William-WFC** [comment]
@itHulk
