### ISSUE TITLE
安卓8.0系统，路由频繁切换后，点击事件失效

### ISSUE THREAD

**Issue by Max-Law** [didi/cube-ui#549]
![路由页面](https://user-images.githubusercontent.com/24608133/61116729-98c4eb00-a4c7-11e9-8ccb-2a4b21d453c6.png)

在安卓8.0环境下，我点击下面的tab切换或者点击列表跳转后再回来，列表的点击事件就失效。

首页tab切换的代码：
` <router-view class="mid" :search="searchData" v-if="userInfoGot"></router-view>
    <footer>
      <router-link
        v-for="item in tab"
        :key="item.name"
        v-on:click.stop="goTo(item.name)"
        :to="`/inquirePage/${item.name}`"
      >{{item.text}}</router-link>
    </footer>`

子路由的代码（3个类似）：
`<template>
  <div name="我的账单">
    <Refersh :templateName="name" :callback="goTo" :option="option" :check="check" ref="myRefersh" />
  </div>
</template>`

组件内的绑定：
` <ul>
    <li v-for="(item,index) in list" :key="index">
      <router-link :to="callback(item.uuid,item.billStatus)">
          // ....
          <div class="left">￥{{item.billAmount}}</div>
      </router-link>
    </li>
  </ul>`

当初以为是@click的问题，然后改成了<router-link>，后来以为是 better-scroll的问题（因采用了cube的上拉加载下拉刷新组件），options 已加上{click: true,tap: true,}，还是不行，后来发现点击后过很就一段事件他会触发，所以给路由变化时加上了取消上一条ajax的方法还是不行。

查看了vue再切换时使用想通组件不会调用钩子，但是我给每个部分都加上了初始化created()输出，还是触发了，我觉得不是影响点击问题的原因。

**Comment by Max-Law** [comment]
代码不清，补充：
```
<router-view class="mid" :search="searchData" v-if="userInfoGot"></router-view>
    <footer>
      <router-link
        v-for="item in tab"
        :key="item.name"
        v-on:click.stop="goTo(item.name)"
        :to="`/inquirePage/${item.name}`"
      >{{item.text}}</router-link>
    </footer>
```

**Comment by Max-Law** [comment]
子路由的代码（3个类似）：
```
<template>
  <ul>
    <li v-for="(item,index) in list" :key="index">
      <router-link :to="callback(item.uuid,item.billStatus)">
         // ...
        <div class="bottom clearfix">
          <div class="right status" :class="item.billStatus | formatStatus">{{item.billStatus}}</div>
        </div>
      </router-link>
    </li>
  </ul>
</template>
```

**Comment by Max-Law** [comment]
组件内的绑定：(反了)
```
<template>
  <div name="我的账单">
    <Refersh :templateName="name" :callback="goTo" :option="option" :check="check" ref="myRefersh" />
  </div>
</template>
```

**Comment by Max-Law** [comment]
> ![路由页面](https://user-images.githubusercontent.com/24608133/61116729-98c4eb00-a4c7-11e9-8ccb-2a4b21d453c6.png)
> 
> 在安卓8.0环境下，我点击下面的tab切换或者点击列表跳转后再回来，列表的点击事件就失效。
> 
> 首页tab切换的代码：
> ```
<router-view class="mid" :search="searchData" v-if="userInfoGot"></router-view>
    <footer>
      <router-link
        v-for="item in tab"
        :key="item.name"
        v-on:click.stop="goTo(item.name)"
        :to="`/inquirePage/${item.name}`"
      >{{item.text}}</router-link>
    </footer>
```
> 
> 子路由的代码（3个类似）：
> ```
> <template>
  <div name="我的账单">
    <Refersh :templateName="name" :callback="goTo" :option="option" :check="check" ref="myRefersh" />
  </div>
</template>
> ```
> 组件内的绑定：
> ```
<template>
  <ul>
    <li v-for="(item,index) in list" :key="index">
      <router-link :to="callback(item.uuid,item.billStatus)">
         // ...
        <div class="bottom clearfix">
          <div class="right status" :class="item.billStatus | formatStatus">{{item.billStatus}}</div>
        </div>
      </router-link>
    </li>
  </ul>
</template>
> ```
> 当初以为是@click的问题，然后改成了，后来以为是 better-scroll的问题（因采用了cube的上拉加载下拉刷新组件），options 已加上{click: true,tap: true,}，还是不行，后来发现点击后过很就一段事件他会触发，所以给路由变化时加上了取消上一条ajax的方法还是不行。
> 
> 查看了vue再切换时使用想通组件不会调用钩子，但是我给每个部分都加上了初始化created()输出，还是触发了，我觉得不是影响点击问题的原因。

**Comment by dolymood** [comment]
做个试验 把 bs干掉 试试呢

**Comment by Max-Law** [comment]
> 
> 
> 做个试验 把 bs干掉 试试呢

我测试了点击事件，确实触发了，应该不时BS的原因，只是this.$router.push()，没反应了，url也没变，确实搞不明白了，不知道是不是子路由的问题

**Comment by dolymood** [comment]
那可能是vuerouter的bug
