### ISSUE TITLE
Slide 组件对异步数据是否支持？

### ISSUE THREAD

**Issue by savoygu** [didi/cube-ui#55]
如果是异步数据的话，遍历的DOM为空，那么 Slide 组件在初始化是并不能成功，尝试着在异步数据过来后，push数据进去，然后在调用 refresh()，报错如下：
![qq 20171219173328](https://user-images.githubusercontent.com/9302866/34150334-039a14ec-e4e3-11e7-82f1-264ab451bcaa.png)

**Comment by Jesonhu** [comment]
@savoygu 我是一模一样的图片，如果来自异步获取再作为props传给slide让其循环渲染出来，显示就有问题。如果是在data里面的里面非异步就显示正常

**Comment by savoygu** [comment]
@Jesonhu 我目前的解决方式是，等到数据有了的话，再显示组件，通过 `v-if="data.length"`

**Comment by dolymood** [comment]
这个场景是初始的时候长度为 0  后来变为有了；而不是从开始就有 而后又更新的 对吧？

**Comment by Jesonhu** [comment]
是的。data中的数据初始为空，然后ajax请求获取然后赋值上去的。

在 2017-12-20 23:34:41，"doly mood" <notifications@github.com> 写道：


这个场景是初始的时候长度为 0 后来变为有了；而不是从开始就有 而后又更新的 对吧？

**Comment by ustbhuangyi** [comment]
better-scroll 1.6.1 已从内核上修复这个报错

**Comment by savoygu** [comment]
@ustbhuangyi 感谢
