### ISSUE TITLE
IndexList与vue-lazyload有冲突吗？

### ISSUE THREAD

**Issue by renliquan** [didi/cube-ui#552]
用IndexList与vue-lazyload同时用，点击右边的索引后，左边内容的图片就一直显示lazyload的默认图片，不会加载了，随便上下滚动一下有可以继续加载lazyload的图片

**Comment by ustbhuangyi** [comment]
目前确实会有些问题，先给一个临时解决方案吧，在我的音乐课程项目中亲测有效：

需要修改 2 个地方，第一个在注册 vue-lazyload 的地方
![image](https://user-images.githubusercontent.com/5359011/61343067-0cc41200-a87f-11e9-8386-4a8c0a04a450.png)

多注册一个 transitioncancel 事件，这个主要解决滚动过程中手动触碰屏幕停止导致图片不能加载的情况。
第二个是使用 IndexList 组件的地方

![image](https://user-images.githubusercontent.com/5359011/61343090-28c7b380-a87f-11e9-9719-e5bd9a625e88.png)

传入 speed，为了让滚动能够触发 transitionend 事件，让 vue-lazyload 插件有机会去加载图片。

**Comment by renliquan** [comment]
谢谢黄大神，解决了。你的两个课程我都买的正版.....^_^
