### ISSUE TITLE
input的type为number的时候,通过@input控制长度,控制不住

### ISSUE THREAD

**Issue by TrainingSpring** [didi/cube-ui#554]
## 控制input类型为number的输入长度的问题: 
出错代码如下
### html代码:
 ` <cube-input  style="width: 50%;" v-model="verifyCode" @input="restrainLength"  placeholder="请输入验证码"  type="number"></cube-input>`
### methods中js代码:
`restrainLength(val){`
`        if (val.length>6){`
`          let v = val.toString();`
`          v = v.slice(0,6);`
`          this.verifyCode = parseInt(v);`
`        }`
`      }`
事实上,我还试过其他方式修改,如watch,computed,也无效,事实证明,应该是组件内绑定数据的问题

在data中的数据verifyCode 是正确的,只有6位数,但是在浏览器中,可以无限长度输入! 
后来将html代码改了下,添加了一个oninput才可以,并且@input也必须存在!
正常情况下,原生input是可以直接操作data中的绑定数据实现的,改后的代码:
 `<cube-input  style="width: 50%;" :maxlength="6" v-model="verifyCode" @input="restrainLength" oninput="if(this.childNodes[1].value.length>6)this.childNodes[1].value = this.childNodes[1].value.slice(0,6);" ref="verify" placeholder="请输入验证码"  type="number"></cube-input>` 

最终我嫌这方法麻烦,只能自己写了个组件...

**Comment by dolymood** [comment]
我们增加一个number限制输入的demo吧

**Comment by dolymood** [comment]
已加 https://didi.github.io/cube-ui/#/zh-CN/docs/input

![image](https://user-images.githubusercontent.com/2121554/61844474-234b1880-aed2-11e9-9399-5825a4b0e84d.png)
