### ISSUE TITLE
better-scroll滑动的内容只超过一点点时，快速滑动到顶部或底部点击，点击事件不触发，需要点击两次

### ISSUE THREAD

**Issue by 533230** [didi/cube-ui#555]
<cube-scroll
                                        ref="meScroll"
                                        :options="{
                                        bounce:false
                                        }"
                                        :scroll-events="['scroll']"
                                        @scroll="meScroll”>
</cube-scroll>

<img width="379" alt="WX20190722-173047@2x" src="https://user-images.githubusercontent.com/15622373/61622178-e0592d00-aca6-11e9-9175-17929f9e4db7.png">
<img width="365" alt="WX20190722-173434@2x" src="https://user-images.githubusercontent.com/15622373/61622253-fff05580-aca6-11e9-9826-e8f884560430.png">

**Comment by 533230** [comment]
快速滑动后class="cube-scroll-list-wrapper”.    的    pointer-events为none。只有点击了一次之后    pointer-events变成auto 才触发点击事件

**Comment by dolymood** [comment]
这是故意为之，你可以看原生的滚动也都是类似的，第一次是停住，点击行为只有是停的状态下才可以的
