### ISSUE TITLE
[New Feature] 什么时候可以支持better-scroll的v1.14.0

### ISSUE THREAD

**Issue by cykcykcykcyk** [didi/cube-ui#556]
### What problem does this feature solve?
在v1.14.0有autoPullDownRefresh() 既自动触发下拉刷新，这个对于大多数前端其实用处很大，可能在新增列表中的item发生改变，又难以通过单独更改数据修改item的data从而重新渲染。又或者在mounted等等生命周期中，需要再加数据，简单的通过autoPullDownRefresh()调用即可。
我觊觎这个方法已经很久了，求官方可以支持

### What does the proposed API look like?
(<any>this).$refs.scroll.autoPullDownRefresh()

**Comment by dolymood** [comment]
As https://github.com/didi/cube-ui/issues/465
