### ISSUE TITLE
scroll组件下拉刷新时，在刷新动作未完成时继续下拉，下拉动画会出现异常，不能回弹回去。

### ISSUE THREAD

**Issue by MeetYouZi** [didi/cube-ui#559]
### Version
1.12.27

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/scroll](https://didi.github.io/cube-ui/#/zh-CN/docs/scroll)

### Steps to reproduce
1，scroll下拉刷新，下拉刷新动作未回弹回去时继续下拉动作，下拉动画异常，不能回弹回去，也不能再次执行下拉动作了。
备注：本地调试没有这个问题。打包之后发布到线上就会有这个问题。

### What is expected?
下拉刷新未回弹回去时继续下拉可以继续执行刷新操作且可以正常回弹回去

### What is actually happening?
下拉刷新未回弹回去时继续下拉，下拉动画异常，且后续往下拉不能执行刷新操作，下拉失效

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
官网提供的例子也可以重现这个问题

**Comment by dolymood** [comment]
麻烦提供个视频会比较好，实验了几次 没有复现还

**Comment by MeetYouZi** [comment]
测试地址：http://c.huayeee.com/#/mine 
tab页 =》我的
版本号1.12.27

**Comment by dolymood** [comment]
打开报错了 我想看的是操作步骤 最好是复现的官方的示例的效果。你的那个操作时机只有看了才明白，语言很难描述清楚

**Comment by MeetYouZi** [comment]
能否留个联系方式，我把视频发给你，这里我不知道怎么发视频，下拉刷新正常的版本号是1.12.15，版本1.12.27下拉是有异常的

**Comment by 1402-zzh** [comment]
我也碰到了同样的问题 ，我的版本是"cube-ui": "^1.12.26"。请问作者目前解决了吗

**Comment by 1402-zzh** [comment]
@MeetYouZi

**Comment by MeetYouZi** [comment]
把cube-UI版本降回1.12.15就不会有这个问题，我安装的最新1.12.27是有问题的。

**Comment by 1402-zzh** [comment]
你是做了降版本的处理吗

**Comment by 1402-zzh** [comment]
我先等等看官方能不能给个解决方案

**Comment by 1402-zzh** [comment]
@MeetYouZi 你降级之后，会不会有其他问题

**Comment by MeetYouZi** [comment]
暂时没发现其他问题，
还有一个就是官方现在不明白我这个问题的操作步骤是什么，我不知道怎么发操作视频

**Comment by 1402-zzh** [comment]
我在qq群里发了一个，但是目前好像还没处理吧，等他们的消息吧。目前我也降级了

**Comment by xuzhixiong886** [comment]
遇到同样的问题，连续拉下就会出现这个问题，希望能得到解决

**Comment by zwind007** [comment]
1.12.27遇到同样的问题，连续快速下拉几次后菊花无法回弹，加载状态无法结束。 按照@MeetYouZi 的方法降到1.12.15，暂时没发现问题。

**Comment by dolymood** [comment]
1.12.29已修复
