### ISSUE TITLE
Invalid key "require" in validation rules object for prop "value"

### ISSUE THREAD

**Issue by YukiYuko** [didi/cube-ui#56]
### A feature or reporting a bug?
 reporting a bug

### What is the current behavior?
[Vue warn]: Invalid key "require" in validation rules object for prop "value"
看了一下错误的原因， 应该是
https://github.com/didi/cube-ui/blob/dev/lib/checkbox-group/index.js
这里面的 props 的问题  还是用了  require 的原因
value: {
        type: [Boolean, String],
        require: true
      },

### What is the expected behavior?
no warn

### How to reproduce the current behavior (if this is a bug)?
value prop required

### Specify your

* vue version: 2.5.2
* cube-ui version: 1.2.0

**Comment by dolymood** [comment]
see https://github.com/didi/cube-ui/issues/49

**Comment by YukiYuko** [comment]
了解了
