### ISSUE TITLE
[New Feature]微信小程序团队开源了kbone工具，希望兼容下

### ISSUE THREAD

**Issue by stephenml** [didi/cube-ui#561]
### What problem does this feature solve?
kbone工具是微信小程序团队开源的一款将Vue项目打包成微信小程序的工具，完整的移植了Vue Runtime，提供了微信小程序中运行的适配器，可以将现有的Vue项目直接打包成微信小程序代码

### What does the proposed API look like?
在这个工具中试用了下你们的组件，大部分是可以直接运行的，但也有一些不兼容，只要是因为 getComputedStyle 和 getBoundingClientRect 在小程序里没法支持同步接口，只能异步，例如：ImagePreview、Picker等

**Comment by dolymood** [comment]
看了下 kbone 目前还不够完善，而且这种方式注定会很多坑，不建议使用直接做转换处理
