### ISSUE TITLE
Swipe组件的cube-swipe-btn高度为零并且没有绝对定位，求大佬指下明路

### ISSUE THREAD

**Issue by HARDCOREAJ** [didi/cube-ui#564]
### Version
1.12.27

### Reproduction link
[https://github.com/HARDCOREAJ/git-demo-1/blob/master/cube-ui-Swipe%E7%BB%84%E4%BB%B6%E6%8A%A5%E9%94%99.jpg](https://github.com/HARDCOREAJ/git-demo-1/blob/master/cube-ui-Swipe%E7%BB%84%E4%BB%B6%E6%8A%A5%E9%94%99.jpg)

### Steps to reproduce
      <div class="swipe-wrapper">
        <cube-scroll ref="scroll">
          <cube-swipe>
            <transition-group name="swipe" tag="ul">
              <li
                class="swipe-item-wrapper"
                v-for="(data,index) in dialogList"
                :key="data.sendUserId"
              >
                <cube-swipe-item
                  ref="swipeItem"
                  :btns="data.btns"
                  :index="index"
                  @item-click="chat(data.sendUserId)"
                  @btn-click="onBtnClick"
                >
                  <div class="item-inner">
                    <dialog-single :dialog="data"></dialog-single>
                  </div>
                </cube-swipe-item>
              </li>
            </transition-group>
          </cube-swipe>
        </cube-scroll>
      </div>

### What is expected?
滑动swipe-item应该出现按钮

### What is actually happening?
没有出现按钮

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
PS：以上样式都是直接按照官网示例抄的

**Comment by dolymood** [comment]
参考 https://github.com/didi/cube-ui/blob/dev/example/pages/swipe/custom.vue

且 对于 scoped 的覆盖的样式，需要去了解下

**Comment by HARDCOREAJ** [comment]
还是没找到原因，会不会我用的是scss的原因？

**Comment by HARDCOREAJ** [comment]
![微信图片_20190812174919](https://user-images.githubusercontent.com/40049420/62857245-b2a55800-bd29-11e9-8716-668a7d6a588c.png)
哥，你看下，我照搬你们的demo了还是一样

**Comment by HARDCOREAJ** [comment]
@dolymood
