### ISSUE TITLE
Upload组件可能会和原生input冲突

### ISSUE THREAD

**Issue by HARDCOREAJ** [didi/cube-ui#565]
### Version
1.12.27

### Reproduction link
[https://github.com/HARDCOREAJ/git-demo-1/blob/master/upload%E7%BB%84%E4%BB%B6bug2.png](https://github.com/HARDCOREAJ/git-demo-1/blob/master/upload%E7%BB%84%E4%BB%B6bug2.png)

### Steps to reproduce
假如页面A有一个原生的input上传，然后路由跳转进入到页面B（有upload组件），则会发现上传的图片是空白的现象

### What is expected?
原生input不应该和upload组件冲突

### What is actually happening?
upload组件得到的照片是空白的

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
https://github.com/HARDCOREAJ/git-demo-1/blob/master/upload%E7%BB%84%E4%BB%B6bug.png
// 这是有原生input的页面A

**Comment by dolymood** [comment]
这个没啥关系，都两个页面了

如果真的是，需要一个复现链接 最好是 repo

**Comment by HARDCOREAJ** [comment]
不好意思，确实不是input的影响.
可能样式覆盖的行为造成的，我还在排查
