### ISSUE TITLE
[New Feature] validator组件两个绑定的值之间怎么进行比较，比如密码与重复密码的比较，值一致。

### ISSUE THREAD

**Issue by zhangkaivictor** [didi/cube-ui#568]
### What problem does this feature solve?
比如密码与重复密码的比较，值一致。因为在规则的自定义里面的，自定义函数的this指向不明，导致获取不到比较值的最新值

newPwdRules: {
                required: true,
                type: 'string',
                min: 6,
                max: 18,
                pattern: /^(?!([a-zA-Z] |\d )$)[a-zA-Z\d]{6,18}$/,
                equivalence: (val) => {
                    // console.log('this : ', this)
                    // console.log('pwd : ', this.a.data().pwd)
                    // console.log('a.data() : ', this.a.data())
                    // console.log('$data : ', this.$data)
                    // this.a.methods.equivalence(val)
                    return val === this.a.data().pwd
                }
            },
            pwdMessages: {
                pattern: '请输入包含字母和数字的组合，不能使用特殊字符，长度在6-18之间.',
            },
            rePwdMessages: {
                pattern: '请输入包含字母和数字的组合，不能使用特殊字符，长度在6-18之间.',
                equivalence: '两次输入的密码请保持一致.',
            },

### What does the proposed API look like?
compareValue

**Comment by dolymood** [comment]
这个是vue的吧，上下文的this就是组件实例，猜测你要写的大码就是 this.a.pwd 或者 this.pwd

**Comment by zhangkaivictor** [comment]
html部分

                <cube-validator ref="pwd" v-model="result[2]" :model="pwd" :rules="pwdRules" :messages="pwdMessages">
                    <cube-input type="password" class="f14" :eye="{open:false,reverse:false}" clearable
                                v-model="pwd" placeholder="请输入密码">
                        <img slot="prepend" src="/src/assets/images/lock.png" alt="">
                    </cube-input>
                </cube-validator>

                
                <cube-validator
                    ref="newPwd"
                    v-model="result[3]"
                    :model="newPwd"
                    :rules="newPwdRules"
                    :messages="rePwdMessages"
                    @input="changeNewPwd"
                >
                    <cube-input type="password" class="f14" :eye="{open:false,reverse:false}" clearable
                                v-model="newPwd" placeholder="请再次输入密码">
                        <img slot="prepend" src="/src/assets/images/lock.png" alt="">
                    </cube-input>
                </cube-validator>

js 部分
data: () => ({
            timeout: null,
            authWord: '获取验证码',
            phone: '',
            captcha: '',
            result: [undefined, undefined, undefined, undefined],
            phoneRules: {required: true, type: 'tel',},
            captchaRules: {required: true, type: 'number', len: 6,},
            pwd: '',// 密码
            newPwd: '', // 重复密码
            pwdRules: {required: true,type: 'string',min: 6,max: 18,pattern: /^(?!([a-zA-Z]+|\d+)$)[a-zA-Z\d]{6,18}$/},
            newPwdRules: {
                required: true,type: 'string',min: 6,max: 18,pattern: /^(?!([a-zA-Z]+|\d+)$)[a-zA-Z\d]{6,18}$/,
                equivalence: (val) => {
                    // console.log('pwd : ', this.pwd)  // 打印为undefined 我怎么获取这个pwd的值 来进行密码与重复密码之间的比较  ？？？？？？？？
                    return val === this.pwd
                }
            },
            pwdMessages: {
                pattern: '请输入包含字母和数字的组合，不能使用特殊字符，长度在6-18之间.',
            },
            rePwdMessages: {
                pattern: '请输入包含字母和数字的组合，不能使用特殊字符，长度在6-18之间.',
                equivalence: '两次输入的密码请保持一致.',
            },
        }),
