### ISSUE TITLE
[New Feature] need support for dynamic import

### ISSUE THREAD

**Issue by legeneek** [didi/cube-ui#571]
### What problem does this feature solve?
dynamic import a single component when required.
can reduce the first page assert size.

### What does the proposed API look like?
import(/\* webpackPrefetch:true \*/ 'cube-ui/datePicker')

**Comment by dolymood** [comment]
You can import the components directly

```js
import('cube-ui/lib/date-picker')
import('cube-ui/lib/date-picker/style.css')
// or 
import('cube-ui/src/modules/date-picker')
```

**Comment by legeneek** [comment]
well done, it works.
