### ISSUE TITLE
loading 组件怎么在js中使用

### ISSUE THREAD

**Issue by myGitHubHuLin** [didi/cube-ui#574]

**Comment by dolymood** [comment]
没有loading组件 
有些支持的 然后在js中使用 参考 https://didi.github.io/cube-ui/#/zh-CN/docs/create-api#cube-%E5%A6%82%E4%BD%95%E5%9C%A8%E6%99%AE%E9%80%9Ajs%E6%96%87%E4%BB%B6%E4%B8%AD%E6%88%96%E8%80%85%E5%85%A8%E5%B1%80%E8%B0%83%E7%94%A8-anchor
