### ISSUE TITLE
提个建议，或者没想通的

### ISSUE THREAD

**Issue by CharlinFeng** [didi/cube-ui#575]
无限滚动列表，（为什么）不能和下拉上拉刷新列表组合？

很多需求是： 有上拉下拉的列表，支持无限滚动。 你弄成两个组件，用户很尴尬。。。

**Comment by dolymood** [comment]
基于之前的需求，我们在实现可回收列表的时候，选择使用的是原生滚动行为，但是原生的滚动里并没有提供下拉刷新的能力。

可回收列表组件支持的就是上拉的模式

**Comment by dolymood** [comment]
Same as #584
