### ISSUE TITLE
[New Feature] 嵌套scroll的问题

### ISSUE THREAD

**Issue by Firstnote** [didi/cube-ui#577]
### What problem does this feature solve?
目前采用的是slide里嵌套scroll实现下拉刷新的功能，但是有需求外部scroll组件外部向上滑动到顶后内部才滑动，目前的嵌套scroll是内层触发边界再启用内层。

### What does the proposed API look like?
嵌套scroll 的时候，先触发外层scroll，当外层达到边界的时候再启用内层scroll

**Comment by dolymood** [comment]
这种特异性需求建议自己基于bs实现

**Comment by Firstnote** [comment]
> 这种特异性需求建议自己基于bs实现

我尝试使用了disabled函数来禁用内部滚动，但是当达到重新启用内部滚动的条件的时候，内部本应被禁用的scoll依然跳跃到了未禁用时才会出现的位置，这是为什么

**Comment by dolymood** [comment]
仅供参考 https://github.com/didi/cube-ui/blob/dev/src/components/scroll/scroll.vue#L378

**Comment by Firstnote** [comment]
关于之前提的需求我已经通过scrollTo解决了，但是我比较关心的就是disable和enable互动切换出现问题的原理，应该是bs的问题，不得其解

**Comment by Firstnote** [comment]
> 仅供参考 https://github.com/didi/cube-ui/blob/dev/src/components/scroll/scroll.vue#L378

关于之前提的需求我已经通过scrollTo解决了，但是我比较关心的就是disable和enable互动切换出现问题的原理，应该是bs的问题，不得其解
