### ISSUE TITLE
[New Feature] 表单验证validate能否只校验某些字段

### ISSUE THREAD

**Issue by pisces22745** [didi/cube-ui#578]
### What problem does this feature solve?
eg:表单中有验证码功能，在发送验证码时需要先验证是否输入手机号码，并且触发手机号的验证，如果手机号码为空，则仅提示手机号码的字段，如果手机号码正确，则继续做后续功能。

### What does the proposed API look like?
```javascript
this.$refs[form].validateField('字段名称',(result)=>{})

```

**Comment by dolymood** [comment]
目前可以取到form实例得到 fields ，每个field都是一个form item实例 有validate 方法

**Comment by pisces22745** [comment]
> 目前可以取到form实例得到 fields ，每个field都是一个form item实例 有validate 方法

field的validate 方法是没有参数的是吗？还是只能通过validity去判断验证结果？

**Comment by dolymood** [comment]
有参数 cb 或者对于支持promise也是返回promise实例的
