### ISSUE TITLE
cube-scroll组件下拉加载，回弹触发机制问题

### ISSUE THREAD

**Issue by oydiligent** [didi/cube-ui#579]
你好！使用cube-scroll组件下拉加载，再回弹没有回去之前，继续下拉加载，连续操作6次以上，会出现回弹失败，再也不会触发下拉加载！且上面一直会有个loading，操作官方例子也是同样结果：[https://didi.github.io/cube-ui/example/#/scroll/toutiao](url)；
![image](https://user-images.githubusercontent.com/19690319/63020620-2e8dd480-bed1-11e9-9199-3e1f59d3b960.png)

**Comment by zwind007** [comment]
同样的问题，另一个issue里看到，降到1.12.15试试，我这边降级了暂时没发现问题。

**Comment by dolymood** [comment]
即将发布新版解决 现在有问题可降级到之前版本

**Comment by dolymood** [comment]
1.12.29已修复

**Comment by gongyuying-000** [comment]
手动调用
this.$refs.scroll.forceUpdate()
可回弹成功
