### ISSUE TITLE
建议支持scss，不仅仅是stylus

### ISSUE THREAD

**Issue by php4world** [didi/cube-ui#58]

**Comment by dolymood** [comment]
如果要使用后编译的话，必须有 stylus 否则则是非必须的依赖的

**Comment by SHERlocked93** [comment]
@dolymood  您好，什么叫 `非必须的依赖` 呢，因为在webstorm中使用 `stylus` 有一些不方便的地方，特别是在自动格式化的时候

**Comment by dolymood** [comment]
这个如果使用后编译需要安装 stylus stylus-loader 但是你自己的应用部分可以依旧使用 sass，两个可以共存的

而如果是普通编译场景，这个限制也就没有了，只需要安装你应用使用的 预处理器以及对应的loader就可以

**Comment by SHERlocked93** [comment]
@dolymood  非常感谢回复~ 因为这两天刚开始使用`cube-ui`并且用在生产环境中，所以比较担心引入scss会不会影响到动态theme

**Comment by dolymood** [comment]
如果是主题定制 也就 theme.styl 这一个文件受影响，而且不会有啥格式化问题

应用其他部分依旧可以使用 scss
