### ISSUE TITLE
Swipe组件的cube-swipe-btn高度为零，将官方demo完全copy下来还是没法解决问题

### ISSUE THREAD

**Issue by HARDCOREAJ** [didi/cube-ui#580]
### Version
1.12.28

### Reproduction link
[https://github.com/HARDCOREAJ/git-demo-1/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190812174919.png](https://github.com/HARDCOREAJ/git-demo-1/blob/master/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190812174919.png)

### Steps to reproduce
在我的项目里，使用的是scss；没有发现其他组件有样式问题，只有Swipe组件出现了滑动按钮高度为零的情况

### What is expected?
按钮高度不为零

### What is actually happening?
按钮高度为零

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
import Cube from 'cube-ui'；在main.js里面我是直接全局引入cube-ui；
vue.config.js里面配置是： pluginOptions: {
    'cube-ui': {
      postCompile: true,
      theme: true
    }
  }

**Comment by tank0317** [comment]
只提供一个图片我们没办法复现问题，能提供一个可运行的代码吗？

**Comment by HARDCOREAJ** [comment]
@tank0317 老哥，麻烦帮我看看。路由地址是：http://localhost:8080/static/app#/dialog。
代码我放到一个压缩文件里，你解压以后yarn 安装一下依赖就可以了。
https://github.com/HARDCOREAJ/git-demo-1/blob/master/web-app.rar

**Comment by dolymood** [comment]
压缩文件 我们这边解压不能识别 
建议提供线上git仓库

**Comment by HARDCOREAJ** [comment]
@dolymood 好的，麻烦你了，地址是 https://github.com/HARDCOREAJ/Practice/tree/master/web-pc

**Comment by HARDCOREAJ** [comment]
@dolymood https://github.com/HARDCOREAJ/SCSS-demo/tree/master/web-app
谢谢，我放到git仓库了

**Comment by dolymood** [comment]
你的项目有样式问题
![image](https://user-images.githubusercontent.com/2121554/63244262-7de85200-c28f-11e9-8708-3d504ad826f9.png)

**Comment by HARDCOREAJ** [comment]
@dolymood 请问具体是哪里的样式问题？ 为什么我这里没显示....
![image](https://user-images.githubusercontent.com/40049420/63247104-cc4d1f00-c296-11e9-923a-2a6f8a48e62f.png)

**Comment by dolymood** [comment]
全局样式污染了，animation影响到了定位体系 所以里边的元素找不到高度了 所以高度为0了

**Comment by HARDCOREAJ** [comment]
@dolymood 谢谢大哥 ! 解决了，原来是一个vueg的动画库样式把它覆盖了
