### ISSUE TITLE
在Popup 弹层中 无法上下滑动，但滚轮却有效

### ISSUE THREAD

**Issue by Max-Law** [didi/cube-ui#583]
### Version
1.12.30

### Reproduction link
[https://eoatestdev.sscc.com/sscc-ow-mobile-web/webstatic/weixin/index.html#/](https://eoatestdev.sscc.com/sscc-ow-mobile-web/webstatic/weixin/index.html#/)

### Steps to reproduce
在Popup填入一个列表，无法滑动

### What is expected?
能够拖动

### What is actually happening?
不能拖动

### Dependencies Version
vue: 2.6.10
better-scroll: 1.15.0

**Comment by dolymood** [comment]
Popup 中阻止了touchmove事件 可以在popup 里层元素上加上 @touchmove.stop 阻止事件冒泡
后边我们加入到文档中
