### ISSUE TITLE
dialog编写slot问题

### ISSUE THREAD

**Issue by 303182519** [didi/cube-ui#588]
```
this.$createDialog({
            type: 'alert',
            confirmBtn: {
                text: '我知道了',
                active: true
            }
        }, (createElement) => {
            return (
                <div>
                    <div class="my-title" slot="title"><div class="my-title-img"></div><p>附近车少,优选出租车将来接您</p></div>
                    <p class="my-content" slot="content">价格仍按快车计算</p>
                </div>

            );
        }).show();

```

为什么我改成这样不行的

**Comment by 303182519** [comment]
> ```
> this.$createDialog({
>             type: 'alert',
>             confirmBtn: {
>                 text: '我知道了',
>                 active: true
>             }
>         }, (createElement) => {
>             return (
>                 <div>
>                     <div class="my-title" slot="title"><div class="my-title-img"></div><p>附近车少,优选出租车将来接您</p></div>
>                     <p class="my-content" slot="content">价格仍按快车计算</p>
>                 </div>
> 
>             );
>         }).show();
> ```
> 
> 为什么我改成这样不行的

没事了，知道问题了

**Comment by Hxiaotong** [comment]
请教一下你是怎么改好的，自定义弹层内容没效果呢？

**Comment by 303182519** [comment]
你是怎么写的
