### ISSUE TITLE
uplaod组件问题

### ISSUE THREAD

**Issue by yyqxjwxy** [didi/cube-ui#590]
### Version
1.12.30

### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/upload](https://didi.github.io/cube-ui/#/zh-CN/docs/upload)

### Steps to reproduce
upload上传组件拍过照片后显示在橱窗的缩略图是倒过来的，官网的custom demo也是这个问题用手机打开的话

### What is expected?
希望图片可以不旋转正着来

### What is actually happening?
图片自动旋转

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这个和upload本身没啥关系，但是这个是属于手机上的一些问题，
一部分代码仅供参考 https://github.com/Tencent/weui.js/blob/master/src/uploader/image.js
