### ISSUE TITLE
form 自定义component 如何绑定值后刷新视图

### ISSUE THREAD

**Issue by simon14980116** [didi/cube-ui#592]
form 自定义component
初始化可以通过 modelKey 绑定值后视图显示
但之后通过 this.model.xxxx = 'dddd' 绑定值
视图没有刷新
而原生例如用 type：‘input’ 是可以的
请问自定义 component 如何解决

**Comment by myGitHubHuLin** [comment]
可以通过vue的计算属性改变视图

**Comment by simon1498** [comment]
分享下解决方案
那控件处
![image](https://user-images.githubusercontent.com/4925982/65405646-59901000-de0f-11e9-8c98-22a6403f1121.png)

除了改变model，还要改变field，写了个方法
![image](https://user-images.githubusercontent.com/4925982/65405689-8e9c6280-de0f-11e9-8cc0-8769fee7250a.png)

**Comment by myGitHubHuLin** [comment]
自定义组件特殊处理






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon1498"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 下午2:37
收件人: "didi/cube-ui"<cube-ui@noreply.github.com&gt;; 
抄送: "2352776704"<2352776704@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [didi/cube-ui] form 自定义component 如何绑定值后刷新视图 (#592)




分享下解决方案
 那控件处
 
 
除了改变model，还要改变field，写了个方法

**Comment by myGitHubHuLin** [comment]
fields写法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon1498"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 下午2:37
收件人: "didi/cube-ui"<cube-ui@noreply.github.com&gt;; 
抄送: "2352776704"<2352776704@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [didi/cube-ui] form 自定义component 如何绑定值后刷新视图 (#592)




分享下解决方案
 那控件处
 
 
除了改变model，还要改变field，写了个方法

**Comment by myGitHubHuLin** [comment]
改值的方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon1498"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 下午2:37
收件人: "didi/cube-ui"<cube-ui@noreply.github.com&gt;; 
抄送: "2352776704"<2352776704@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [didi/cube-ui] form 自定义component 如何绑定值后刷新视图 (#592)




分享下解决方案
 那控件处
 
 
除了改变model，还要改变field，写了个方法

**Comment by myGitHubHuLin** [comment]
这是组件的使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "simon1498"<notifications@github.com&gt;; 
发送时间: 2019年9月23日(星期一) 下午2:37
收件人: "didi/cube-ui"<cube-ui@noreply.github.com&gt;; 
抄送: "2352776704"<2352776704@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [didi/cube-ui] form 自定义component 如何绑定值后刷新视图 (#592)




分享下解决方案
 那控件处
 
 
除了改变model，还要改变field，写了个方法
