### ISSUE TITLE
webpack项目使用后编译引入cube-ui，组件没有经过babel转译代码

### ISSUE THREAD

**Issue by chwech** [didi/cube-ui#594]
### Version
1.12.30

### Reproduction link
[https://github.com/chwech/cube-ui-demo](https://github.com/chwech/cube-ui-demo)

### Steps to reproduce
```
1.
git clone https://github.com/chwech/cube-ui-demo

2.
cd cube-ui-demo

3.
npm i

4.
npm run serve

5. ie打开localhost:9000端口，报错，点击进去发现是cube-ui代码没有转译

```

### What is expected?
使用后编译集成项目时cube-ui能经过babel转译

### What is actually happening?
使用后编译集成项目时cube-ui没有经过babel转译

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
参考 https://github.com/cube-ui/question-answer/issues/29 和 https://github.com/cube-ui/question-answer/issues/55

即可解决你的问题

**Comment by chwech** [comment]
it works. 谢谢！
