### ISSUE TITLE
在cube-scroll中使用弹出层drawer

### ISSUE THREAD

**Issue by z1137557736** [didi/cube-ui#595]
在cube-scroll中使用弹出层drawer，当我drawer滑动时，父级cube-scroll也会随着滑动，建议drawer也增加nestMode嵌套滚动模式

**Comment by tank0317** [comment]
为什么 cube-scroll 中会使用 drawer 呢？不能放 cube-scroll 外吗？

**Comment by z1137557736** [comment]
![image](https://user-images.githubusercontent.com/32252043/64663966-1bdecf00-d480-11e9-8555-39fc37e021c8.png)
这是我的父组件

**Comment by z1137557736** [comment]
![image](https://user-images.githubusercontent.com/32252043/64664052-8132c000-d480-11e9-9334-a004ac14a798.png)
这是我目前的组件结构，由于考虑到底部导航栏在移动端的定位问题不太灵活，所以内容区域采用了cube-scroll。正因为我在子组件中使用了drawer，导致问题的发生。

**Comment by tank0317** [comment]
恩，很奇特的使用方式。不管你怎么使用吧。现在试试给 drawer 组件的 touchstart 事件禁止 stopPropagation ？

**Comment by z1137557736** [comment]
![image](https://user-images.githubusercontent.com/32252043/64666248-3026ca00-d488-11e9-8c5a-d1faada07af5.png)
测试后还是滑动还是有bug，能否当我在子组件使用drawer时，加一个参数，把当前drawer标签append到body元素上，这样使用的话就不会重现此问题

**Comment by z1137557736** [comment]
![image](https://user-images.githubusercontent.com/32252043/64666446-ee4a5380-d488-11e9-9a49-43c54abe2787.png)
经测试后滑动还是有bug，能否当我在子组件使用drawer时，加一个参数，把当前drawer标签append到body元素上，这样使用的话就不会重现此问题

**Comment by tank0317** [comment]
cube-ui 的 create-api 会把组件添加到body
https://didi.github.io/cube-ui/#/zh-CN/docs/create-api

另外，cube-ui 的 create-api 是对 vue-create-api 的封装，你也可以看
https://github.com/cube-ui/vue-create-api/blob/master/README_zh-CN.md

**Comment by z1137557736** [comment]
@tank0317 感谢大佬，已通过create-api实现此功能:smile:
