### ISSUE TITLE
如何让表单验证的提示出现在输入框下方

### ISSUE THREAD

**Issue by bufudanqing** [didi/cube-ui#599]
### Version
1.12.31

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
用的cube-form表单，<cube-form-item :field="fields[0]"></cube-form-item>这种形式，点提交后会出现一个红点，点击红点才弹出提示，想要把提示直接出现在字段下方，cube-ui有例子没代码啊

### What is expected?
错误提示显示在字段下方，看到了示例是这样的，但没看到示例的代码是怎么写的

### What is actually happening?
错误提示需要点击红点才弹出来

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这块写的有些简单了
![image](https://user-images.githubusercontent.com/2121554/65036188-72b33f80-d97d-11e9-945e-610967a1a8d7.png)

可通过 options 的 layout 决定何种布局 可以是 standard classic fresh 其中一种

我后边把文档改下
