### ISSUE TITLE
[New Feature] ScrollNavBar 指定direction的另外的方向恢复原生滚动

### ISSUE THREAD

**Issue by chinieer** [didi/cube-ui#609]
### What problem does this feature solve?
ScrollNavBar设置水平方向滚动时，在组件触发上下滑动，父组件没法滚动

### What does the proposed API look like?
例如方向，默认横向，那么better scroll的eventPassthrough的可设置为vertical

**Comment by dolymood** [comment]
这个场景要看需求了

可以通过 ScrollNavBar 的 `options` Prop 改变这种行为，这块文档好像拉掉了，我们补上

**Comment by chinieer** [comment]
实测可以通过options改变，谢谢了
