### ISSUE TITLE
关于cube-scroll的两个bug

### ISSUE THREAD

**Issue by he429134733** [didi/cube-ui#617]
### Version
1.12.32

### Reproduction link
[https://github.com/didi/cube-ui](https://github.com/didi/cube-ui)

### Steps to reproduce
当我使用cube-scroll 作为整个页面的滚动时，碰到了两个bug， 一个是 当cube-scroll有img标签的时候，如果不指定img的height 在加载完成之后，cube-scroll不能滚动、但是元素显示的很正常 只是不能滚动，当我用纯文字的时候 很正常。 第二个 当我使用require（img）的时候 也是发生了一样的bug

### What is expected?
能够正常滚动

### What is actually happening?
不能滚动

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这个底层依赖bs的，图片之类的，在高度没有得到之前 都是不能滚动的，自己需要监听处理才可以的
通过 refresh 刷新
