### ISSUE TITLE
关于 cube-scroll-nav-bar和cube-scroll-nav-panel  组合使用的时候，右侧的滚动带动不了左侧的导航了

### ISSUE THREAD

**Issue by whl122677** [didi/cube-ui#628]
如果cube-scroll-nav  使用的时候   里面加入了cube-scroll-nav-bar   然后左侧点击是正常的  但是右侧的滚动可以滚动，但是带动不了左侧的导航了
![OUCOW29_~BK9%B$SKO3`DQ2](https://user-images.githubusercontent.com/47175490/68289235-bcd4b980-00c0-11ea-8d83-86e2616fe730.png)
![ISN3VM95B({ 0MBXH0Q58J](https://user-images.githubusercontent.com/47175490/68289237-bd6d5000-00c0-11ea-9745-819a8880e49c.png)

不是道是不是BUG  还是我没写对  但是我已经来回试了好多次了

**Comment by whl122677** [comment]
不知道我说的是不是很清楚      不加cube-scroll-nav-bar   这个自定义的话   是正常的  左侧点击  右侧正常      右侧滑动左侧也是正常高亮          加上cube-scroll-nav-bar     右侧滑动，左侧不高亮了

**Comment by dolymood** [comment]
提供个demo仓库看下吧

**Comment by whl122677** [comment]
[VipTable.txt](https://github.com/didi/cube-ui/files/3817457/VipTable.txt)

麻烦你把文件的后缀名改为.vue的      谢谢你   这是一个dome 页面

**Comment by dolymood** [comment]
```html
<cube-scroll-nav-bar
                 slot="bar"
                  direction="vertical"
                  :current="current"
                  :labels="labels"
                  @change="changeHandler">
                  <p slot-scope="props">
                    <span>{{props.txt}}</span><span>20个</span>
                  </p>
                </cube-scroll-nav-bar>
```html

这里的current是传入的
可以改成：
```html
<cube-scroll-nav-bar
                 slot="bar"
                 slot-scope="props"
                  direction="vertical"
                  :current="props.current"
                  :labels="props.labels"
                  @change="changeHandler">
                  <p slot-scope="props">
                    <span>{{props.txt}}</span><span>20个</span>
                  </p>
                </cube-scroll-nav-bar>
```html

差异就能看出来，不变的原因就是 current 传入了 而 current是一直不变的

**Comment by whl122677** [comment]
这样的话  页面好像不能刷新了，一刷新就报错     先注销掉这块代码正常现在   再打开这段代码正常显示， 但是刷新一下就不行了
![5L3N480{_@OG_R A6~X6S20](https://user-images.githubusercontent.com/47175490/68374464-ea346c80-017f-11ea-8de1-9cc17c6579d9.png)
