### ISSUE TITLE
使用scroll组件时，点击某一项不能设置点击后的样式

### ISSUE THREAD

**Issue by xhtea** [didi/cube-ui#632]
### Version
1.12.32

### Reproduction link
[https://jsbin.com/zohayepemo/edit?html,output](https://jsbin.com/zohayepemo/edit?html,output)

### Steps to reproduce
直接点击某一项

### What is expected?
点击时，能使点击项加上背景色，告诉用户已经点击了该项

### What is actually happening?
在电脑端展示时，点击了能改背景色；
但在移动端无效，点击了背景颜色不能改变

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

**Comment by dolymood** [comment]
bs默认阻止了touch行为 所以不会生效 你想要的应该是类似于 IndexList 的效果 可以去参考实现
