### ISSUE TITLE
[New Feature] 类似于安卓的NestedScrolling效果

### ISSUE THREAD

**Issue by wj20160318** [didi/cube-ui#635]
### What problem does this feature solve?
内外两层滚动，先滚外层，后滚内层。bs现在貌似做不到这种效果，如果用disable和enable，外层滚到底后，开启内层，需要重新touch，才能滚动内层

### What does the proposed API look like?
  希望bs提供api，依然监听滑动事件，只是不滚动。设为可滚动时，不需要重新touch

**Comment by dolymood** [comment]
https://didi.github.io/cube-ui/example/#/scroll/h-scrolls
这种？

**Comment by wj20160318** [comment]
上面的是先滚内后滚外，不太一样
