### ISSUE TITLE
[New Feature] input 输入框能设置attr的属性，比如想添加pattern

### ISSUE THREAD

**Issue by 303182519** [didi/cube-ui#637]
### What problem does this feature solve?
input 输入框能设置attr的属性，比如想添加pattern

### What does the proposed API look like?
:attr="{pattern: '\\d*' }"

**Comment by dolymood** [comment]
这是需要做利用原生的来做校验吗

**Comment by 303182519** [comment]
`<input type="number" pattern="\d*" oncontextmenu="return false" oncopy="return false" onpaste="return false" oncut="return false" autocomplete="off">`

就是想加一些原始的属性上去，比如pattern="\d*"能控制移动端的键盘显示

**Comment by dolymood** [comment]
我们新增一个 pattern 吧，未来会使用 $attrs 去修复这类问题
