### ISSUE TITLE
Scroll组件用起来用点顿，不太流畅，体验不是很好

### ISSUE THREAD

**Issue by StruggleThunder** [didi/cube-ui#643]
### Scroll组件不流畅问题，请问可以加什么代码解决下吗 ？
```
 <cube-scroll 
ref="scroll" 
:data="articleList" 
:options="options"
@pulling-down="onPullingDown"
@pulling-up="onPullingUp">

</cube-scroll>
```

**Comment by theniceangel** [comment]
是在安卓上么

**Comment by StruggleThunder** [comment]
> 是在安卓上么

安卓和苹果都有。
就是手指用力向上滑动，感觉会有0.1 - 0.2 秒的延迟然后内容再向下滚动。所以体验起来就感觉有点顿。

**Comment by dolymood** [comment]
是不是内容有很多  或者内容里 有很多图片？

**Comment by StruggleThunder** [comment]
> 是不是内容有很多 或者内容里 有很多图片？

内容和图片也不多，这是地址。http://www.clluo.com:9000/index
用手机浏览器打开就可以感受下，总觉得慢半拍。初次加载的时候很慢，可能要等10秒钟。

**Comment by dolymood** [comment]
好像是有那么一点点，我们也深入研究下，简单看的是在touchstart的时候 有时候会比较耗时

**Comment by dolymood** [comment]
在快速滚动的情况下，touch事件的响应是可能会有点长，浏览器也会做一些判断。
额外的，我发现，在”发现“tab中，内容即使是完全加载完毕后，滚动也还是很流畅。通过Chrome layers发现，在”科普“tab中存在一些样式上问题，引起的是有动态的合成层的生成，建议通过样式手段优化掉，把上边的slide单独成层（例如，给 cube-slide 增加 z-index 1），不影响下边的内容，应该会好一点。

**Comment by StruggleThunder** [comment]
> 在快速滚动的情况下，touch事件的响应是可能会有点长，浏览器也会做一些判断。
> 额外的，我发现，在”发现“tab中，内容即使是完全加载完毕后，滚动也还是很流畅。通过Chrome layers发现，在”科普“tab中存在一些样式上问题，引起的是有动态的合成层的生成，建议通过样式手段优化掉，把上边的slide单独成层（例如，给 cube-slide 增加 z-index 1），不影响下边的内容，应该会好一点。

好的，谢谢，我看看。
