### ISSUE TITLE
upload组件files-added方法在微信浏览器中选择相册图片时不会被触发，机型为华为Honor 9,安卓系统9，EMUI版本9.1.0

### ISSUE THREAD

**Issue by pisces22745** [didi/cube-ui#650]
### Version
1.12.34

### Reproduction link
[https://contract-qa.gongmall.com/upload_id_card](https://contract-qa.gongmall.com/upload_id_card)

### Steps to reproduce
1、在微信浏览器中打开链接 https://contract-qa.gongmall.com/upload_id_card
2、点击身份证上传按钮，选择相册，选择图片完成返回

### What is expected?
图片会展示在身份证框内

### What is actually happening?
选择相册时图片不能显示，选择拍照时图片会显示

### Dependencies Version
vue: 2.6.9
better-scroll: 1.15.0

---
目前在系统浏览器中均可正常调起files-added回调，只有在微信浏览器中不能触发回调

**Comment by dolymood** [comment]
可以试验 原生 input type file 是否有效，之前经验是很多webview都会禁掉文件上传能力

**Comment by xfFelix** [comment]
问题解决了吗？
