### ISSUE TITLE
Vue CLI3.0集成cube-ui因为Vue CLI3.0的vue.config.js没有plugins属性，无法集成第三方插件，官方文档也没有详细介绍这块，能提供下集成方案吗？

### ISSUE THREAD

**Issue by fuyunjinglong** [didi/cube-ui#652]
Vue CLI3.0集成cube-ui因为Vue CLI3.0的vue.config.js没有plugins属性，无法集成第三方插件，官方文档也没有详细介绍这块，能提供下完整的Vue CLI3.0集成cube-ui集成方案吗？急急急

**Comment by dolymood** [comment]
没明白？
