### ISSUE TITLE
 日期选择器DatePicker 设置时间,跟实际显示时间不对应.

### ISSUE THREAD

**Issue by changguoli** [didi/cube-ui#654]
this.datePicker = this.$createDatePicker({
          title: 'Date Picker',
          min: new Date(2019, 9, 8),
          max: new Date(2020, 9, 20),
          value: new Date(),
          onSelect: this.selectHandle,
          onCancel: this.cancelHandle
        })
设置起始时间为 2019-09-08, 实际时间为 2019-10-08, 有时候我设置起始时间为2019-12-16, 实际起始时间为2020-01-17. 希望遇到这个问题的给个解决方案

**Comment by tank0317** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by tank0317** [comment]
月份是从 0 开始的。
