### ISSUE TITLE
slide组件中.cube-slide-dots  div样式问题

### ISSUE THREAD

**Issue by xsw911213** [didi/cube-ui#66]
### Version
1.2.6

### Reproduction link
[https://jsfiddle.net/xsw911213/50wL7mdz/87547/](https://jsfiddle.net/xsw911213/50wL7mdz/87547/)

### Steps to reproduce
前提：动态设置根字体（使用rem布局，参考淘宝的跟字体设置）
1、使用slide组件
2、因在css初始化的时候加入了line-height:1，导致有默认高度。

### What is expected?
解决方案：

手动为.cube-slide-dots设置line-height:1px

### What is actually happening?
因为有默认高度，所以导致后面的a标签基本无法点击。

### Dependencies Version
vue: 2.5.13
better-scroll: 1.7.0

**Comment by AmyFoxFN** [comment]
thanks for you  feedback~😆
