### ISSUE TITLE
Radio的默认插槽文档有错误

### ISSUE THREAD

**Issue by celverbamboo** [didi/cube-ui#660]
![image](https://user-images.githubusercontent.com/24216880/71428447-ca3f1500-26fb-11ea-9176-7348b7bd84e1.png)
![image](https://user-images.githubusercontent.com/24216880/71428460-d4f9aa00-26fb-11ea-9160-2e9845e6601b.png)

**Comment by dolymood** [comment]
As https://github.com/didi/cube-ui/issues/463
