### ISSUE TITLE
cube-form中schema怎么配置textarea的最大长度

### ISSUE THREAD

**Issue by caoyan0829** [didi/cube-ui#661]
{
                type: "textarea",
                modelKey: "textareaValue",
                label: "Textarea",
                rules: {
                  required: true
                },
                // debounce validate
                // if set to true, the default debounce time will be 200(ms)
                debounce: 400
              }

**Comment by dolymood** [comment]
props 传入prop控制

**Comment by caoyan0829** [comment]
了解&nbsp; 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "doly mood"<notifications@github.com&gt;; 
发送时间: 2019年12月31日(星期二) 下午5:18
收件人: "didi/cube-ui"<cube-ui@noreply.github.com&gt;; 
抄送: "曹罡瑜"<735768974@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [didi/cube-ui] cube-form中schema怎么配置textarea的最大长度 (#661)




props 传入prop控制
