### ISSUE TITLE
cube-scroll-nav-bar组件在MatePad Pro（横屏）/Mate X（全/半屏）时，change事件会失效，是什么原因吗？

### ISSUE THREAD

**Issue by fuyunjinglong** [didi/cube-ui#662]
cube-scroll-nav-bar组件在MatePad Pro（横屏）/Mate X（全/半屏）时，change事件会失效，可能是什么原因导致？急急急

**Comment by dolymood** [comment]
你需要在那种状态发生改变的时候 去主动的 刷新 refresh 组件
