### ISSUE TITLE
Picker中的 实例hide()方法不生效

### ISSUE THREAD

**Issue by caoyan0829** [didi/cube-ui#664]
![image](https://user-images.githubusercontent.com/31430084/71974657-ff477d80-324c-11ea-9238-aae9c38b47ac.png)

**Comment by caoyan0829** [comment]
怎么用动态数据去展示 地址选择器

**Comment by dolymood** [comment]
差一个 tick，可以 nextTick(() => this.picker.hide())

但是目测你的逻辑 没必要 这样做

只需要上边判断好展示状态  直接控制 `this.visibleVal` 岂不是更好
