### ISSUE TITLE
data-picker组件 手机选一下就卡死了  谷歌正常

### ISSUE THREAD

**Issue by caoyan0829** [didi/cube-ui#667]
组件：
![image](https://user-images.githubusercontent.com/31430084/72231628-81da8f00-35f7-11ea-96c1-7794da1eb3cf.png)

主页html：
![image](https://user-images.githubusercontent.com/31430084/72231645-9a4aa980-35f7-11ea-9da9-ef5098d8b960.png)

methods:
![image](https://user-images.githubusercontent.com/31430084/72231695-dbdb5480-35f7-11ea-8514-cd18199ac52b.png)

**Comment by caoyan0829** [comment]
组件：
<template>
  <cube-cascade-picker
    ref="cascadePicker"
    :title="placeholder"
    :data="data"
    :selectedIndex="selectedIndex"
    @select="select"
    @cancel="cancel"
  ></cube-cascade-picker>
</template>

<script>
/* eslint-disable */
const COMPONENT_NAME = "date-picker";
const EVENT_SELECT = "select";
const EVENT_CANCEL = "cancel";

export default {
  name: COMPONENT_NAME,
  props: {
    placeholder: {
      type: String,
      default: ""
    },
    min: {
      type: Array,
      default() {
        return [2010, 2, 1];
      }
    },
    max: {
      type: Array,
      default() {
        return [2020, 2, 1];
      }
    },
    selectedIndex: {
      type: Array,
      default() {
        return [0, 0, 0];
      }
    }
  },
  data() {
    return {};
  },
  computed: {
    data() {
      let data = range(this.min[0], this.max[0], false, "年");

      data.forEach(year => {
        let minMonth = year.value === this.min[0] ? this.min[1] : 1;
        let maxMonth = year.value === this.max[0] ? this.max[1] : 12;

        year.children = range(minMonth, maxMonth, false, "月");
        year.children.forEach(month => {
          let day = 30;
          if ([1, 3, 5, 7, 8, 10, 12].indexOf(month.value) > -1) {
            day = 31;
          } else {
            if (month.value === 2) {
              day =
                !(year.value % 400) || (!(year.value % 4) && year.value % 100)
                  ? 29
                  : 28;
            }
          }

          let minDay =
            year.value === this.min[0] && month.value === this.min[1]
              ? this.min[2]
              : 1;
          let maxDay =
            year.value === this.max[0] && month.value === this.max[1]
              ? this.max[2]
              : day;

          month.children = range(minDay, maxDay, false, "日");
        });
      });

      return data;
    }
  },
  methods: {
    show() {
      this.$refs.cascadePicker.show();
    },
    hide() {
      this.$refs.cascadePicker.hide();
    },
    select(selectedVal, selectedIndex, selectedText) {
      this.$emit(EVENT_SELECT, selectedVal, selectedIndex, selectedText);
    },
    cancel() {
      // this.$emit(EVENT_CANCEL);
    }
  }
};

function range(n, m, polyfill = false, unit = "") {
  let arr = [];
  for (let i = n; i <= m; i++) {
    let value = (polyfill && i < 10 ? "0" + i : i) + unit;
    arr.push({
      text: value,
      value: i
    });
  }
  return arr;
}
</script>

**Comment by caoyan0829** [comment]
showStartDatePicker() {
      this.$refs.startDatePicker.show();
    },
    showEndDatePicker() {
      this.$refs.endDatePicker.show();
    },
    dateStartSelectHandler(selectedVal) {
      console.log(selectedVal);
      this.model.businessStart =
        // utils.formatTime(
        //   new Date(
        new Date(
          selectedVal[0],
          selectedVal[1] - 1,
          selectedVal[2]
        ).toDateString();
      // ).getTime(),
      // "Y-MM-dd"
      // );
      // if (this.model.businessStart && this.model.businessEnd) {
      //   if (
      //     new Date(this.model.businessEnd).getTime() >=
      //     new Date(this.model.businessStart).getTime()
      //   ) {
      //     this.model.manageDate = true;
      //   } else {
      //     this.model.manageDate = false;
      //   }
      // }
    },
    dateEndSelectHandler(selectedVal) {
      console.log(selectedVal);
      this.model.businessEnd = new Date(
        selectedVal[0],
        selectedVal[1] - 1,
        selectedVal[2]
      ).toDateString();
      // this.model.businessEnd = utils.formatTime(
      //   new Date(
      //     new Date(
      //       selectedVal[0],
      //       selectedVal[1] - 1,
      //       selectedVal[2]
      //     ).toDateString()
      //   ).getTime(),
      //   "Y-MM-dd"
      // );

      // if (this.model.businessStart && this.model.businessEnd) {
      //   if (
      //     new Date(this.model.businessEnd).getTime() >=
      //     new Date(this.model.businessStart).getTime()
      //   ) {
      //     this.model.manageDate = true;
      //   } else {
      //     this.model.manageDate = false;
      //   }
      // }
    },

**Comment by caoyan0829** [comment]
<cube-form-item :field="fields[19]" class="data-button-box">
              <cube-button
                :light="true"
                @click="showStartDatePicker"
                :class="model.businessStart ? '' : 'data-button'"
              >{{ model.businessStart || '经营期限（起）' }}</cube-button>
              <span class="data-line"></span>
              <cube-button
                :light="true"
                @click="showEndDatePicker"
                :class="model.businessStart ? '' : 'data-button'"
              >{{ model.businessEnd || '经营期限（止）' }}</cube-button>
              <date-picker
                ref="startDatePicker"
                :min="[2010, 1, 1]"
                :max="[2030, 1, 1]"
                :placeholder="model.businessStart || '经营期限（起）'"
                @select="dateStartSelectHandler"
              ></date-picker>
              <date-picker
                ref="endDatePicker"
                :min="[2010, 1, 1]"
                :max="[2030, 1, 1]"
                :placeholder="model.businessEnd || '经营期限（止）'"
                @select="dateEndSelectHandler"
              ></date-picker>
            </cube-form-item>

**Comment by caoyan0829** [comment]
`<cube-form-item :field="fields[19]" class="data-button-box">
              <cube-button
                :light="true"
                @click="showStartDatePicker"
                :class="model.businessStart ? '' : 'data-button'"
              >{{ model.businessStart || '经营期限（起）' }}</cube-button>
              <span class="data-line"></span>
              <cube-button
                :light="true"
                @click="showEndDatePicker"
                :class="model.businessStart ? '' : 'data-button'"
              >{{ model.businessEnd || '经营期限（止）' }}</cube-button>
              <date-picker
                ref="startDatePicker"
                :min="[2010, 1, 1]"
                :max="[2030, 1, 1]"
                :placeholder="model.businessStart || '经营期限（起）'"
                @select="dateStartSelectHandler"
              ></date-picker>
              <date-picker
                ref="endDatePicker"
                :min="[2010, 1, 1]"
                :max="[2030, 1, 1]"
                :placeholder="model.businessEnd || '经营期限（止）'"
                @select="dateEndSelectHandler"
              ></date-picker>
            </cube-form-item>`

**Comment by dolymood** [comment]
不要这样贴，建议整合到一个中

这样大家都没法看，也没法复现

这个先close掉了，还请提供repo以及复现步骤到一个新的issue中
