### ISSUE TITLE
datapicker组件设置的最小时间时出现BUG

### ISSUE THREAD

**Issue by xuetian120** [didi/cube-ui#669]
"better-scroll": "^1.15.2",
使用better-scroll最新依赖包，出现报错，麻烦处理一下~

@wo5516820 谢谢反馈。不过我在当前的 1.12.10 版本上验证了下，没有发现这个问题。所以想问下，你用的是哪个版本呢？

_Originally posted by @AmyFoxFN in https://github.com/didi/cube-ui/issues/402#issuecomment-460129679_

**Comment by dolymood** [comment]
cube-ui版本应该没问题

**Comment by xuetian120** [comment]
不支持更高版本better-scroll吗
