### ISSUE TITLE
upload拍照有的手机会闪退iphone7

### ISSUE THREAD

**Issue by caoyan0829** [didi/cube-ui#671]
![image](https://user-images.githubusercontent.com/31430084/72487504-31f30680-3849-11ea-98ce-4c3605352a39.png)
![image](https://user-images.githubusercontent.com/31430084/72487516-3d463200-3849-11ea-8f46-77c1769ac41a.png)
使用iphone7拍照时会出现闪退的问题，iphone6s（12.3.1）拍照会出现form表单刷新问题，其它部分手机正常
华为手机EMUI（9.1.0）upload，在app内部使用upload无反应，在浏览器正常

**Comment by caoyan0829** [comment]
<cube-upload
                  ref="businessLicenseUrl"
                  v-model="model.businessLicenseUrl"
                  :action="businessLicenseAction"
                  @files-added="addedHandler('businessLicenseUrl')"
                  @file-error="errHandler"
                >
                  <div class="clear-fix">
                    <cube-upload-file
                      v-for="(file, i) in model.businessLicenseUrl"
                      :file="file"
                      :key="i"
                    ></cube-upload-file>

                    <cube-upload-btn :multiple="false">
                      <div>
                        <i></i>
                        <p>上传营业执照照片</p>
                      </div>
                    </cube-upload-btn>
                  </div>
                </cube-upload>

**Comment by caoyan0829** [comment]
businessLicenseAction: {
        target: () => {
          return this.action + "?type=3&code=" + this.model.organizationCode;
        },
        checkSuccess: (res, file) => {
          console.log("res", res);
          if (res.code == 179) {
            this.createToastFun();
          } else if (res.code == 200) {
            return true;
          }
        }
      },

**Comment by dolymood** [comment]
As https://github.com/didi/cube-ui/issues/445
