### ISSUE TITLE
Upload: 可以控制图片删除按钮显示、隐藏吗？

### ISSUE THREAD

**Issue by Jesonhu** [didi/cube-ui#672]
## What is expected?

有个这样一个场景，最多上传 `3` 张图片，当上传 2 张以上的图片时，这时如果要删除上传的图片，最少要保留 `1张`（最后一张图片不能删除）。所以看到这个需求时，第一时间想到的是控制删除按钮，如果只有1张图片时就禁用(不显示)删除按钮。但是没有发现控制这个按钮的 API 和文档说明。

**Comment by dolymood** [comment]
建议使用层加控制逻辑 在外层控制 class 比较好

本身目前确实没有提供Api控制
