### ISSUE TITLE
Component must have name while using create-api!

### ISSUE THREAD

**Issue by liubian333** [didi/cube-ui#674]
### Version
1.12.34

### Reproduction link
[https://github.com/cube-ui/vue-create-api/issues/14](https://github.com/cube-ui/vue-create-api/issues/14)

### Steps to reproduce
1、使用createApi 出问题
2、代码如下
import { createAPI } from 'cube-ui'
import Vue from 'vue'
import HeaderDetail from 'components/header-detail/index.vue'
createAPI(Vue, HeaderDetail)

### What is expected?
网页正常运行

### What is actually happening?
网页空白

### Dependencies Version
vue: 2.6.11
better-scroll: 1.15.0

---
参考https://github.com/cube-ui/vue-create-api/issues/14
仍然出现问题

**Comment by dolymood** [comment]
使用 TS？
