### ISSUE TITLE
关于"TypeError: this.$createRecycleList is not a function"错误，$createRecycleList()方法未定义的问题

### ISSUE THREAD

**Issue by feligo887** [didi/cube-ui#676]
实例化RecycleList组件中this.$createRecycleList()方法报错找不到这个方法。
但是在test/unit/specs/recycle-list.spec.js文件中51行 是有这个方法的。
另外在https://didi.github.io/cube-ui/#/zh-CN/docs/recycle-list中
RecycleList这个组件的实例方法reset我在vue-create-api中也没有找到相应的使用方法 和 任何的 这个实例化方法的使用方式和实例只有  “清空列表全部内容，重置数据” 的这一句说明，请在文档写清楚谢谢，不然我用了4个小时翻了源码，我都用不出来。
如果能看到，求解决，很急谢谢答复。

**Comment by dolymood** [comment]
1. 测试文件中并没有 $createRecycleList，也和 vue-create-api 没有关系
2. 组件实例化方法，这部分Vue中有详细介绍，通过 ref 获取组件实例

**Comment by feligo887** [comment]
按照官方文档逻辑 来说 $createRecycleList(),不应该是内置方法么？您这说要我 自己定义？ 但是还在最下面写有reset()这个实例化方法，那就不应该让使用者自己去实例化啊。
