### ISSUE TITLE
<cube-upload /> :multiple 组件在安卓手机无法多选照片

### ISSUE THREAD

**Issue by donley828** [didi/cube-ui#680]
### Version
1.12.36

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1.ios手机正常

### What is expected?
安卓手机可以多选

### What is actually happening?
不能多选

### Dependencies Version
vue: 2.6.11
better-scroll: 1.15.0

**Comment by dolymood** [comment]
这个移动端系统本身限制 前端这块没法解决 😄
