### ISSUE TITLE
checkbox 手动设置选中

### ISSUE THREAD

**Issue by shijianchun** [didi/cube-ui#685]
checkbox首次选中后，手动设置v-model绑定值为false后，此时checkbox变成未选中状态；
再次点击，在未选中的状态下，期待选择后的@input返回值是true, 但是返回的是false;

或者有其他方式再第一次选中后，手动设置为选中状态完全生效？

**Comment by dolymood** [comment]
没有复现你的case
我这实验是OK的状态

**Comment by shijianchun** [comment]
和版本号有关吗？我这边是 cube-ui@1.12.14
当前确实出现这个问题

**Comment by dolymood** [comment]
可以试试更新到最新版本试试
