### ISSUE TITLE
使用ScrollNav组件，里面的图片二维码无法长按识别

### ISSUE THREAD

**Issue by Scott1995** [didi/cube-ui#689]
使用ScrollNav组件，里面的图片二维码无法长按识别

**Comment by dolymood** [comment]
可以这样试试

```html
<cube-scroll-nav :options="{preventDefault: false}"  />
```

原因是因为 better-scroll 本身会禁止事件默认行为

我们之前疏忽，options 配置项没体现在文档上 现在已经加了

**Comment by Scott1995** [comment]
加上这个配置之后  浏览器滚动行为会跟better-scroll冲突  虽然能识别二维码了 但是效果很差

**Comment by Scott1995** [comment]
加上这个配置之后 浏览器滚动行为会跟better-scroll冲突 虽然能识别二维码了 但是效果很差

**Comment by Scott1995** [comment]
加上这个配置之后 浏览器滚动行为会跟better-scroll冲突 虽然能识别二维码了 但是效果很差

**Comment by Scott1995** [comment]
应该是使用这个 <cube-scroll-nav :options="{preventDefaultException: { className:/(^|\s)img(\s|$)/}}"  />

**Comment by Scott1995** [comment]
{preventDefaultException: { className:/(^|\s)img(\s|$)/}}
