### ISSUE TITLE
input组件autofocus自动对焦属性无效

### ISSUE THREAD

**Issue by jietoulufei** [didi/cube-ui#691]
<cube-input
  v-model="value"
  :placeholder="placeholder"
  :type="type"
  :autofocus="autofocus"
>
</cube-input>
export default {
  data() {
    return {
      value: '',
      placeholder: '请输入内容',
      type: 'password',
      autofocus: true,
    }
  }
}

Chrome进入手机调试模式
页面载入后，输入框没有自动获取焦点

**Comment by dolymood** [comment]
autofocus 在移动端本来就是不好使的 只有PC模式可用
