### ISSUE TITLE
在ios和安卓中 点击upload打开的照片图库中没有视频可以选择

### ISSUE THREAD

**Issue by feng9217** [didi/cube-ui#702]
### Version
1.12.38

### Reproduction link
[https://jsfiddle.net/mwx7nafc/](https://jsfiddle.net/mwx7nafc/)

### Steps to reproduce
在ios和安卓中打开项目, 点击 请上传教学视频 后, 打开的照片图库中只有相片, 没有视频

### What is expected?
点击upload组件 在照片图库中能选择照片及视频

### What is actually happening?
在照片图库中只有照片

### Dependencies Version
vue: 2.6.11
better-scroll: 1.15.0

**Comment by dolymood** [comment]
应该是因为 accept 默认设置了 image 你可以参考修改

**Comment by feng9217** [comment]
ok 已经解决了 谢谢

**Comment by feng9217** [comment]
> 应该是因为 accept 默认设置了 image 你可以参考修改

ok 已经解决了 谢谢
