### ISSUE TITLE
date-picker使用中发现的bug

### ISSUE THREAD

**Issue by lijingjian001** [didi/cube-ui#703]
### Version
1.12.38

### Reproduction link
[http://jsrun.net/fT2Kp/edit](http://jsrun.net/fT2Kp/edit)

### Steps to reproduce
当datepicker对象中的max中的值为new Date()时,日期弹窗出不来。报Cannot read property 'findIndex' of undefined的异常。

### What is expected?
期望当max属性为new Date()时,可以出现日期弹框。

### What is actually happening?
max属性为new Date()时,日期弹框不出现,并且报异常。

### Dependencies Version
vue: 2.6.11
better-scroll: 1.15.0

---
和better-scroll没关系,应该。

**Comment by dolymood** [comment]
你的min比max大引起的

**Comment by lijingjian001** [comment]
> 你的min比max大引起的

你确定?
![image](https://user-images.githubusercontent.com/12969526/82555980-6d0c9a00-9b9b-11ea-88ab-e31ef4baa078.png)

**Comment by lijingjian001** [comment]
> 你的min比max大引起的

好的,看到了,好长时间不写js了,忘了日期初始化的时候要注意,月份的时候,4代表5月了。

**Comment by lijingjian001** [comment]
说真的,能不能在官网示例中添加jsfidder那样的示例,就像muse-ui一样。
