### ISSUE TITLE
使用upload上传图片在关闭auto自动上传后 上传第二张图片会自动变为自动上传

### ISSUE THREAD

**Issue by ijunwu** [didi/cube-ui#706]
### Reproduction link
[https://didi.github.io/cube-ui/#/zh-CN/docs/upload](https://didi.github.io/cube-ui/#/zh-CN/docs/upload)

### Steps to reproduce
使用upload上传图片在关闭auto自动上传后 上传图片前套用picker选择器选择图片类型， 上传第二张图片时候会自动变为自动上传

### Dependencies Version
vue: 
better-scroll: 

---

**Comment by dolymood** [comment]
看代码逻辑并不会 除非调用了 start
这个请提供复现链接
