### ISSUE TITLE
预览图片 放大时会突然闪一下

### ISSUE THREAD

**Issue by feng9217** [didi/cube-ui#707]
### Reproduction link
[http://none](http://none)

### Steps to reproduce
预览图片时, 对图片进行放大浏览

### What is expected?
放大时尽量顺滑

### What is actually happening?
放大超过某些大小时 会闪一下(显示底色后再显示放大后的图片)

### Dependencies Version
vue: 
better-scroll:

**Comment by feng9217** [comment]
![04e0435fdeeee8f766ba83838bddb998](https://user-images.githubusercontent.com/6224010/83130741-5c1ad600-a111-11ea-9e87-e7e0a343db7d.gif)

**Comment by dolymood** [comment]
好 应该是 ios13.4后的bug，我们修下

**Comment by feng9217** [comment]
13.3.1 的 6s
13.3 的 11 
都发生了这个

**Comment by feng9217** [comment]
> 我这边手机 13.4.1 没有问题 你那边提供更多手机设备信息

13.3.1 的 6s
13.3 的 11
都发生了这个

**Comment by dolymood** [comment]
1.12.42 版本已修复
