### ISSUE TITLE
upload

### ISSUE THREAD

**Issue by whl122677** [didi/cube-ui#708]
<input class="cube-upload-input" type="file" @change="changeHandler" :multiple="false" accept="image/*" capture="camera">

现在调取摄像头的话 华为 vivo有兼容  加上这个属性的话会好很多   我测试的华为手机没办法调取摄像头直接调取了相册      用的是webAPP网页   不是APP软件

 capture="camera"   想添加一个这个属性怎么添加

**Comment by zhaoshiqi123** [comment]
我也遇到这个问题，怎么解决的大哥

**Comment by whl122677** [comment]
通过$refs往下找  找到那个input   动态添加属性吧     我是一进入页面就添加
this.$nextTick(function () {
				this.$refs.inp.$el.lastChild.setAttribute('capture','camera')
			})

**Comment by zhaoshiqi123** [comment]
谢谢大哥，i try one down hahahaha..

**Comment by zhaoshiqi123** [comment]
改完之后点击调用相机会闪退，这是安卓系统的问题吗

**Comment by whl122677** [comment]
这个我到碰到 我改过目前一切是正常的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhaoshiqi123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 中午12:57
收件人:&nbsp;"didi/cube-ui"<cube-ui@noreply.github.com&gt;;
抄送:&nbsp;"王鸿禄"<122677892@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [didi/cube-ui] upload (#708)





 
改完之后点击调用相机会闪退，这是安卓系统的问题吗
