### ISSUE TITLE
vue-cli 4.4.4 执行 vue add cube-ui 报错

### ISSUE THREAD

**Issue by CSZRZ** [didi/cube-ui#715]

**Comment by CSZRZ** [comment]
node 版本号 12.7.0
@vue/cli 4.4.4

**Comment by CSZRZ** [comment]
Module not found: Error: Can't resolve './cubeic.ttf' in '/xxxx/node_modules/cube-ui/src/common/stylus'

**Comment by dolymood** [comment]
vue-cli 的配置中 关于 css stylus 的 options 中有没有
'resolve url': true 的配置项

有的话 就不应该会出现这个问题

**Comment by H-zk** [comment]
我遇到了同样的问题，改了 "stylus-loader" 版本为 "3.0.2" 
然后全局引入 cube-ui 后，继续在 vue.config.js 中这么配置一下，暂时解决了
![image](https://user-images.githubusercontent.com/23274145/140052232-10764750-5132-4ca9-84e9-def4e40d2011.png)
