### ISSUE TITLE
当升级了better-scroll后，时间选择器，会经常性的卡死

### ISSUE THREAD

**Issue by SevenWang666** [didi/cube-ui#716]
当升级了better-scroll后，时间选择器，会经常性的卡死，能否解决这个bug

**Comment by dolymood** [comment]
cube-ui 依赖的是 1.12 的版本 不知你升级的bs是哪个的

**Comment by SevenWang666** [comment]
1.15.2

**Comment by SevenWang666** [comment]
版本高了，怎么就不行了

**Comment by dolymood** [comment]
cube-ui 还没升级到那么高版本 因为有一些breaking change 在
目前只能搭配1.12的先
