### ISSUE TITLE
[New Feature] Why don't the popup series provide a template method call?

### ISSUE THREAD

**Issue by clmystes** [didi/cube-ui#73]
### What problem does this feature solve?
i want to implement customized component,  but  popup series is difficult for me to do this without template or jsx. i also saw
```
<div class="cube-picker-footer"></div>
```
in the source code , why not give a `slot` to me.
Or i'm  fundamentally wrong.

### What does the proposed API look like?
like basic component

**Comment by AmyFoxFN** [comment]
It's always supported.  Popup series could be used in template, like basic component, although we recommend to used by API

**Comment by clmystes** [comment]
Sorry, it's my bad. i didn't read the introduction but component doc first.
very thanks.
