### ISSUE TITLE
how to use options to scroll vertical item in cube slide

### ISSUE THREAD

**Issue by myomyintaung1411** [didi/cube-ui#731]
Cube tip]: <cube-slide> The property "allow-vertical" is deprecated, please use the recommended property "options" to replace it. Details could be found in https://didi.github.io/cube-ui/#/en-US/docs/slide#cube-Propsconfiguration-anchor

**Comment by dolymood** [comment]
https://better-scroll.github.io/docs-v1/doc/en/options.html#eventpassthrough
value vertical

We need to update bs/docs link
