### ISSUE TITLE
[New Feature] ScrollNav 组件 自定义面板标题

### ISSUE THREAD

**Issue by CleverBamboo** [didi/cube-ui#738]
### What problem does this feature solve?
面板标题必须显示，不可以定制。例如需要做成类似京东详情这样的页面就不行, [京东详情](https://item.m.jd.com/product/100007627021.html?sku=100007627021&_fd=jdw&price=2799.00&fs=1&jxsid=16039356529920016759&pos=2&csid=3bcc3f3af74f0f195d53b5ea37c0d1c8_1603939075849_1_1603939075850&ss_symbol=10&ss_mtest=new_arch_fd_feature_log,shop_entrance_t1,wx_d3_new,~sak7|mixtag_sak7r,sak7_m_mwdl_l6967,sak7_m_ensa_l6486,sak7_m_gwjd_r,sak7_m_am_l5415,sak7_m_jwb_r,sak7_m_rmd_r,sak7_m_rmso_l6742,sak7_m_rmp_r,sak7_m_rms_r,sak7_m_mawx_r,sak7_m_ntab_r,sak7_s_krw_r,sak7_s_bdw_r,sak7_s_am_r,sak7_s_run_r,sak7_s_rmo_l6269,sak7_s_rat_r,sak7_s_rbr_l6685,sak7_s_rpr_r,sak7_s_ram_r,sak7_s_rbm_l6214,sak7_s_rba_r,sak7_s_rpm_l7465,sak7_s_rpa_r,sak7_s_rpb_r,sak7_s_rbam_r,sak7_s_rpam_r,sak7_s_rpbm_r,sak7_s_rpba_r,sak7_s_pbam_l7583,sak7_s_rsd_l7468,sak7_s_rspr_l7665,sak7_s_mawx_r,sak7_s_rdpw_l6800,sak7_s_rtw_r,sak7_b_ri_r,sak7_o_kss_l3931,sak7_o_ons_l3957,sak7_o_oca_l5174|&key=%E7%A9%BA%E8%B0%83&ss_pos_type=normal&ptag=138769.3.2&sceneval=2)
![image](https://user-images.githubusercontent.com/24216880/97518922-34d37800-19d3-11eb-990a-7765a0daf586.png)

### What does the proposed API look like?
增加一个props属性，面板标题是否显示, is-show-title: true\flase

**Comment by dolymood** [comment]
描述的再详细点？

**Comment by CleverBamboo** [comment]
@dolymood 
![image](https://user-images.githubusercontent.com/24216880/97521014-93025a00-19d7-11eb-938d-24b53e9b38dd.png)
没有属性可以隐藏这个标题，并且不能自定义！

**Comment by dolymood** [comment]
这个样式解决不就好了
