### ISSUE TITLE
关于TimePicker最小可选时间的问题

### ISSUE THREAD

**Issue by zhuping** [didi/cube-ui#748]
看了下 `TimePicker` 最小时间的 demo，min 设置是 `+new Date() - (2 * 60 + 20) * 60 * 1000`，即当前时间的过去140分钟。比如我当前时间是 `11:31`，减去 140 分钟应该是 `09:11`，但是组件表现还是可选 `09:10`，这算是一个已经**过去**的时间了，超出我最小时间范围了。
![image](https://user-images.githubusercontent.com/1574767/103393103-f5a0df00-4b5b-11eb-97b1-759a564675ce.png)

看了下代码，应该是这里使用了向下取整的原因
https://github.com/didi/cube-ui/blob/dev/src/components/time-picker/time-picker.vue#L133

**Comment by QiuShuiBai** [comment]
@zhuping 这个不是bug哈，可以看下[文档](https://didi.github.io/cube-ui/#/zh-CN/docs/time-picker)上的 `minuteStep` 配置。
其中 `rule` 选项用来配置取整方式，默认向下取整。

**Comment by zhuping** [comment]
@QiuShuiBai 试了下用 `minuteStep` 确实可以，感谢
