### ISSUE TITLE
系统内的h1 h2 h3等标签的默认样式都不生效

### ISSUE THREAD

**Issue by hellolex** [didi/cube-ui#753]
### Version
1.12.38

### Reproduction link
[https://github.com/didi/cube-ui/issues/752](https://github.com/didi/cube-ui/issues/752)

### Steps to reproduce
移动端有部分页面内容是在其他系统的富文本编辑器录入的，但是在cubeui中显示的话发现简单的h1 h2 h3 b之类的标签都无法正常显示
查看了下样式代码发现cubeui默认定义了这些标签的font-size:100%，导致标签的默认样式无法显示

### What is expected?
让html默认标签可以有自身默认的特性

### What is actually happening?
<h1><h2>之类的标签都无法有其应有的默认效果

### Dependencies Version
vue: 2.6.11
better-scroll: 2.1.1

**Comment by dolymood** [comment]
As #752
