### ISSUE TITLE
安装cube报错 ./cubeic.ttf in ./node_modules/css-loader/dist/cjs.js??ref--11-oneOf-3-1!./node_modules/postcss-loader/src??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/cube-ui/src/common/stylus/index.styl

### ISSUE THREAD

**Issue by gaowei887** [didi/cube-ui#754]
ERROR  Failed to compile with 2 errors                                                                                                                                  4:44:58 PM

These relative modules were not found:

* ./cubeic.ttf in ./node_modules/css-loader/dist/cjs.js??ref--11-oneOf-3-1!./node_modules/postcss-loader/src??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/cube-ui/src/common/stylus/index.styl
* ./cubeic.woff in ./node_modules/css-loader/dist/cjs.js??ref--11-oneOf-3-1!./node_modules/postcss-loader/src??ref--11-oneOf-3-2!./node_modules/stylus-loader??ref--11-oneOf-3-3!./node_modules/cube-ui/src/common/stylus/index.styl

**Comment by dolymood** [comment]
As https://github.com/didi/cube-ui/issues/39

请参照 https://didi.github.io/cube-ui/#/zh-CN/docs/quick-start

核心 stylus 的配置项 需要配置  `resolve url`
