### ISSUE TITLE
[New Feature] Dialog 增加是否显示确定按钮

### ISSUE THREAD

**Issue by TaylorWolfX** [didi/cube-ui#756]
### What problem does this feature solve?
用处:在页面弹起一个无法关闭的Dialog,只用来提示用户,阻止用户继续操作
场景:我有一个活动,活动到期,用户再次进入我的活动页,提示用户,活动已过期

### What does the proposed API look like?
showConfirm:false

**Comment by dolymood** [comment]
dialog一定是可关闭的，交互上 不考虑这种情况

如果真的要实现，可以通过自己指定 `btns` 插槽
