### ISSUE TITLE
jsx使用form表单时model传值为空

### ISSUE THREAD

**Issue by sy-fe** [didi/cube-ui#758]
### Version
1.12.38

### Reproduction link
[https://codesandbox.io/s/peaceful-bouman-5l8fh?file=/src/views/Home.vue](https://codesandbox.io/s/peaceful-bouman-5l8fh?file=/src/views/Home.vue)

### Steps to reproduce
form表单jsx 语法，model传值传不过去，
template 语法正常，
但是我必须要用render jsx语法

### What is expected?
默认值可以正常回显

### What is actually happening?
没有回显

### Dependencies Version
vue: 2.6.11
better-scroll: 2.1.4

**Comment by dolymood** [comment]
vue jsx 的问题 参考

https://github.com/vuejs/jsx/issues/49
