### ISSUE TITLE
datepicker default min max time have problem

### ISSUE THREAD

**Issue by AdamYLK** [didi/cube-ui#760]
### Version
1.12.38

### Reproduction link
[http://no.need.code.to.show](http://no.need.code.to.show)

### Steps to reproduce
default use $createDatePicker to create a picker

### What is expected?
the min and max choose time is depends on the real time, no a const value.
like new Date() to give the time.

### What is actually happening?
the default min and max time has passed

### Dependencies Version
vue: 2.6.11
better-scroll: 2.2.1

**Comment by QiuShuiBai** [comment]
@AdamYLK  This is not a bug. But you can customize min and max as needed. 

As example:
```js
min: [new date().getFullYear() - 4, 1, 1, 0, 0, 0]
```

Consider that some users may have used the default value of min and max. So we will not modify the  default value.
