### ISSUE TITLE
[New Feature] cube-ui是不怎么维护了吗？better-scroll都v2.3了，cube-ui引用的还是1.几的版本

### ISSUE THREAD

**Issue by wenye123** [didi/cube-ui#765]
### What problem does this feature solve?
cube-ui是不怎么维护了吗？better-scroll都v2.3了，cube-ui引用的还是1.几的版本

### What does the proposed API look like?
引用最新版的better-scroll，以支持多重嵌套等功能

**Comment by dolymood** [comment]
是因为有breaking change 所以没升级

cube-ui本身是支持嵌套的，只是不能支持多重嵌套，只能支持两层的

升级bs会随着重构升级，内部已经在做了
