### ISSUE TITLE
drawer 默认项 bug

### ISSUE THREAD

**Issue by iiicon** [didi/cube-ui#766]
![image](https://user-images.githubusercontent.com/19875237/117258532-a78c4700-ae7f-11eb-8170-f9dcd6477e79.png)

```js
 watch: {
      selectedIndex(newVal) {
        this.selected = [...newVal]
      }
    }
```

selectedIndex 要观察成员，否则一直不变

**Comment by dolymood** [comment]
在变的情况下，只考虑 重新赋值场景，没必要deep

**Comment by iiicon** [comment]
好的
