### ISSUE TITLE
cube-tab-bar showSlider初始不生效，点了其他tab签才出现

### ISSUE THREAD

**Issue by ray1347227** [didi/cube-ui#772]
cube-tab-bar默认高亮tab2，但是初始加载时下划线没有显示，在点击了其他tab签时才出现，感谢好心人帮忙解答
![image](https://user-images.githubusercontent.com/21354564/122006746-c7e9e280-cde9-11eb-98a4-2b01faeaee02.png)
![image](https://user-images.githubusercontent.com/21354564/122006799-da641c00-cde9-11eb-850c-95150e63a41c.png)

![image](https://user-images.githubusercontent.com/21354564/122006663-abe64100-cde9-11eb-8e8b-b4ae7e04c9f6.png)
![image](https://user-images.githubusercontent.com/21354564/122006706-b9033000-cde9-11eb-9318-387ae26dd9ff.png)

**Comment by dolymood** [comment]
官方的示例貌似就是这样写的
可以提供线上复现demo 看下
