### ISSUE TITLE
如何用cdn方式单独加载组件化方式使用

### ISSUE THREAD

**Issue by goldencolor** [didi/cube-ui#78]
比如  CascadePicker组件
我只用到了这个功能，并且不在标准es6 vue环境下开发，要如何使用 ，原生 webview 里面通过加载js方式使用

**Comment by dolymood** [comment]
如果说只用一个的话，可以在引入之前声明全局 module 变量，

如果引用多个，那么需要按需加载的加载器，支持cmd的

**Comment by dolymood** [comment]
当然也可以简易来做：

```js
      const modules = {}
      const module = {}
      Object.defineProperty(module, 'exports', {
        set: function (value) {
          modules[value.name] = value
        }
      })
```

结果 modules 的结构：

![image](https://user-images.githubusercontent.com/2121554/35229951-b35e4f4a-ffcf-11e7-823c-2e79f7def548.png)
