### ISSUE TITLE
关于cube-scroll组件构建后dom(class='.cube-scroll-list-wrapper')内出现 "undefined" 文本节点

### ISSUE THREAD

**Issue by enazou** [didi/cube-ui#781]
### Version
1.12.38

### Reproduction link
[https://user-images.githubusercontent.com/22870788/130575714-9cf803be-3050-4b7d-8c12-825caf89392a.png](https://user-images.githubusercontent.com/22870788/130575714-9cf803be-3050-4b7d-8c12-825caf89392a.png)

### Steps to reproduce
开发环境不会出现，在生存环境在每个使用了Scroll 组件的dom元素内部都会生成"undefined" 文本节点

### What is expected?
期望给点建议或解决方案

### What is actually happening?
不明原因

### Dependencies Version
vue: 2.6.14
better-scroll: 2.4.2

**Comment by xyduane** [comment]
解决了吗，我也出现了，怎么解决的
