### ISSUE TITLE
cube-upload在ios15.4.1以上传不了图片？

### ISSUE THREAD

**Issue by AvengerAssembles** [didi/cube-ui#802]
### Version
1.12.38

### Reproduction link
[https://cube-ui.gitee.io/#/zh-CN/example](https://cube-ui.gitee.io/#/zh-CN/example)

### Steps to reproduce
你们官网的upload示例可直接复现。

### What is expected?
能成功上传

### What is actually happening?
上传不了

### Dependencies Version
vue: 2.7.4
better-scroll: 2.4.2

**Comment by dolymood** [comment]
https://cube-ui.gitee.io/example

应该是嵌套在iframe中原因，这个是实际的示例地址 我实验了下 没问题的
