### ISSUE TITLE
scroll 的参数data 必须得是 数组吗

### ISSUE THREAD

**Issue by qinzitong** [didi/cube-ui#94]
### Version
1.4.2

### Reproduction link
[]()

### What is expected?
使用scroll 能不实现固定头部、底部而页面的在滚动

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.0

**Comment by dolymood** [comment]
如果传的话 就传数组 还可以不传也行，那就是默认插槽情况

**Comment by qinzitong** [comment]
如果只能传数组的化，scroll 这个组件就只能解决 数组的滚动问题，解决不了页面的滚动问题啊。
<div>
  <div id="header"></div>
  <div id="wrapper-content">
    <div id="content1"></div>
    <div id="content2"></div>
    <div id="content3"></div>
    ......
  </div>
  <div id="bottom"></div>
</div>

这样的结构，像固定顶部、底部，整个内容部分需要滚动

**Comment by dolymood** [comment]
还可以选择不传入，直接使用默认插槽也可以的
