### ISSUE TITLE
使用 CascadePicker 时，多级联动很慢

### ISSUE THREAD

**Issue by hdwong** [didi/cube-ui#97]
### Version
1.4.2

### Reproduction link
[https://didi.github.io/cube-ui/example/#/cascade-picker](https://didi.github.io/cube-ui/example/#/cascade-picker)

### Steps to reproduce
1. showCascadePicker
2. 切换1级菜单
3. 观察2级菜单切换

### What is expected?
2级菜单快速切换

### What is actually happening?
2级菜单切换缓慢

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.0

---
数据量并不大，在手机和在PC调试都有这个问题，经常造成2级菜单误点（因为上次的2级菜单还没有完成切换）。
个人猜测是1级菜单滚动延时太长。

**Comment by dolymood** [comment]
滚动时间是计算出来的 如果普通picker和timepicker一样的

**Comment by AmyFoxFN** [comment]
这目前是组件的正常表现，要等上一级的滚动完全停下来，才会计算下一级的数据。如果在滚动过程中实时计算，计算太频繁，消耗太大。

**Comment by AmyFoxFN** [comment]
不过确实交互问题还挺难受的，我们之后会考虑怎么来优化一下。
谢谢反馈啊

**Comment by AmyFoxFN** [comment]
新加了一个 swipeTime属性用来设置快速滚动动画延时，减小时长可以用来优化这个问题，但会对滚动体验有损，你可以试试看找一个合适的值。1.5.0发布，对应PR：#104
