### ISSUE TITLE
npm install 提示网络错误

### ISSUE THREAD

**Issue by 974929538** [didi/cube-ui#99]
### Version
1.4.2

### Reproduction link
[https://github.com/didi/cube-ui](https://github.com/didi/cube-ui)

### Steps to reproduce
npm install 时 提示网络错误

### What is expected?
npm install 成功

### What is actually happening?
npm install 失败

### Dependencies Version
vue: 2.5.13
better-scroll: 1.8.0

**Comment by dolymood** [comment]
npm 私服？ 这个和 cube-ui 没关系，和私服平台有关系

**Comment by 974929538** [comment]
network request to http://artifactory.intra.xiaojukeji.com:80/artifactory/api/npm/npm/which/download/which-1.3.0.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.intra.xiaojukeji.com artifactory.intra.xiaojukeji.com:80

**Comment by ustbhuangyi** [comment]
请不要暴露任何滴滴内部的信息，用外部 npm 安装即可
